### ISSUE TITLE
Where to store design docs

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#1008]
As discussed a bit on the side, we need a place to store our design docs. It should be public, easy to find the key docs, and add to by committers. Need to discuss where the best place is, e.g. git repo, git issue, ...?

Next, we'll need to prime it with a few architecture docs - e.g. how IDEs, cwctrl, and portal communicate, and the new hybrid design.

**Comment by jgwest** [comment]
Some options:
- Use the Wiki tab of one of the repos (need webmaster to enable)
- Use Markdown in Git repo (but requires committer to merge, and edits might trigger product builds)
- https://github.com/eclipse/codewind-wiki (?)

**Comment by ssh24** [comment]
I think what we could have is a README in the codewind repo that describes the overall codewind architecture (with pictures, text, etc.). Similar to the architecture drawing we showed in the cascon booth. We could also have the description of each modules -> Turbine, Portal, IDE. 

This level of docs should be fairly simple and as Jonathan mentioned if we want to store in detailed docs, we can use a more detailed wiki.
<img width="806" alt="Screen Shot 2019-11-06 at 10 46 38 AM" src="https://user-images.githubusercontent.com/15173354/68313526-b889ab80-0082-11ea-9679-593cf4cd1f0b.png">

**Comment by GeekArthur** [comment]
Regarding architecture docs, we can use the same idea as Eclipse Che. Eclipse Che adds the `Che architecture` link under `Contributing` section of `README` in the Eclipse Che Github Repository: https://github.com/eclipse/che#contributing, then the `Che architecture` link points to the actual Che architecture docs: https://www.eclipse.org/che/docs/che-7/che-architecture.html. They host the actual docs on Eclipse org docs site `https://www.eclipse.org/che/docs`, we may have the similar site or use codewind-wiki directly to host docs.

**Comment by jopit** [comment]
Needs to be easily accessible from github
Needs to allow easily collaboration

wiki at eclipse.org (used by WTP for design)?
codewind-wiki?
set up a separate repo for design docs like Che does?
investigate what Kabanero is doing and follow suite?

**Comment by jgwest** [comment]
Another option: create a new repo under our [codewind-resources org](https://github.com/codewind-resources), for example `github.com/codewind-resources/wiki`. 

Since this org is under our control, rather than the Eclipse webbmaster's, we can allow edits from logged-in users without requiring them to be committers. This also has the advantage of allowing us to continue using markdown (unlike Eclipse) and provides a modern familiar UI for developers (unlike Eclipse).

The disadvantage is that it will live in a different org than the rest of our code (but so would the wiki.eclipse.org option), but to mitigate this we can add a link to the above repo from our existing `eclipse/codewind-*` repos.

**Comment by jopit** [comment]
We'll use codewind-resources org, we'll create a new repo in this org, and will create separate folders for each area

**Comment by jopit** [comment]
Repo is here: https://github.com/codewind-resources/design-documentation

**Comment by jgwest** [comment]
@jopit @deboer-tim Can this be closed?

**Comment by jopit** [comment]
Yes, closing
