### ISSUE TITLE
Insecure upgrade message after vscode upgrade

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#1058]
**Codewind version:** 6 (devt build)
**OS:**  MacOS

**Che version:**
**IDE extension version:** 6.0 (dev)
**IDE version:**   VSCode 1.39.2
**Kubernetes cluster:**

**Description:**

**Steps to reproduce:**

After upgrading my 0.5 (GA) plugin to 0.6 (devt build) I received an error in vscode and the following log output

About to upgrade projects from /Users/watsona/codewind-workspace
{"error":"unable to find any codewind projects","error_description":"stat /Users/watsona/codewind-workspace/.projects/: no such file or directory"}
==> End cwctl --json --insecure upgrade --ws /Users/watsona/codewind-workspace

This only occurs the first time I start VSCode after the docker images have been downloaded, and assume this is part of a migration process ?.   My concern was that the popup error in vscode was "Insecure Download" which may concern users

I have seen this twice now using different build levels.

**Workaround:**

**Comment by tetchel** [comment]
this isn't a bug, this is how cwctl works, the `--insecure` flag disables SSL cert checking, since we don't have a proper solution for self-signed certs at this time

does `/Users/watsona/codewind-workspace` exist, or not?

**Comment by AndyRWatson** [comment]
Thanks @tetchel, yes it does and it did have existing projects in the directory. 

From a concern point I am wondering how this message is perceived by a user who is migrating or using for the first time. May panic people over what they have just downloaded ?! (Thoughts)

**Comment by tetchel** [comment]
some thoughts:
1. we could rename `--insecure` to something clearer like `--disable-certcheck` so users can see what's happening
2. we could remove `--insecure` altogether for 0.6 since there's no remote connections anyway, it has no effect, but that just pushes the problem to when we actually ship remote support in 0.7
3. (in 0.7) we could actually fix the ssl cert problem in the codewind backend and not have to pass this flag anymore

@tobespc any thoughts from portal pov?

**Comment by jopit** [comment]
@AndyRWatson you say you’re also seeing a pop up in vscode that says “Insecure Download” separate from  the —insecure flag?  That sounds like something we should change.

**Comment by AndyRWatson** [comment]
Sorry typo. The message said ‘insecure upgrade‘ not  ‘insecure download’

**Comment by jopit** [comment]
OK, then I think the fix needs to come from portal.

**Comment by jcockbain** [comment]
@tobespc could I be assigned?

**Comment by tobespc** [comment]
lets pursue fixing this as per comment above 
```
(in 0.7) we could actually fix the self-signed cert problem in the codewind backend and not have to pass this flag anymore
```

**Comment by markcor11** [comment]
Its not so much "insecure upgrade" its actually :

1.  --insecure
2.  upgrade

the first is a global flag to turn off certificate checking and is the same name that curl uses to perform the same function. 

Since Kubernetes environments out of the box install with self signed certs and we have to be able to deploy into those environments we have to turn off certificate checking until we know that the services have valid certs. 

That said,  for upgrade specifically --insecure is not required at all since it does not communicate with Codewind PFE but works on local data.   We do not upgrade remote projects.

**Comment by jcockbain** [comment]
`upgradeProjects` works fine for me, when the path to `.projects` exists.

As @markcor11 says, we always upgrade projects to `local` connection, so the `insecure` flag isn't needed when calling bind. (https://github.com/eclipse/codewind-installer/blob/master/pkg/project/upgrade.go#L59). So we could just remove the flag wherever we invoke it (IDE's etc.). 

As for renaming the flag, it was named `--insecure` to match curl. We've had a few discussion about using sticking to convention wherever possible with our `cwctl` commands.

**Comment by tobespc** [comment]
this is the standard way of doing this, closing
