### ISSUE TITLE
[odo] Investigate and add odo templates

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#1115]
We have removed a couple of odo templates since they were not working correctly.  This item is to investigate to see if there are any that are working again (especially Java ones) and add those back to the list of templates

**Comment by lentheivendra** [comment]
Currently ODO officially only fully supports node.js and Java, and partially supports other languages/components like python, perl , ruby, etc.

For java templates,  https://github.com/spring-projects/spring-petclinic.git as mentioned in https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.html seems to be a good candidate. Since OKD by default doesn't come with a java component, a java image stream would need to be imported into OKD and tagged as a builder. So that leads to some questions:
1) We could provide a sample script to import and setup a java image stream as a builder .. but that imagestream/builder would have to use a known name so that our extension tools can match the template (in our master-index.json) to it (since the builder name will be listed when calling odo catalog list components
2) Or maybe better to do 1) as part of our odo extension installation? And name the imagestream/builder something unique like codewind-odo-java18 or whatever which we can then use as key to match up with the template in our master-index.json. Using a unique name hopefully will lessen the chance of conflict with any pre-existing java components the user might've set up on his cluster. If not doable when installing the extension, then probably best to merge this setup task with the rbac setup tasks into one script for the user.

**Comment by lentheivendra** [comment]
Some measured times for templates doing odo create+build, running >=3 times:

redhat-openjdk-18/openjdk18-openshift:latest: 108s, 193s, 195s
openjdk/openjdk-11-rhel8:latest: authentication needed to import image stream
openjdk/openjdk-11-rhel7:latest: 220s, 115s, 172s, 108s
rhscl/nodejs-8-rhel7:latest: 67s, 44s, 29s, 29s
rhoar-nodejs/nodejs-8:latest: 73s, 37s, 28s, 28s
rhoar-nodejs/nodejs-10:latest: 60s, 43s, 28s

**Comment by GeekArthur** [comment]
@lentheivendra Thanks, Len. Last Friday I asked Charlie from odo development team for the odo build performance as well. He said currently there is no big performance difference among odo supported image stream, I think your metrics can also prove that, from your metrics looks like the performance is environment-driven instead of image-driven (running time increases/decreases at the same time). Regarding performance, we may need to investigate templates to find light templates that are compatible with odo to improve the performance.

**Comment by lentheivendra** [comment]
Will using issue #1111 to update docs related to this item (i.e. instructing users how to use example script to import jdk image stream and add as odo builder, change of directory name for odo extension helper/setup files, etc)

**Comment by GeekArthur** [comment]
PR has been merged, verified, close the issue.
