### ISSUE TITLE
Create a feature in a minute video(s) for Open API

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1129]
Create a feature in a minute video for the Open API tools. May need two if you want to do vscode and eclipse.

Adding docs tag since content should be reviewed by ID.

**Comment by rtaniwa** [comment]
Personally I don't feel our FIUM videos need to be shown for both Eclipse and VS Code. In the videos, we can narrate that the extension is available for both, but I don't think it is necessary to have a video for each.

**Comment by beccabau** [comment]
I'm happy to work on this FIUM (preferably using vscode). Just let me know who I need to work with from the Appsody squad  to get this done :).

**Comment by keithchong** [comment]
Hi @beccabau , I'll be working on this.  What is the format of and guidance for the video?  Eg. resolution, size, will we add the 'bubble' comments or are we going to narrate, etc?

**Comment by beccabau** [comment]
Hi Keith, the only hard requirements are an intro/outro (located https://github.ibm.com/dev-ex/devAdvocacy/tree/master/Media/videos). 
- I would recommend as high resolution as you can (at least 1080p), since that will look nicer in general
- We can be pretty creative with these (just keep them under a minute). Some of the videos are narrated over, others have text on the screen (which can be a little more difficult to read). I am happy to narrate if you don't want to, or we can add text or bubble comments and some subtle background music.

**Comment by rtaniwa** [comment]
My two cents, I prefer a video with narration for general use over one with just text. The latter is great for conferences or venues where there may not be audio available at a ped etc, but for general use videos I think they are much better received when there is someone narrating. :)

**Comment by keithchong** [comment]
@rtaniwa, I agree that someone narrating it is better in this video series.   Another question, @beccabau , is there some leeway regarding the 1 minute limit?  Including the intro (3 sec) and outtro (5 sec), my video is 1:21 in length.  Also do you mind if I send you the video part only for your review?  (It is Full HD (1920x0180) and is 43MB in size.)  Note also that I enabled the option to show mouse clicks, which shows a circle whenever the mouse button is clicked.  Perhaps this should be done in the other videos in this series for consistency.

**Comment by beccabau** [comment]
Yes, you can send it to me. We might be able to speed it up a tad. I think by the nature of the series (features in under a minute), the content should be at least a minute or less.

**Comment by AndyRWatson** [comment]
yep gotta be under a minute,   we've already had one nit comment that our first video shows as 1:00 and technically not under a minute :-o

+1 on the 1080p .mp4,  thats what we've been using for all the other videos and please also upload to https://ibm.ent.box.com/folder/80656701482 when complete so we have a backup incase we ever need to edit again in the future

@beccabau we should really look to document these tips etc,   one for us in the new year :-)

**Comment by keithchong** [comment]
I've reduced it down to 0:59 - I had to talk fast.  The mp4 file has been uploaded to the above box location ( https://ibm.ent.box.com/file/591630850498 ).  Please review.  I have the video only file, and the transcript if you think someone else should do the audio for this video, or for all the videos in the series, for consistency.

**Comment by beccabau** [comment]
Thanks Keith, will review after playback

**Comment by beccabau** [comment]
Okay, just watched it - I'm impressed you were able to fit all the content in under a minute! 

@AndyRWatson  - I'm a little worried that this sounds more like a "how to" instead of a feature highlight, but I think it's great content that we should make sure is available for people looking to use. What do you think about going with Keith's original speed and putting this under tutorials?

And/or we could instead pick out some "highlights" (i.e. why it makes sense to use Codewind for OpenAPI development/why OpenAPI in Codewind is so cool!) for a FIUM video.

**Comment by AndyRWatson** [comment]
Yes I agree @beccabau I think we should expand this video to be the how to and look to create a separate FIUM video which is more like a trailer and inline with the existing videos https://www.youtube.com/channel/UCnKCVK6RFDyHFqUmXlAhCHQ/playlists

One thing though i'd like to call out that FIUM videos today have no sound, however we should be also including audio and not precedenting on a silent FIUM video.

My other comment was tha the introduction was more around spring app development, rather than specifically addressing how this differentiates around openAPI.  That woiuld be good to call out up front.   Lets look to address the speed (maybe more like 2 to 3 mins for a how to video) and how we can help create the FIUM equivalent

**Comment by rtaniwa** [comment]
+1 to adding a narrator. at a personal level i am much less likely to watch any kind of tech video that has no sound. this should be a requirement imho.

**Comment by sishida** [comment]
This issue is no longer a priority. @micgibso and I agree to close it.
