### ISSUE TITLE
VS Code should provide access to raw template urls

### ISSUE THREAD

**Issue by deboer-tim** [eclipse/codewind#1153]
I was trying to see where one of the template sources went to. Although the popup with the URL in it was nice, I couldn't find any way to copy and paste that into a browser. In Eclipse this is easy because it shows the raw url in the dialog.

I'm not suggesting we adopt the Eclipse UI (different IDE, and it's nice that the URL wasn't shown by default), but there should be a way of copying it.

**Comment by tetchel** [comment]
in the template source manager, clicking the template name will open the template in the browser, does that meet your requirement?

**Comment by deboer-tim** [comment]
In this case there was a redirect, so the browser opened, immediately went to the redirect, cleared out the url bar, and downloaded. The only way to get back to any url was going backwards from the download history which showed the redirect url instead of the original.

I don't love an explicit button either, but maybe if it's just a copy icon it wouldn't clutter the UI a lot.

**Comment by tetchel** [comment]
@thisguy-1

**Comment by GeekArthur** [comment]
> clicking the template name will open the template in the browser

I am using Eclipse Che (not VS Code), and click the template name find the following behavior:

Default templates: have access issue, seems like it tries to access `https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/index.json` but fails, probably due to redirection issue
![Screen Shot 2019-11-15 at 11 45 39 AM](https://user-images.githubusercontent.com/15131537/68960252-d00d1680-079d-11ea-8279-be401c7914e5.png)

OpenShift templates: Nothing happen since it uses file system link

Appsody templates: Download the index.json file directly

What is the expected behavior? Open the index.json from browser or directly download the file?

**Comment by GeekArthur** [comment]
Also I may need to create a separate issue to do the correspond changes for OpenShift templates to support the expected behavior

**Comment by tetchel** [comment]
it's supposed to open in a new tab, and definitely used to do this. The opening of it in within the Theia webview is new, and is definitely not what I want.

The behaviour of downloading the file vs just viewing it depends on your browser.

**Comment by jcockbain96** [comment]
With the redirect issue, I'm now back working on https://github.com/eclipse/codewind/issues/614 to have `cwctl` handle github redirects.

**Comment by tetchel** [comment]
FWIW you can always just open `repository_list.json` and view the urls there

**Comment by deboer-tim** [comment]
Yeah, I did get it from there. This is a pretty minor issue, just felt like there should be a way for the user to get it from this page vs having to find out where we store settings.
