### ISSUE TITLE
Allow user to specify multiple docker registry credentials

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#1178]
If the user has an Appsody project with a custom stack/collection for which images are pushed to a registry other than Docker Hub, the project is unable to build because the codewind container does not have the credentials to login to internal docker registry to pull the required images.

To fix this, we need to allow the user to specify credentials for a number of image registries that PFE can use to pull the images.

See [Codewind not able to work with stacks images in the internal registry/non-docker hub](https://github.com/eclipse/codewind/issues/938)
See [Dynamic registry setup for the local scenario](https://github.com/eclipse/codewind/issues/948)
See [[Hybrid] Create docker registry secret in kube](https://github.com/eclipse/codewind/issues/665)

**Comment by jopit** [comment]
For local minimum is to set the credentials for one private pull registry
For and one private push registry

**Comment by jopit** [comment]
**Hybrid & Che**

- Need to specify one docker registry for Codewind projects to push to
- Need to specify one or more docker registries for Appsody projects to pull from

**Local**

- Need to specify one or more docker registries for Appsody projects to pull from

**Comment by jopit** [comment]
**Hybrid & Che**
- When the user first creates a codewind project, prompt for the docker registry needed for push

**Local, Hybrid & Che***
Add an item to the connection's context menu to show a 'manage container registries' page which allows user's to add, remove and edit the list of registries that PFE knows about.  The list should also contain the registry needed for push if it exists. The user should be able to change which registry is used for the push from this page.

**Comment by makandre** [comment]
When users enter the registry credentials in the IDEs, I'd like to propose that we do a local `docker login` as well; this would serve 2 purpose:

- we can make sure the creds work before posting them to PFE
- a successful login makes the creds available to local docker for pulling (this is for `appsody init` which happens locally)

**Comment by j-c-berger** [comment]
Feel free to assign me @micgibso  and @sishida

**Comment by tetchel** [comment]
here's the existing page https://www.eclipse.org/codewind/dockerregistry.html

**Comment by tetchel** [comment]
merged https://github.com/eclipse/codewind-vscode/pull/323

**Comment by eharris369** [comment]
@j-c-berger @sishida There is a "Learn more" link in the Manage Registries dialog that needs a URL for the documentation for this feature.  Can you give us a URL even if the documentation is not complete yet so we can update the code?

**Comment by sishida** [comment]
@eharris369 This is the main Docker registry file that I am aware of: https://www.eclipse.org/codewind/dockerregistry.html

If we want to use this link, we should add a new section about specifying multiple Docker registry credentials. We could also link directly to this new section.

**Comment by tetchel** [comment]
Steps 1 and 2 in the linked page are invalid now and should be replaced by the new documentation

**Comment by sishida** [comment]
@j-c-berger Could you handle the doc updates for https://www.eclipse.org/codewind/dockerregistry.html?

Please let me know if you'd prefer me to handle it and/or open a separate issue. Thanks!

**Comment by eharris369** [comment]
Should the examples use the same terms as in the IDEs?  Address for host (docker.io) and namespace for the <username>?

![image](https://user-images.githubusercontent.com/9484320/70471101-8cef4c00-1a9a-11ea-9492-99244652d56e.png)

**Comment by sishida** [comment]
I generally lean on the side of consistency. So unless there's a reason to change up the terms, my vote is for using the same terms. :)

Also, here are some minor edits:
- "Provide registries for projects that need to pull content to build. You can designate a single registry as a push registry."
   - The desktop checker recommends "to" instead of "in order to" because it's less wordy.
   - I also changed the second sentence to active voice.
- "Username" should be one word unless it's already two words throughout Eclipse.

**Comment by j-c-berger** [comment]
@jopit, as always, thank you for the detailed and spot-on feedback! Looking forward to progressing with this issue.

@tetchel,  question regarding your comment on steps 1 and 2 for the `dockerregistry` doc: https://www.eclipse.org/codewind/dockerregistry.html 

Do we want to replace steps 1 and 2 with the content that I'm developing now? Basically, this issue will focus on `dockerregistry` and update those steps? Or, will I be making a whole new doc for this issue (as we earlier discussed) _and_ update `dockerregistry`? In which case, I can open a second issue for the latter since there will be two separate docs being worked on. Thanks!

**Comment by maysunfaisal** [comment]
@j-c-berger with regards to the question addressed to @tetchel, I have put a comment on PR https://github.com/eclipse/codewind-docs/pull/261/files#r357857126

Steps 1 and 2 needs to be merged, because they;re now done with the same UI (Image Registries):
![Screen Shot 2019-12-13 at 5 36 29 PM](https://user-images.githubusercontent.com/31771087/70836704-21291e00-1dcf-11ea-9e83-be7ed199e9e1.png)

But the keys will and commands are no longer relevant with the new UI. See the screenshot above for reference. And I think we can still host the doc at https://www.eclipse.org/codewind/dockerregistry.html

**Comment by sishida** [comment]
@j-c-berger This issue is good to close, correct?
