### ISSUE TITLE
SVT : Eclipse : Mac : Error stopping codewind

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1223]
**Codewind version:**  Codewind tech preview	0.6.0.v201911181940	
**OS:** MAC

**Che version:**
**IDE extension version:**
**IDE version:** 
Eclipse IDE for Enterprise Java Developers.

Version: 2019-09 R (4.13.0)
Build id: 20190917-1200
**Kubernetes cluster:**

**Description:**
Saw an error stopping codewind. May be a network issue but wanted to to have a developer check.
[output from : docker ps -s, docker image -s, and docker volume ls](https://github.com/eclipse/codewind/files/3870138/diag.txt)

**Steps to reproduce:**

**Workaround:** 

<img width="416" alt="Screen Shot 2019-11-20 at 10 35 12 AM" src="https://user-images.githubusercontent.com/16086270/69255265-83eb1900-0b85-11ea-9c1e-b436465dc93c.png">

**Comment by mmulholl** [comment]
[diag.txt](https://github.com/eclipse/codewind/files/3870142/diag.txt)

**Comment by stalleyj** [comment]
@mmulholl Can you please give some detail as to what you were doing to get this error and what projects you had ?  I can see from your 'docker ps' output that there was a swift project running which would have prevented the network from being removed so the real problem is probably why wasn't the swift project stopped. The eclipse log would be very helpful as it should show errors from the cli

**Comment by stalleyj** [comment]
@tobespc Please can you close as we haven't had any update from Martin.

**Comment by tobespc** [comment]
closing as not been seen since 0.6.0 and was a one off.  Without logs we can't progress this
