### ISSUE TITLE
SVT: Project settings update failed: The requested application port is not exposed

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1248]
**Codewind version:** 0.6.0
**OS:** Windows

**Che version:**
**IDE extension version:**  0.6.0
**IDE version:** Eclipse - 2019-09
**Kubernetes cluster:**

**Description:**
After migrating from Codewind 0.5.0 to Codewind 0.6.0 user will get this failure message when projects are getting built.

```Project settings update failed: The requested application port is not exposed```

**Steps to reproduce:**
1. Install Codewind 0.5 release from market place
2. Create Appsody Eclipse Microprofile, Appsody python, Default (Go,Open Liberty) projects.
3. Let it build successfully.
4. Install Codewind 0.6.0 and click on migration from Codewind explorer view.

**Workaround:**

**Comment by elsony** [comment]
@jagraj Can you provide the PFE trace on this one? @rajivnathan just tried and cannot reproduce with microprofile app.

**Comment by jagraj** [comment]
@rajivnathan 
Did you attempt migration scenario as documented in the issue.?

**Comment by rajivnathan** [comment]
Fails for the go project and likely occurs for any of the default docker type projects. The other projects shouldn't have this issue. The cw-settings are being set with an empty applicationPort that Turbine then tries to set for that project. However, if the port is empty it will try to use a default value or look up a port on the project's container (likely isn't running at that time so would not get a port from the container). So it is unable to set the port and returns an error.

However, this problem doesn't happen on import. Only reproduced with migration. This is because the cw-settings file changed code path is only being hit for migration.

**Comment by malincoln** [comment]
Fix is medium risk so will work to fix in next release of 0.7.0

**Comment by jagraj** [comment]
I see this problem even after codewind restart not only during migration. I see all the time when I restart codewind.

**Comment by rajivnathan** [comment]
@jagraj Yep, I was able to reproduce without migration so not surprised you can reproduce it with a restart.

Steps to reproduce without migration:

- create a go project and wait for it to start
- run `docker stop <container id>` to stop the container
- change `contextRoot` to `/` and the error about the port will pop up

Have a potential fix.

**Comment by rajivnathan** [comment]
@jagraj I have delivered a fix for this issue on master. Can you please verify?

**Comment by malincoln** [comment]
@jagraj pls verify and close.  Thanks

**Comment by jagraj** [comment]
I do not see this problem now.
