### ISSUE TITLE
Remote connection: connected but was not ready after 60 seconds

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1265]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OCP 4.2

**Question synopsis:**

I have setup a PFE deployment onto my OCP 4.2 cluster, using the following `cwctl` command:

```
./cwctl --insecure install remote --namespace eclipse-codewind --kadminuser admin --kadminpass xxxxx --krealm codewind --kclient codewind --kdevuser developer --kdevpass xxxxx --ingress apps.makandre42.os.fyre.ibm.com
```

Everything appears to be deployed correctly, however, when I try to create a connection to it in VS code, I'm getting:

```
Failed to connect to https://codewind-gatekeeper-k3esjbv2.apps.makandre42.os.fyre.ibm.com/. makandre42 connected, but was not ready after 60 seconds. Try reconnecting to, or restarting, this Codewind instance.
```

I see the following in gatekeeper logs:

```
Gatekeeper undefined with route authentication and UI Socket pass-through
Gatekeeper configuration:
** PFE Service: https://172.30.236.243:9191
** SESSION_SECRET: <not-displayed>
** REALM: codewind
** CLIENT_ID: codewind
** AUTH_URL: https://codewind-keycloak-k3esjbv2.apps.makandre42.os.fyre.ibm.com
** CLIENT_SECRET: <not-displayed>
** GATEKEEPER_HOST: CODEWIND-GATEKEEPER-K3ESJBV2.APPS.MAKANDRE42.OS.FYRE.IBM.COM
** WARNING ACCESS_ROLE : Access role has not been set in environment
** Gatekeeper: Authentication is enabled - ENABLE_AUTH=1
Added environment route to : /api/v1/gatekeeper/environment
req.originalUrl = /api/pfe/ready
(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
req.originalUrl = /api/pfe/ready
Error: connect EHOSTUNREACH 172.30.236.243:9191
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.30.236.243',
  port: 9191
}
```

Did I miss some steps in the setup?

**Comment by makandre** [comment]
@markcor11 
/area portal

**Comment by makandre** [comment]
[codewind-pfe-k3esjbv2-c9489db76-drf5f-codewind-pfe.log](https://github.com/eclipse/codewind/files/3888462/codewind-pfe-k3esjbv2-c9489db76-drf5f-codewind-pfe.log)

attaching log from PFE

**Comment by tetchel** [comment]
```
Error: error installing: deployments.extensions is forbidden: User "system:serviceaccount:eclipse-codewind:default" cannot create resource "deployments" in API group "extensions" in the namespace "eclipse-codewind"
```

if it's a serviceaccount/rbac problem, perhaps this was caused by the fix for https://github.com/eclipse/codewind/issues/1211

**Comment by markcor11** [comment]
As of yesterday Gatekeeper is now being configured for authorisation as well as authentication.  Per the gatekeeper trace : 

** WARNING ACCESS_ROLE : Access role has not been set in environment

Authorization restricts a PFE installation to a user with a required access role.  This improves security where two users could authenticate and get an access token from a shared Keycloak install and then present those tokens to gain access to a PFE/Gatekeeper.  Authorisation adds roles so that only one of those users (with the required role) can get access. 

CWCTL during deployment will set the appropriate access roles for the user and push them to the gatekeeper config-map as part of this CLI PR : https://github.com/eclipse/codewind-installer/pull/238 which seems to not have been merged yet. 

Both PRs that one and the Codewind PR you are running now :  https://github.com/eclipse/codewind/pull/1258 need to be installed.

**Comment by markcor11** [comment]
The error message in PFE logs : 

```
Error: error installing: deployments.extensions is forbidden: User "system:serviceaccount:eclipse-codewind:default" cannot create resource "deployments" in API group "extensions" in the namespace "eclipse-codewind"
```

Is because you dont have the correct cluster roles set and need the changes from this PR :  https://github.com/eclipse/codewind/issues/1211

**Comment by makandre** [comment]
Thanks @markcor11, I'll retry this after the remaining PRs you mentioned in `cwctl` are merged.
