### ISSUE TITLE
Handle application status for serverless appsody templates to ensure Stopped status is shown

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#1269]
See if there's a way from the extension to determine the state if the server doesn't exist. The code from the codewind side to set the status to stopped was removed" https://github.com/eclipse/codewind/pull/1255

**Comment by elsony** [comment]
One possible way to handle it:
1. Add function to Turbine so that if the port on cw-settings is set to a special value, e.g. -1, it indicates that the app does not have a port for ping so it will not cause error on PFE on failing to ping.
2. Appsody extension handles the status change and relying on something else, e.g. the process is still up and running, and set the correct status of the application.  Given that the app is ready, the original behaviour of staying on starting or stopped are not ideal.  We can consider to set as started as long as the process is up and running (or introduce a special detailed label like ready if really needed for those type of apps with server status set to started).

**Comment by makandre** [comment]
Is this same as https://github.com/eclipse/codewind/issues/314?  Maybe we can close one of these

**Comment by makandre** [comment]
I like the idea of introducing a `ready` label/state between `starting` and `running`, where:

- `starting` -> initial state
- `ready` -> container is up
- `running` -> container is up **and** app is pingable on port

The good news is that all appsody stacks, even ones w/o a server, do already expose a PORT where it is intended that a server will eventually listen on.  So appsody extension can tell Codewind about this PORT as it is done today, and Codewind determines if it is `ready` or `running` depending on how far it can get when it pings the app.

The reason I like this is because this doesn't require yet another layer of processing or logic to poll the application state.  If we used the -1 for the PORT, then I guess appsody extension would itself need to ping the container on the PORT and manage the application state that way, which feels like it's potentially duplicating code that's already tried and tested in Turbine.

So I'm hoping the `ready` state approach can avoid that (plus then other extensions such as ODO won't need to implement their own polling either)

**Comment by sishida** [comment]
When this issue is resolved, we need to revisit the doc content that was added in this PR (https://github.com/eclipse/codewind-docs/pull/188/files) and see if it is still needed in the doc.

**Comment by makandre** [comment]
Had some discussions with @elsony and @sghung on this recently so jotting down some points:

- using the -1 for the port approach, perhaps that could signal to Turbine to ping the application up to the point of determining whether the container is up and running, and not proceed any further with pinging an application endpoint

- but what should happen when we determined that the container is up an running?  Is that a new app state?  (my suggestion [above](https://github.com/eclipse/codewind/issues/1269#issuecomment-558829855) called this a `ready` state, but that might give users the wrong impression that the application is "ready" to be interacted with; we could label it something else).  But in any case @elsony had concerns with having such a state (what are they?)

- side note: if we did have a state for container up and running, could be used to enable the "Open Container Shell" action sooner

- or should -1 signal to Turbine to **not** ping the container/application at all?  Then when the container comes up, what happens, what should the app state be?

@elsony Do you think we should have a tech-topic discussion for this one?

**Comment by jgwest** [comment]
@ssh24: Unable to locate pipeline with name: `in-progress`

**Comment by ssh24** [comment]
Talked with Andrew, it looks like the serverless stacks in Appsody don't come with a .cw-settings file. Since we are going with the solution to have -1 in the .cw-settings file, there is two things to do:

1. Either have appsody create a .cw-settings file by themselves OR another option would be to have something in the IDE where you can click and it would create a generic .cw-settings file - recommended by Andrew and coulde be a tech topic discussion to get the IDE folks on board
2. Turbine logic to deal with the -1 settings in the .cw-settings file, which I will be working on.

Rajiv mentioned to keep this issue open as a parent issue, and I will open a separate issue that deals with #2 above and link it back to this issue.

/unassign

**Comment by rajivnathan** [comment]
@sghung Sakib made the changes on the iterative-dev side in https://github.com/eclipse/codewind/pull/1880 so the changes on the appsody extension can be made now

**Comment by sghung** [comment]
@makandre can you look at Sakib's changes and make the necessary changes on the appsody extension side? Thank you

**Comment by makandre** [comment]
Will take a look, but based on my understanding there isn't anything we need to do in appsody extension

**Comment by ssh24** [comment]
I think the only step left for Appsody is to find out how to create a template .cw-settings file that users know requires to be edited in order for this functionality to work.

This can be done either in Appsody level, or have an enhancement in the UI where with the click of the button a template `.cw-settings` file is created for projects that don't have it. If this is not doable for 0.9.0, we need to be able to document on how a user can create a `.cw-settings` file and set the app port to be -1 in order to avoid a timeout on continuous pinging.

**Comment by makandre** [comment]
Right @ssh24, and we were going to discuss in tech-topics whether to provide that enhancement to create the `.cw-settings` as I recall

**Comment by jopit** [comment]
- Ask appsody team to modify stack description to explain there is no server by default (Andrew/Appsody)
  - related issue: https://github.com/appsody/stacks/issues/602
- Add link to the appropriate docs from the "couldn't ping" message (Turbine team)
  - related issues: https://github.com/eclipse/codewind/issues/1812
- Provide the ability for the user to control the pinging (by setting -1 in .cw-settings file) (Turbine team)
  - related issue: https://github.com/eclipse/codewind/issues/1862
- Appsody (and odo?) extension to create .cw-setting file by default (Andrew/Appsody)

**Comment by makandre** [comment]
Opened https://github.com/eclipse/codewind/issues/1943 for the last bullet point

**Comment by malincoln** [comment]
is this still being targeted for this release (0.9.0)?

**Comment by ssh24** [comment]
I think this needs to be at least documented for 0.9.0 if https://github.com/eclipse/codewind/issues/1943 is not completed

**Comment by makandre** [comment]
PR for 1943 (https://github.com/eclipse/codewind-installer/pull/359) is awaiting review I've pinged @tobespc about it

**Comment by malincoln** [comment]
I'll go ahead and add the docs label for awareness.  We can remove the label if no doc updates are required.  @micgibso @sishida

**Comment by ssh24** [comment]
Just to clarify what I mentioned:

I think a doc is required regardless, even if #1943 goes in, with what the user needs to do in the `.cw-settings` file to stop the app pinging continuously on an app does not have server

**Comment by sishida** [comment]
Hi, team, This is what we had documented earlier for this issue: https://www.eclipse.org/codewind/troubleshooting.html#projects-stuck-in-starting-or-stopped-state

Could we edit this content, or do we need to replace it/add new content?

**Comment by ssh24** [comment]
I think we can add new content under there for the serverless applications. Because users do see app stuck on starting stage on apps that do not have any servers

**Comment by sishida** [comment]
Talked with @makandre during a meeting today. Keep existing documentation but also add a note/section for if your application doesn't have a server listening, you need to take action to stop it from pinging.

**Comment by j-c-berger** [comment]
Please assign me, @sishida, thanks.

**Comment by malincoln** [comment]
> * Ask appsody team to modify stack description to explain there is no server by default (Andrew/Appsody)
>   
>   * related issue: [appsody/stacks#602](https://github.com/appsody/stacks/issues/602)
> * Add link to the appropriate docs from the "couldn't ping" message (Turbine team)
>   
>   * related issues: #1812
> * Provide the ability for the user to control the pinging (by setting -1 in .cw-settings file) (Turbine team)
>   
>   * related issue: #1862
> * Appsody (and odo?) extension to create .cw-setting file by default (Andrew/Appsody)

So, it looks like we are doc'ing this for 0.9.0 + @makandre has completed the last bullet.  
The remaining bullets will likely be completed for the next release.  If so, I can update the release.

**Comment by ssh24** [comment]
@malincoln The 3rd bullet is also done from the Turbine side. That was the first work of this story

**Comment by malincoln** [comment]
So, only these two items remain:

- Ask appsody team to modify stack description to explain there is no server by default (Andrew/Appsody)

    - related issue: appsody/stacks#602

- Add link to the appropriate docs from the "couldn't ping" message (Turbine team)

   - related issues: #1812

**Comment by makandre** [comment]
We asked appsody about status of https://github.com/appsody/stacks/issues/602 today, it's not something that will be available in 0.9.0.  In any case this shouldn't affect what we document

**Comment by ssh24** [comment]
@makandre I am assuming that the change for including a default `.cw-settings` file by default with Appsody stack for 0.9.0 went in? (saw a PR couple of days back that did this change)

Should we be adding some kind of documentation for users who want to use older release appsody stacks that don't come with a `.cw-settings` file on how to create a generic template of it and then still have the new docs of adding the ability to `-1` on internalPort key for this functionality to work.

**Comment by makandre** [comment]
@ssh24 that's a good idea.  In our documentation for specifying the `-1`, maybe we could add a small note saying: If the `.cw-settings` file does not exist, create it with the following contents.  That covers all bases, even if user somehow deleted that file by accident.

**Comment by ssh24** [comment]
Yes, agreed. @j-c-berger Would you be able to do assist with that doc? I can help with the technical details if you need help

**Comment by j-c-berger** [comment]
@ssh24, yes, I am happy to help and have been assigned this issue. I'm also working on 1812, which to my understanding, is in conjunction to this issue. 

I'll reach out for the technical details as I plan to make more headway on this issue next week, starting Monday. Thanks!

**Comment by rajivnathan** [comment]
@sghung can you please take a look and see if the doc is okay from an Appsody perspective?

**Comment by sghung** [comment]
Verified the doc is okay (pull #360). Closing as requested by Sakib
