### ISSUE TITLE
cwctl not sending json to stdout

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1276]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

Some commands (don't know how many are affected) are not sending json to stdout stream, for example:

`cwctl --json --insecure project create some_path > output.txt`  (output.txt is empty)

Whereas:

`cwctl --json --insecure templates list > output.txt` (output.txt has expected json)

Possible caused by https://github.com/eclipse/codewind-installer/commit/4fc72319c060331e0173cfa5b7c653fc829d6878

**Steps to reproduce:**

**Workaround:**

**Comment by makandre** [comment]
The PR reverts the change for `project create`: https://github.com/eclipse/codewind-installer/pull/241

**Comment by tetchel** [comment]
we cannot bind projects because of this

**Comment by johnmcollier** [comment]
Adding hot label as this'll block most dev / testing of Codewind on Che

**Comment by tetchel** [comment]
also not on che 🙃

**Comment by johnmcollier** [comment]
@yangcao77 Said she was seeing this on Che?

**Comment by tetchel** [comment]
it is broken everywhere

**Comment by makandre** [comment]
If someone merges https://github.com/eclipse/codewind/issues/1276 we can at least unblock the bind

**Comment by liamchampton** [comment]
Sorry! By default logrus prints to `stderr`. Will fix this by sending it to `stdout` by default (forgot to add that into PR https://github.com/eclipse/codewind-installer/commit/4fc72319c060331e0173cfa5b7c653fc829d6878)

**Comment by liamchampton** [comment]
Would also like to mention the actual cause of this issue was a small mistake by changing an `fmt` -> `logr`. No `json` output should have been touched by PR https://github.com/eclipse/codewind-installer/commit/4fc72319c060331e0173cfa5b7c653fc829d6878 but this one slipped in. https://github.com/eclipse/codewind-installer/pull/241 has fixed it and after re-revewing the code changes that originally went in, this should be the only occurrence. PR https://github.com/eclipse/codewind-installer/pull/242 will also rectify logrus info logging going to the wrong stream.

**Comment by liamchampton** [comment]
@makandre can this be closed? - The logrus PR has been reverted so this shouldn't be an issue anymore

**Comment by makandre** [comment]
ok, closing
