### ISSUE TITLE
[odo] Add auto detection logic for binding odo application

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#1285]
For odo applications that has been run on Codewind before, we know exactly the project style (odo) and the component ID of the project.  During a bind of that application, we should be able to detect those so that the user does not have to provide the same information again.

To do that:
1. Change our existing delete operation without the -a flag so that the .odo folder will be left behind to preserve the component id info
2. On the project creation of odo project, we remove the .odo folder/config before calling create component (to allow user to give a different project name during the bind)
3. Add detection logic to odo extension to return the correct odo sytle and component id by looking for the odo config in the .odo folder if it exists.

**Comment by elsony** [comment]
@GeekArthur Can you take a look at this?

**Comment by GeekArthur** [comment]
Bind case main issue is here: https://github.com/eclipse/codewind/issues/450

**Comment by GeekArthur** [comment]
Currently we only have forward files syncing from workspace PVC to PFE PVC, thus the `.odo` folder that is created by PFE can't sync back to workspace, then if user deletes and binds the odo project again, the auto detection won't work since we don't have `.odo` on IDE side which uses workspace PVC.

Workaround:
Easy: Let user manually add `.odo` folder if user uses Codewind odo extension before for their projects
Hard: Codewind suppots backward files syncing from PFE PVC to workspace PVC

**Comment by GeekArthur** [comment]
I investigate more on this issue, the `Hard workaround` is not feasible because odo CLI generates `odo-file-index.json` which record file update metadata under `.odo` folder to imporve the odo build performance, that means `odo-file-index.json` can be updated with each file update, that can result in double build issue if we support backward files syncing from PFE PVC to workspace PVC.

I also try to **only** kubectl copy `.odo` folder to workspace PVC automatically during project create to ensure already binded odo project has the `.odo` folder, it works but downside is it increase ~ 10s for initial build.

**Comment by GeekArthur** [comment]
All auto detection is working (eg. if user project directory has .odo folder we can detect the project type as odo) now, only issue is if user removes the project there is no `.odo` folder in the project directory, in order to avoid double build and performance issue, we decide to leave as it is and use the current code with the current behavior.
