### ISSUE TITLE
Remote PFE: why do we create cluster role binding instead of role binding?

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1301]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Question synopsis:**

When I deploy a remote PFE, I'm curious why we create a `ClusterRoleBinding` instead of a `RoleBinding` in the namespace?

In the Che case we are using `RoleBinding`: https://github.com/eclipse/codewind-che-plugin/blob/master/setup/install_che/codewind-rolebinding.yaml

@markcor11 @johnmcollier

**Comment by maysunfaisal** [comment]
We should probably use `RoleBinding` for remote, dont see a reason why we should use `ClusterRoleBinding`

**Comment by markcor11** [comment]
We can change the bindings to `RoleBindings`.  We are installing `ClusterRoles` because we wanted to have just 1 set of deployed roles per Codewind version across the cluster,  but for the `ClusterRoleBindings` themselves they can be moved into the namespace since they are all labeled with the WorkspaceID anyway.

**Comment by johnmcollier** [comment]
We can have namespaced `RoleBindings` that are bound to cluster-scoped ClusterRoles (such as the Codewind role).

But it also may make sense to make the Codewind role per-workspace rather than cluster-wide for remote.

**Comment by makandre** [comment]
Verified now it's no longer creating `ClusterRoleBinding`, thanks
