### ISSUE TITLE
Rewrite project summary pages

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1362]
The help doesn't correspond with what you now see on the Project Summary page, for example, https://www.eclipse.org/codewind/mdt-vsc-commands-project.html.  
So rewrite these pages for VS Code and Eclipse, suggested headings are: 
- Project information
- Project Status
- Application information

etc. 

Consult the UI and adapt accordingly.

**Comment by james-wallis** [comment]
### VSCode
Once https://github.com/eclipse/codewind-vscode/pull/317 lands the project page in VSCode will be:
![image](https://user-images.githubusercontent.com/17385115/70135849-c3842b80-1682-11ea-99ac-1d57fd0348f1.png)

And the context menu will be:
![image](https://user-images.githubusercontent.com/17385115/70135868-cc74fd00-1682-11ea-9391-79c6fab2da84.png)

(Without the PR they are the same just without "auto inject metrics")

**Comment by micgibso** [comment]
On investigation, consider using content from 'projectview.md` currently in our docs source but not in our toc.

**Comment by james-wallis** [comment]
I've split the eclipse plugin implementation out to issue https://github.com/eclipse/codewind/issues/1406

**Comment by sishida** [comment]
Hi, @micgibso, With all the changes since this issue was opened in December, I'm not sure if this issue is still relevant.

I see that https://www.eclipse.org/codewind/vsc-commands-project.html and https://www.eclipse.org/codewind/projectview.html are no longer in our table of contents (https://github.com/eclipse/codewind-docs/edit/master/docs/_data/docstoc.yml).

Should we delete these files, or do we want to add them to the table of contents? Thanks!

**Comment by micgibso** [comment]
Hi @sishida, the two applicable topics now are:

- https://www.eclipse.org/codewind/project-actions.html
- https://www.eclipse.org/codewind/project-settings.html

...so perhaps just check the info above matches the text, for example, the `Open App` menu option is in our docs as `Open application`.  Suggest check with dev first to see what changes there have been to the context menus, and change to the text to the latest. 

The two files you mention can be deleted. Thx.
