### ISSUE TITLE
Cannot find the filewatcher log

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#1460]
Trying to debug a filewatcher issue and can't the log anywhere.  Following the instructions points me here `"/Users/tobes/Library/Application Support/Code/logs/20191209T180347/exthost14/IBM.codewind"` but there is only a codewind.log

I'm running vscode-ide by running `code codewind.workspace`

**Comment by tetchel** [comment]
the first line of the extension's output should be like:
`Codewind Tools created logs dir /Users/tim/Library/Application Support/Code/logs/20191210T004207/exthost7/IBM.codewind`

then lower down:
`codewind-filewatcher logging to /Users/tim/Library/Application Support/Code/logs/20191210T004207/exthost7/IBM.codewind with log level INFO on platform 'darwin'`

the paths should match

**Comment by jgwest** [comment]
I think what Toby may be seeing is multiple instance of Filewatcher's file logger stepping on each other's toes, due to us now having multiple connections open in VS Code (not sure why other people would not have hit it, but it would be a race condition when it did occur...). 

The TS Filewatcher is designed to delete any old filewatcher log files on IDE startup, but what they are actually doing is deleting any old filewatcher log files when the filewatcher constructor is instantiated (eg a new connection object is created).

**Comment by jgwest** [comment]
I've confirmed that the Java and Go filewatchers don't have this issue.

**Comment by jgwest** [comment]
As a workaround until this is available in VSCode, you can test on Codewind Eclipse, or ensure that only one Codewind connection exists in the Codewind view.

**Comment by malincoln** [comment]
@tobespc pls verify this is resolved. Thanks
