### ISSUE TITLE
Protected Template Repository can be deleted

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1461]
**Codewind version:** Master

**Description:**
PFE has template repositories that can be protected so they do not get deleted (such as the default ones), it appears that they can be deleted.

**Steps to reproduce:**
Run the DELETE template repo API on the default template URL.

**Comment by james-wallis** [comment]
I can pick this up tomorrow.

**Comment by rwalle61** [comment]
Fyi I introduced the `protected` property here https://github.com/eclipse/codewind/pull/382

I think I was aware at the time that `protected` only *indicates to the IDEs* which templates should not be deleted. Those templates can still be deleted via PFE's DELETE template repo API (as you've found). This was so that tests could delete the templates via PFE's DELETE API.

If we had an alternate way to delete 'protected' templates, I would probably make PFE unable to delete them too, and therefore agree that this is a bug.

However, I don't know of an alternate way to delete 'protected' templates, and am therefore happy to keep this property as a mere soft instruction to the IDEs not to call the DELETE API on these templates

@tobespc what do you think?

**Comment by stalleyj** [comment]
I've raised an enhancement to look at template sources because there are a few issues that need to be resolved/redesigned. We can consider this as part of that work so can we close this ?

**Comment by james-wallis** [comment]
@stalleyj sounds good to me.
