### ISSUE TITLE
[Hybrid] Reloading IDE workspace triggers full rebuild for all projects

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#1471]
**Codewind version:** 0.7.0
**OS:** Mac OS

**IDE extension version:** 0.7.0
**Kubernetes cluster:** OCP4

**Description:**
When I have multiple projects in a workspace and I right click on a project and select `Add Project to Workspace`, it adds the project to the workspace but also triggers a full rebuild of all of the projects.

Could be the same root issue as https://github.com/eclipse/codewind/issues/1293, since it seems that when VS Code is reloaded after adding the projects, there's a `cwctl sync` command for each project with `-t 0`.

**Steps to reproduce:**
1. Connect Codewind for VS Code to a remote install of Codewind
2. Create some projects and place them somewhere not in your current VS Code workspace
3. Wait for the projects to deploy
4. Right click on a project and select `Add Project to Workspace`. The editor will reload, the Codewind connection will refresh and all of the projects will be rebuilding.

**Logs:**
PFE: [pfe_logs.txt](https://github.com/eclipse/codewind/files/3947379/pfe_logs.txt)
Codewind.log: [codewind.log](https://github.com/eclipse/codewind/files/3947381/codewind.log)
Filewatcherd.log: [filewatcherd-1.log](https://github.com/eclipse/codewind/files/3947383/filewatcherd-1.log)

**Video:**
https://ibm.box.com/s/njyk9mio4c5dky33egqefzdei1mwp85p

**Comment by tetchel** [comment]
so does this mean restarting vs code also triggers a rebuild of all projects?

**Comment by johnmcollier** [comment]
Here's what I've been able to determine:
- Happens on both VS Code and Eclipse
- Simply reloading the IDE triggers this error as well
- It's the same issue as described in https://github.com/eclipse/codewind/issues/1293 and a proper fix for it will require changes in `cwctl` (as discussed on last week's tech topic)

**Comment by tobespc** [comment]
think this also affect #1073

**Comment by tobespc** [comment]
adding a lastSyncTime field to the project data returned for each project

**Comment by tobespc** [comment]
the watchlist api now returns a lastSyncTime value which should be used by the FWD to call cwctl rather than a value of `-t 0`  @jgwest

**Comment by jgwest** [comment]
## The projectCreationTime field should work for this purpose, rather than adding a new lastSyncTime field (though we could rename pCT)

Rather than using a new field `lastSyncTime`, I believe the existing `projectCreationTime` field can be used for this purpose. We can rename it to serve its new conceptual purpose (`lastSyncTime`), but I believe the underlying logic of this existing field, and how it is currently used by the filewatchers, will work for this use case as well.

#### The current logic of `projectCreationTime`, as implemented in the filewatchers right now, is:
- If a project has a 'projectCreationTime' field in EITHER the value returned by GET `/watchlist` or the value returned by the `/file-changes` endpoint, store it in memory (let's call it `project.pCT`)
- In any scenario where FWd would call `cwctl project sync`:
    - a) First look at `project.timestamp`, which is the value we would normally pass to `-t`; if the timestamp is non-zero, then just pass that to `cwctl` and return (eg never pass pCT if timestamp is non-zero)
      - timestamp is stored in FWd memory and not persisted to disk; so this use works fine for every subsequent `cwctl project sync` request, but not the first (which is the problem covered by this bug)
    - b) OTOH, if `project.timestamp` is zero, proceed to next line. 
- Timestamp is zero; so, if `project.pCT` is defined, then pass that to `cwctl project sync` as the `-t` param.
- In all the above cases, once `cwctl` has successfully run, the traditional `project.timestamp` field will be updated and therefore be non-zero, and will be used from then on.

And the new logic for the field would be the same logic you have now for the `lastSyncTime` field:
- On project creation, and any time a file sync occurs, updated the  `project.lastSyncTime` field in PFE
- NEW: Pass this value as the `projectCreationTime` field in the GET `/watchlist` and WebSocket `/file-changes` endpoint.
- NEW: `cwctl` to pass this value as part of upload end (but see below because this needs to be exactly correct)


AFAICT this logic sounds like exactly what you are looking for (and has the advantage of not requiring any late-breaking filewatcher changes). We would just treat this existing field as a `lastSyncTime` field (and rename it for the next release, to ensure the new field name is consistent with its purpose). Likewise it means we don't have two timestamp fields in the project JSON doing the same thing.


So, for this bug, the scenario will be:
1. File change occurs; sync time is updated to the timestamp of the most recent change.
2. IDE restart occurs.
3. Filewatcher calls GET `/watchlist` and is passed a new pCT.
4. Filewatcher passes that value to cwctl (instead of 0)
5. Cwctl walks the filesystem and sees no new changes since that time, and no build is triggered.

Batting cleanup:
- `lastSyncTime` will always be slightly > than FWd's timestamp, and that's OK, but ONLY as long as below is true.

## BUT, the lastSync value that CWCTL uploads to the upload complete endpoint is crucial, and very hard to get correct without either a race condition, (x)or an IDE rebuild on every restart 

In any case, whether we use `projectCreationTime` or `lastSyncTime` we will still hit the following issue:

This semi-persistent `lastSyncTime` should work, and not miss files, but ONLY if the `lastSyncTime` timestamp that is uploaded is exactly equal to the newest file, and also that our upload list contains all the changed files/folders exist that are older than this timestamp.
- Problem A) If changed files (files that should be synced) exist that are older than `lastSyncTime`, but are not in the upload list, they will be missed and thus never synced (race condition)
- Problem B) OTOH if the `lastSyncTime` timestamp is older than the newest file seen, then the IDE will build on every restart (because it will always do a file walk and see a file with a newer modification time)

The only way I can think of to solve both problems, and ensure we have an exactly correct upload list, and an exactly correct `lastSync` value, is to double walk the tree (a two-phase sync).

#### When `cwctl project sync` is called:
(For our purposes here, a 'changed file' is defined as a file/folder that was created/modified/deleted since the previous sync operation.)

Initial variables:
```
mostRecentModification := now
listOfChangedFiles := empty
```

Algorithm:

1) Phase 1: Walk the project tree once and look for changed files. 
	- If no changed files are found, skip to step 2
	- If changed files are found, set `mostRecentModification` to the most recent file modification timestamp seen (eg largest). Add all changed files seen to `listOfChangedFiles`

2) Phase 2: Walk the project tree again, looking for changed files older than `mostRecentModification`:
	- If a changed file is found that is older than `mostRecentModification` add it (if not already present) to `listOfChangedFiles` (it IS possible for this to happen, eg for a changed file to be missed,  in AT LEAST the error condition described below)

3) Finally, upload `listOfChangedFiles`, and set `lastSyncTime` to the `mostRecentModification` variable value


####  The specific error condition that requires the two-phase synchronize is this:

```
mostRecentTimestamp = now;
listOfChangedFiles := empty
```

1. Project directory walk starts. 
2. Project walk scans the `/project/one` directory and sees no new changes.
3. A change is made to `/project/one/file`, after the walk has already scanned the directory.
4. A change is made to `/project/two/file`, after step 3. Thus `two/file` has a larger modification date than `one/file`
5. Project walk scans `/project/two`, and notices the change to `two/file`, and sets `mostRecentTimestamp` to the modificationTime of `/project/two/file`. `/project/two/file` is added to `listOfChangedFiles`
6. `lastSyncTime` is set to `mostRecentTimestamp`

BUT, step 6 is incorrect, because `/project/one/file` has an older timestamp then `lastSyncTime`, and `/project/one/file` is not in `listOfChangedFiles`, and thus it will never be synced.

The two-phase synchronize algorithm avoids this, by first finding all the changed files, and THEN checking that there aren't any files missing that are older then the newest file modification date found.

How are we currently doing it in the codebase? AFAICT, it looks like the current `cwctl` code is using the `-timestamp` value from FWd for the `lastFileSync` timestamp it is uploading, which I believe will be susceptible to problem B ("always build on IDE restart").

**Comment by tobespc** [comment]
I've put a change in to pass projectCreationTime back in the watcthlist call
```
   ],
      "projectWatchStateId": "5dfd73a1571e8d244351fe654f70c1a7",
      "projectCreationTime": 1576234227163
    }
```
and updating this value on a sync.   For now, I've made the same change to 0.7.0 and master but we can look at improving master next year

**Comment by malincoln** [comment]
@johnmcollier can you test the 0.7.0 fix and confirm if problem is resolved?  Thanks

**Comment by johnmcollier** [comment]
I can no longer reproduce on 0.7.0

**Comment by johnmcollier** [comment]
Closing and verifying as it's fixed for me.

Thanks @tobespc!
