### ISSUE TITLE
[Remote/Kube] Can't have projects which share the same first three letters

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#1522]
**Codewind version:** Master
**OS:** Using VSCode extension on Mac OS connecting to a remote deployment in OpenShift.

**Description:**
If I have two projects which share the same first 3 characters in their name ("app" for example) I can only reach the first application using the ingress address.

I have created two applications using remote mode into an open shift cluster:
1. `appsody-node-express-mongrel`
2. `appsody-scaffold-mongrel`
They both build and launch fine.
The Ingress url given to me for each is:
1. `http://cw-app-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io/`
2. `http://cw-app-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io/`

So they're exactly the same and when I go to the URL I can only get to the first project.
I am not sure on the details but it looks like we're using `cw-app` as the only identifier for the ingress.

*This might also be present in a Che environment but I have not tested for that.*

My OpenShift dashboard shows the second project's URL as invalid as the route it is trying to use already exists (the black invalid url text):
![image](https://user-images.githubusercontent.com/17385115/70805648-56267800-1db1-11ea-9d6f-0ffd7ef24bcc.png)

**Steps to reproduce:**
1. Connect to remote Codewind
2. Create two projects with the same first 3 characters in their name (I did `appsody-*`)
    * I created Appsody and Node.js
3. Let them build and start
4. Check their given URLs and they will be the same
5. Check the OpenShift dashboard to see the behaviour shown in the screenshot above.

**Workaround:** 

If the project has an exposed port AND its a NodePort you can take any URL for that OpenShift cluster and add its port onto the end.
So: 
  * `http://cw-app-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io: 32688` got me to my first Node.js project
  * `http://cw-app-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io: 31802` got me to my second Node.js project

**Comment by johnmcollier** [comment]
@james-wallis I know why this is happening, it's cause we're trimming the ingress hostname we create in a bad way.

On OKD 3.x clusters, it requires that the host name for the ingress/route be < 63 characters. The problem here is that we have no way to know what the maximum allowed ingress host name length is, as it heavily varies by Kube distribution (even OCP 4.x doesn't have this issue). So what we do is:
- If the ingress domain we're given is < 63, we trim the pieces we append to the ingress so that the ingress for the project is also < 63. 
- If the ingress domain we're given is > 63, we know that requirement isn't in place, so we don't trim.

So your ingress domain is `jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`, which is 56 characters, which only gives room for 6 more characters (the `cw-app-`, specifically). Which explains the collision with projects with similar names. If `jamesw0001` was shortened, you might get more room (I presume this is the namespace you installed in?).

The problem is that our current approach doesn't guarantee enough uniqueness if the ingress domain is close enough to the 63 character limit.

I'm wondering what we can do here? One solution may be to generate some random characters to add on to the ingress hostname we create? E.g.:
- `cwxdnj-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`
- `cwxdnj-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`

**Comment by johnmcollier** [comment]
@james-wallis I know why this is happening, it's cause we're trimming the ingress hostname we create in a bad way.

On OKD 3.x clusters, it requires that the host name for the ingress/route be < 63 characters. The problem here is that we have no way to know what the maximum allowed ingress host name length is, as it heavily varies by Kube distribution (even OCP 4.x doesn't have this issue). So what we do is:
- If the ingress domain we're given is < 63, we trim the pieces we append to the ingress so that the ingress for the project is also < 63. 
- If the ingress domain we're given is > 63, we know that requirement isn't in place, so we don't trim.

So your ingress domain is `jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`, which is 56 characters, which only gives room for 6 more characters (the `cw-app-`, specifically). Which explains the collision with projects with similar names. If `jamesw0001` was shortened, you might get more room (I presume this is the namespace you installed in?).

The problem is that our current approach doesn't guarantee enough uniqueness if the ingress domain is close enough to the 63 character limit.

I'm wondering what we can do here? One solution may be to generate some random characters to add on to the ingress hostname we create? E.g.:
- `cwxdnj-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`
- `cwxdnj-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io`

**Comment by johnmcollier** [comment]
Test

**Comment by jgwest** [comment]
@james-wallis Nice catch finding this one :+1:

**Comment by james-wallis** [comment]
@markcor11 mentioned that he'd already fixed an issue like the one @johnmcollier described in codewind-installer when deploying keycloak. Best to talk to him on Monday to get the details but I we were able to make it longer than you've said above. 
But, like you say, his fix might not work on OKD 3.x clusters. 


Sidenote - On OpenShift I've been able to change: 
```
http://cw-app-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io/
```
to 
```
http://123456789012345678901234567890123456789012345678901234567890.12cb28b0-1dbd-11ea-aff5-jamesw0001.apps.exact-mongrel-icp-mst.9.20.195.90.nip.io/
```
 and it still works as it  has less than 63 characters in between every `.`. (Again I realise this isn't on OKD 3.0)

**Comment by johnmcollier** [comment]
@james-wallis Huh, that's interesting. I'll definitely reach out to Mark on Monday and give that a try.

**Comment by johnmcollier** [comment]
Moving to in progress

**Comment by rajivnathan** [comment]
@james-wallis can you please verify?

**Comment by malincoln** [comment]
@james-wallis pls verify and close.  Thanks

**Comment by james-wallis** [comment]
Have tested this and it works.
