### ISSUE TITLE
[odo] Odo functional test failing on ignorePaths

### ISSUE THREAD

**Issue by maysunfaisal** [eclipse/codewind#1527]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The odo projects fail on ignorePath functional test
[kube-functional-test.log](https://github.com/eclipse/codewind/files/3961913/kube-functional-test.log)

/area iterative-dev
/kind test

**Comment by GeekArthur** [comment]
It fails here: https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectsController.ts#L995, which returns default status error code 500 instead of 202 when calling `projectSpecifications.projectSpecificationHandler`, since the function is generic function, so if it’s a real issue the problem shouldn’t be odo project specific or any project type specific. I am not sure how our tests verify that or what’s the testing scenarios, but someone who creates the test case can manually try configure odo project to see if it works

**Comment by GeekArthur** [comment]
But this one might be related with the syncing issue I find recently `[13/12/19 17:26:09 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted files from project: odo-nodejs, ID: 43c61e60-1dcd-11ea-9690-81a499d046aa - .odo/config.yaml, .odo/odo-file-index.json`, Portal removes all files under `.odo` folder so that all updates (including update `.cw-settings` file) won't work as files under `.odo` are gone

**Comment by makandre** [comment]
@GeekArthur the remove deleted files problem you describe, could the core issue be the same as in #1472?

**Comment by GeekArthur** [comment]
@makandre Seems like they are not the same, my problem is only files missing on PFE side, there is not issue for remote connection.

**Comment by ssh24** [comment]
@maysunfaisal I think the ODO tests have been more stable on the ignoredPaths lately? Could you please verify?
