### ISSUE TITLE
PFE disconnected after a single change to a spring project

### ISSUE THREAD

**Issue by yangcao77** [eclipse/codewind#1574]
**Codewind version:** master
**OS:** MacOS

**Che version:**
**IDE extension version:** VSCode master
**IDE version:**
**Kubernetes cluster:**

**Description:**
This is an intermittent issue. 
I only have 1 spring project in my local workspace.
PFE and docker hangs after a change to the spring project. I've noticed that portal is trying to log all deleted files, and my pfe hangs after that.

I need to restart my docker and restart codewind to continue my work on the project. 

this is the PFE log: 
[pfelog.txt](https://github.com/eclipse/codewind/files/3975163/pfelog.txt)

**Steps to reproduce:**
1. create a spring project
2. modify a file and save

**Workaround:**

**Comment by elsony** [comment]
Based on the described scenario, I wonder if it is possible that the portal code is doing the sync on the main thread so it will block any incoming connection, e.g. ping from the IDE, if it is in the middle of a sync operation.

**Comment by elsony** [comment]
Although we kind of mentioned this problem in https://github.com/eclipse/codewind/issues/1383, that item is currently classified as having a lot of project building at the same time and hold up the CPU. However, this particular scenario is just one single project on local and I think it is more serve than #1383.

**Comment by elsony** [comment]
@johnmcollier It sounds like you are seeing similar problem when running on Che (https://github.com/eclipse/codewind/issues/1383#issuecomment-562727397). Can you confirm if you are still seeing the problem on Che scenario?

**Comment by jopit** [comment]
The log Stephanie attached shows PFE is deleting the maven cache folder (.m2) .  Seems like another instance of the kind of problem reported in #1472 and #1546 

Even if we change to deleting folders instead of individual files, deleting the maven cache is less than ideal since it will likely dramatically increase build times -- maven will have to download all dependencies again.

**Comment by tetchel** [comment]
also similar https://github.com/eclipse/codewind/issues/1570

**Comment by johnmcollier** [comment]
@elsony I can still reproduce on Che

**Comment by jopit** [comment]
That log snippet from John's comment in https://github.com/eclipse/codewind/issues/1383#issuecomment-562727397 also shows PFE is deleting the maven cache.

**Comment by elsony** [comment]
@tobespc One way to fix it is to add .m2 to the skip list for deletion similar to what we did for the similar odo and Appsody in the past.  Having said that, this is the third variant of stopship problems caused by the new sync logic introduced on 0.7.0 is trying to delete files that it doesn't know about (as mentioned on #1533).  I am not sure if we can safely say that we have have found all cases that are broken by that yet.  I wonder if we should considering to roll back that change for 0.7.0 and design carefully on the resource deletion before introducing that support back to avoid similar problem.

**Comment by tobespc** [comment]
The change we want to put in will not delete files individually but rather delete files by directory.  However, build files should not be being deleted .  Files can exist in 3 places now.   In the users workspace, in the pfe container and in the build/run container.  

Files likes .m2 cache should only exist in the build/run container ?

We do deletion by comparing the list of files in the users workspace against the list of files in the pfe container.  If there are any extra files in pfe then its assumed they have been deleted and should be removed.

**Comment by tobespc** [comment]
This is raised on master ?   not 0.7.0

**Comment by tobespc** [comment]
ok, so I can see that in the pfe volume, we have the .m2 cache as well as in the build container, why ?   The codewind-workspace/project should be a mirror of that is on the user workspace, should never contain build artifacts

**Comment by tobespc** [comment]
I've made a change to the spring-container.sh script to match liberty.  That is, rather than unzip the m2cache, leave it as a zip file and let it get extracted by the build.sh file

**Comment by tobespc** [comment]
I've had some thoughts around improving the deletion logic to prevent this happening in future, will get a change in for 0.8.0

**Comment by makandre** [comment]
@tobespc re:

> The codewind-workspace/project should be a mirror of that is on the user workspace, should never contain build artifacts.

Well in the case of appsody, the appsody container still mounts pfe's project dir, hence build artifacts do appear in the dir

There's also another case of build artifacts getting generated into the project dir:  when appsody runs in pfe in k8s, it will generate `app-deploy.yaml` etc. into the project dir.  Tho, it's less of an issue if those are deleted because appsody will just generate them again when it re-runs (but having them around is useful for debugging)

**Comment by tobespc** [comment]
@makandre yeah, thats what I'm finding, the change I'm making will preserve all that stuff

**Comment by tobespc** [comment]
Raised https://github.com/eclipse/codewind/issues/1589 to cover the enhancement to delete

**Comment by elsony** [comment]
@makandre Does it mean that there are still some potential problems on Appsody case that has not been addressed yet or is that already fixed as part of the earlier fixes?

**Comment by makandre** [comment]
@elsony good question.  I have to say yes: because any runtime artifact will get removed and we don't know how that affects the running app.  We are catching the `node_modules` scenario now, but because we can't know for sure what appsody stacks will be used with Codewind, we won't catch all the scenarios.  That's why I've been advocating for a way that can distinguish
between files sync to PFE and files that are generated at build/run time.  See https://github.com/eclipse/codewind/issues/1472#issuecomment-566190100

**Comment by elsony** [comment]
@tobespc Although you have raised #1589 to fix it post 0.7.0, as mentioned in the earlier comments, I wonder if we should really consider to remove that file deletion logic for 0.7.0 since and reintroduce the proper deletion logic when we have one.  Leaving that logic in 0.7.0 can potentially causes instability to our 0.7.0 driver:
1. We don't know if we have caught all cases that the deletion will cause problems yet. The problem is intermittent in some cases so it is difficult to tell whether there are other failure cases that we haven't seen yet.
2. Whenever there is a problem, the problem is serve and it may even potentially hang docker in some cases.

**Comment by GeekArthur** [comment]
I think the key point is we need to have a design to identify the `origin of triggering the sync`. 

Currently we only support forwards sync which sync from user workspace to PFE, so the origin of triggering the sync should only be the user workspace and only operations (create, update, delete files) in user workspace can trigger the sync. However, the current behavior is that if we generate build artifacts (some we know like `.odo` and Appsody `node_modules` and some we don't know and may have potential issues like Andrew said) on PFE container, we still trigger the sync due to sync thinks user delete the files that generated on PFE container but actually user doesn't. This is for sync forces to delete files that generated on PFE container, I am not sure if we have the issue of sync forces to create files that deleted on PFE container since that may potentially cause performance issue as well.

If we have a design to identify the `origin of triggering the sync`, we may avoid all the issues since all operations from origin of PFE container can be ignored and only origin of user workspace can trigger the sync.

**Comment by tobespc** [comment]
So I have a design worked out that will solve this going forwards and prevent deletion of anything that is not src code. I can work on it for delivery for 0.7.0 of you really want it for that but it's not a tiny change

**Comment by tobespc** [comment]
For info though, the deletion logic is the same as it was in 0.6.0 and 0.6.1

**Comment by makandre** [comment]
I don't think a sync is triggered when files are created in PFE though.  The sync (and deletion of files) is triggered on the **next** modification of files in the user's local project.

**Comment by tobespc** [comment]
Ah yes, so this issue was masked behind the original build

**Comment by tobespc** [comment]
Now you get it on the first sync

**Comment by tobespc** [comment]
It's not sync that is the issue. It's when we do sync and the logic in pfe compares what files are in the users workspace against what is in the volume. Any differences are deleted

**Comment by tobespc** [comment]
I'll be home in about an hour if you want me to work on a change. I don't this we should revert anything as that would not give us any file deletion

**Comment by elsony** [comment]
Regarding to the change in deletion logic from 0.6.1, Jingfu has pointed out earlier that there were some changes on the deletion logic (https://github.com/eclipse/codewind/pull/1310/files#diff-b73b1946195409164e2ccc8a3b7fe79cR216) that was causing the odo case to fail on 0.7.0 which was working on 0.6.0 and 0.6.1 before.

**Comment by yangcao77** [comment]
Verified it's been fixed on local.

**Comment by johnmcollier** [comment]
I can still reproduce on master with Che

**Comment by elsony** [comment]
Putting this back to in progress since the problem still happens on Che (local works fine).

**Comment by johnmcollier** [comment]
Logs from PFE indicate that the .m2 folder is **still** getting deleted:
```
[18/12/19 21:54:41 /portal/routes/projects/remoteBind.route.js] [INFO] Removing locally deleted files from project: springtest, ID: 80e36460-21d8-11ea-8cf6-9550cebf4478 - .m2/repository/aopalliance/aopalliance/1.0/_remote.repositories, .m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar, .m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar.sha1, .m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.pom, .m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.pom.sha1, .m2/repository/asm/asm/3.2/_remote.repositories, .m2/repository/asm/asm/3.2/asm-3.2.pom, .m2/repository/asm/asm/3.2/asm-3.2.pom.sha1, .m2/repository/asm/asm/3.3.1/_remote.repositories, .m2/repository/asm/asm/3.3.1/asm-3.3.1.jar, .m2/repository/asm/asm/3.3.1/asm-3.3.1.jar.sha1, .m2/repository/asm/asm/3.3.1/asm-3.3.1.pom, .m2/repository/asm/asm/3.3.1/asm-3.3.1.pom.sha1, .m2/repository/asm/asm-analysis/3.2/_remote.repositories, .m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.jar, .m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.jar.sha1, .m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.pom, .m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.pom.sha1, .m2/repository/asm/asm-commons/3.2/_remote.repositories, .m2/repository/asm/asm-commons/3.2/asm-commons-3.2.pom, .m2/repository/asm/asm-commons/3.2/asm-commons-3.2.pom.sha1, .m2/repositor
```

Also weirdly, once PFE "disconnects" from the editor (note it doesn't crash), the following is spammed in the logs a **lot**
```
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
[18/12/19 21:55:17 sharedFunctions.js] [WARN] spawn /bin/sh EAGAIN
```

**Comment by johnmcollier** [comment]
I know why it’s happening. It’s because Spring projects on Kube still share a volume mount with Codewind. So the fix here: https://github.com/eclipse/codewind/pull/1592/files#diff-a3b69d6f69e6c6c34ddf2550e3fde307 won't work since it's still creating the .m2 cache on the volume mount that PFE has.

**Comment by rajivnathan** [comment]
Verified https://github.com/eclipse/codewind/pull/1594 fixes the issue. @jagraj to verify with the public 0.7.0 image once the build completes

**Comment by jagraj** [comment]
Verified on 0.7.0 as well. Closing this one. Thanks for the fix.

**Comment by johnmcollier** [comment]
Fixed in master too.
