### ISSUE TITLE
In 0.7.0 release, appmetrics inject can cause app crash for Express Node.js

### ISSUE THREAD

**Issue by NikCanvin** [eclipse/codewind#1602]
**Codewind version:** 0.7.0
**OS:** Mac

**Che version:** - 
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Note:**
This issue only applies to Node.js Apps, as everything worked OK on 'Websphere Liberty Java Microprofile'.

**Description:**
I was trying to understand/test the new metrics inject feature in 0.7.0 release, when toggling the inject feature and trying to do perf runs, the app consistently crashed - I slacked with Jag, who was able to reproduce.

**Steps to reproduce:**
1.create Express Node.js app from default template
2.toggle 'inject appmetrics' ON
3.do a perf run
THE APP CRASHES

**Workaround:** 
-

**Comment by tobespc** [comment]
this also affects master branch

**Comment by rwalle61** [comment]
Okay, I'm trying to recreate. It'd be great if you could post:
1. What's at /metrics
2. what does the package json of the project look like, in the project's docker container?
3. what does the package json of the project look like, in the project dir of the PFE docker container? (`.codewind-workspace`)

**Comment by tobespc** [comment]
nothing on /metrics except a nice 404 not found

package.json does not container codewind-metrics

**Comment by rwalle61** [comment]
neither package.json, not even in the PFE container? If so that narrows the problem very specifically

**Comment by rwalle61** [comment]
if metrics injection fails there should be an error in the PFE logs, probably `Injection of metrics collector is not supported for projects of type 'nodejs'`. But if there is a `debug` level log saying `Successfully injected metrics collector into nodejs project` then metrics injection succeeded and the bug is afterwards.

It'd be good to know, if you set logging level to `trace`, whether we get this log message: `Injecting metrics collector into project's package.json, which is now <newContentsOfPackageJson>`

**Comment by tobespc** [comment]
```  "dependencies": {
    "appmetrics-dash": "^5.2.0",
    "body-parser": "^1.18.3",
    "express": "^4.16.4",
    "log4js": "^4.0.2",
    "appmetrics-codewind": "^0.1.0"
  },```

**Comment by tobespc** [comment]
the injection part has worked fine

**Comment by rwalle61** [comment]
so the package json of the project in PFE has `appmetrics-codewind`, but the package json in project's docker container doesn't have it... 

That happened a while ago when there was a bug where I think we built the project before injecting the package json. I thought we fixed that, but a similar thing may be happening now

I'm still trying to recreate

**Comment by rwalle61** [comment]
**Diagnosis**
Okay I think I've recreated this bug. An app that `attach` `appmetrics-dash` after `attach`ing `appmetrics-codewind` crashes when any endpoints shared by the 2 packages are hit, including the endpoints that the performance test hits, and `/appmetrics-dash`. 

In our Nodejs templates, the 1st line in `server.js` is `require('appmetrics-dash').attach()`. And when we inject metrics, the app is started with `node -r appmetrics-codewind/attach ...`. Therefore it will `attach` `appmetrics-codewind` then `appmetrics-dash`. Hitting `/metrics` is fine, because that endpoint belong to `appmetrics-codewind` only. But the app crashes when we hit `/appmetrics-dash` or launch a performance test.

**Solutions**
1. (partial solution) remove `appmetrics-dash` from the templates, so that users of nodejs templates don't automatically hit this problem
2. don't inject into nodejs projects that already have `appmetrics-dash`. We can do a check, and hide the `inject metrics` button on these nodejs projects. We can explain that we don't offer to inject metrics if the user is already using our metrics package (`appmetrics-dash`). In that case, the only benefit of injecting `appmetrics-codewind` is to give them a `/metrics` endpoint of prometheus metrics that they can consume however they want (e.g. graphing on grafana)
3. or, if a nodejs project already has `appmetrics-dash`, inject only the `/metrics` endpoint, without injecting what's already in `appmetrics-dash` (e.g. the endpoints that the performance test will hit)

**Comment by rwalle61** [comment]
I believe the errors were caused by `appmetrics-codewind` [patching the same listeners](https://github.com/RuntimeTools/appmetrics-codewind/pull/3/files#diff-a427f349a78624131dbcf9702a67fe58L103-L107) that `appmetrics-dash` [patches afterwards](https://github.com/RuntimeTools/appmetrics-dash/blob/master/lib/appmetrics-dash.js#L195). When the listeners hear a request, they both respond, throwing these errors (and sometimes crashing the app):
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at expressInit (/app/node_modules/express/lib/middleware/init.js:30:42)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at query (/app/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
Error: Can't render headers after they are sent to the client
    at ServerResponse.writeHead (_http_server.js:226:15)
    at XHR.Polling.onPollRequest (/app/node_modules/engine.io/lib/transports/polling.js:85:9)
    at XHR.Polling.onRequest (/app/node_modules/engine.io/lib/transports/polling.js:65:10)
    at XHR.onRequest (/app/node_modules/engine.io/lib/transports/polling-xhr.js:46:33)
    at /app/node_modules/engine.io/lib/server.js:232:46
    at Server.verify (/app/node_modules/engine.io/lib/server.js:173:3)
    at Server.handleRequest (/app/node_modules/engine.io/lib/server.js:224:8)
    at Server.<anonymous> (/app/node_modules/engine.io/lib/server.js:469:14)
    at Server.<anonymous> (/app/node_modules/socket.io/lib/index.js:343:16)
    at /app/node_modules/appmetrics-codewind/lib/appmetrics-codewind.js:148:16
```
