### ISSUE TITLE
Support adding project quickly from Git repo

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#163]
- [ ] Codewind should be able to import a project from github directly into VSCode/Eclipse

@tetchel @sishida @thisguy-1

**Comment by eharris369** [comment]
Could we allow the user to specify the workspace on install or start of codewind? That way if they have a "git" folder where they check out all of their projects, it could be used as the codewind workspace (known issues with windows if it is in their Azure user dir).  That way they could still check in changes they make through the IDEs.

**Comment by sishida** [comment]
If we need error notification rewrites, I can help with those.

**Comment by thisguy-1** [comment]
> Could we allow the user to specify the workspace on install or start of codewind? That way if they have a "git" folder where they check out all of their projects, it could be used as the codewind workspace (known issues with windows if it is in their Azure user dir). That way they could still check in changes they make through the IDEs.

Do you mean like a "set your workspace" type deal?

**Comment by tetchel** [comment]
> Do you mean like a "set your workspace" type deal?

putting aside the design, is this technically possible with the current architecture? if not, I don't think we will put in the work because the workspace is going away someday anyway.

**Comment by tetchel** [comment]
now that there's no workspace, the second and third items don't apply. but the first one still could

**Comment by thisguy-1** [comment]
Is this technically feasible? What do you think the flow would be like. I'm trying to think if its worth it when a user could simply download the project from github and then click on add existing within vscode. Is the addition of this feature easy to do and does it benefit a developer enough?

**Comment by thisguy-1** [comment]
Also, is it worth it to a developer, for codewind to be able to move there project's file to another directory during the addition process? Say they had the project existing within a different directory, and and now the wanted to either copy it/move it to another, or in the case of downloading directly from github within codewind, being able to specify where.

**Comment by thisguy-1** [comment]
Should we still be considering this? This would apply to add existing project, correct?

**Comment by tetchel** [comment]
I do think this is still worth doing, we should discuss at our next meeting

**Comment by tetchel** [comment]
I checked out how a user would do this using the current tools, and I think this is probably suitable to be quickly documented because it's only two steps - `git clone` the normal way (either through the command line, or through the IDE) and then adding it to Codewind. So, I think this should be a docs issue.

You can see a screen recording below of how this looks in VS Code. Note that:
- Instead of using the `Git: Clone` command you can just run `git clone` on the command line.
  - I know Eclipse and IntellIJ have git clone features too but obviously they would look different.
- Adding the cloned folder to the workspace is optional.

[clone-add.zip](https://github.com/eclipse/codewind/files/4344403/clone-add.zip)
![clone-and-add](https://user-images.githubusercontent.com/8888438/76876292-1ce62400-6848-11ea-9105-de1ebb9cb0c8.gif)

so, I think we should just document this as part of our getting started and 'adding projects' documentation.
@sishida

**Comment by sishida** [comment]
- Document Codewind command.
- Other IDE-specific instruction can be covered by IDE documentation.

**Comment by sishida** [comment]
PR has been merged. Closing this issue. :)
