### ISSUE TITLE
Reduce steps from Codewind website to install

### ISSUE THREAD

**Issue by thisguy-1** [eclipse/codewind#165]
- The "Install Codewind Link" should just take them to VS Code, not to the online market place.
@micgibso
@thisguy-1
@sishida 
@tetchel 

![Codewind Install Instructions](https://user-images.githubusercontent.com/52169824/62888731-e8d4de80-bd0d-11e9-9b8c-693b93b1d62c.png)

![Artboard](https://user-images.githubusercontent.com/52169824/62810280-64931900-bacb-11e9-8400-fe4db725a52a.jpg)

**Comment by thisguy-1** [comment]
The link should also be renamed.

**Comment by tetchel** [comment]
I believe this could be done by replacing the current marketplace link `https://marketplace.visualstudio.com/items?itemName=IBM.codewind` with `vscode:extension/IBM.codewind`. It works for me, but I would be curious to see if that works on a machine which does *not* have VS Code installed.

**Comment by thisguy-1** [comment]
I imagine it would be the same as if you were starting at the marketplace. But yes, I have the same question.

**Comment by tetchel** [comment]
Also, we should still link to the marketplace entry separately.

**Comment by micgibso** [comment]
See also https://github.com/eclipse/codewind/issues/173

**Comment by sishida** [comment]
@micgibso, I checked our list of files (https://github.com/eclipse/codewind-docs/tree/master/docs/_documentations) as well as our table of contents file (https://github.com/eclipse/codewind-docs/blob/master/docs/_data/docstoc.yml), and it appears that installlocally.md is no longer in use.

Is this file still in use but renamed, or can we go ahead and close this issue because the problematic link is no longer around?

**Comment by tetchel** [comment]
we should still make this change in the new page https://www.eclipse.org/codewind/mdt-vsc-getting-started.html we can put the link here 
![image](https://user-images.githubusercontent.com/8888438/69282246-d9401e00-0bb7-11ea-8b91-91db521974f3.png)

**Comment by micgibso** [comment]
@sishida I'll take a look please.

**Comment by micgibso** [comment]
@tetchel Change made on PR https://github.com/eclipse/codewind/issues/165, please review.  

Have changed the sentence to your suggested link above (`vscode:extension/IBM.codewind`), tested it,  and it works for me too. 

Re  'I would be curious to see if that works on a machine which does not have VS Code installed.' Step 1 above says `Install VS Code 1.28 or later` so in theory users shouldn't ever encounter this scenario, but it would be interesting to see what happens if they omit step 1.

**Comment by micgibso** [comment]
Change made, closing.
