### ISSUE TITLE
Invalid characters for Spring Boot and Microprofile template in New Codewind Wizard on Windows Eclipse

### ISSUE THREAD

**Issue by jgwest** [eclipse/codewind#1765]
**Codewind version:** Latest
**OS:** Windows

**Description:**

In Eclipse, but ONLY on Windows, I see the following under the New Codewind Project wizard.

![image](https://user-images.githubusercontent.com/7594762/72439239-89737280-3774-11ea-9684-15e59cb3c75c.png)

The extra symbols after Spring Boot and Microprofile are a trademark symbol on other platforms, so presumably on Windows these are being intrepreted as an incorrect character encoding.

**Comment by tobespc** [comment]
need to check our labels in the templates don't have any funny characters in

**Comment by mattcolegate** [comment]
This is indeed a string encoding issue - `Â` is what you get when encoding a `&nbsp;` (non-breaking space) character from UTF-8 to ASCII (ISO-8859-1). The output from the cwctl call to list templates is returned as UTF-8 strings, but turned into Strings by the plugin with default encoding, which on Windows is ISO-8859-1.
I've made a change to specify UTF-8 encoding in this PR: https://github.com/eclipse/codewind-eclipse/pull/542 and it has fixed the observed problem - however because the area I've changed is fundamental to the plugin (getting executed in every single call to cwctl, including project creation, binding, start, stop, install, uninstall, upgrade, validate and authorisation tokens) this will need extensive testing to make sure everything still works before being pulled in. @eharris369 is that something you can handle?

**Comment by mattcolegate** [comment]
No more work to do on this issue until @eharris369 has approved https://github.com/eclipse/codewind-eclipse/pull/542
