### ISSUE TITLE
SVT: [Che] Application stopped unexpectedly 

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1769]
**Codewind version:** 0.8.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.5.1
**Kubernetes cluster:** OKD/Openshift 

**Description:** An error message "Application stopped unexpectedly" appears in Eclipse Che, but then the application starts and works as expected. I have seen this error with multiple projects.

<img width="1676" alt="Screen Shot 2020-01-15 at 1 25 09 PM" src="https://user-images.githubusercontent.com/49531960/72463511-66ab8300-37a1-11ea-8d4e-c6cf330485e2.png">

<img width="1672" alt="Screen Shot 2020-01-15 at 1 25 51 PM" src="https://user-images.githubusercontent.com/49531960/72462772-dfa9db00-379f-11ea-9bbb-c376c775d808.png">

**Logs:**
[codewind-workspace5g2fohc3kkmqj4kj-7b6448cbd4-wzkcw.txt](https://github.com/eclipse/codewind/files/4066989/codewind-workspace5g2fohc3kkmqj4kj-7b6448cbd4-wzkcw.txt)
[cw-appsody-node-express-simple.txt](https://github.com/eclipse/codewind/files/4066990/cw-appsody-node-express-simple.txt)
[cw-appsody-loopback4.txt](https://github.com/eclipse/codewind/files/4066991/cw-appsody-loopback4.txt)
[codewind.txt](https://github.com/eclipse/codewind/files/4066992/codewind.txt)

@jagraj

**Comment by johnmcollier** [comment]
@makandre FYI ^

@sujeilyfonseca Do you only see this error with appsody projects?

**Comment by sujeilyfonseca** [comment]
/priority stopship
Marking this as "stopship" since it is a regression.

@johnmcollier - So far, I've only seen the error with Appsody projects.

**Comment by johnmcollier** [comment]
Removing the iterative-dev label I added as this seems isolated to appsody for the timebeing. Feel free to add back if that's not the case

**Comment by malincoln** [comment]
@makandre can you review?

**Comment by makandre** [comment]
Suspect it is related to fix for https://github.com/eclipse/codewind/issues/1297

Likely the appsody app state going to `stopped` had always existed (perhaps because the container/pod is not active yet when Turbine pings it), but now with #1297, we are throwing an error status for that condition and hence we see it back in the editor

**Comment by tetchel** [comment]
agree with andrew that likely the status probably always flip-flopped like this - the difference is that now we are showing a notification for it.

**Comment by tetchel** [comment]
This is closely related to https://github.com/eclipse/codewind/issues/1732

It may be worth not showing the notifications (maybe just for appsody projects?) until they are a bit more stable.

**Comment by yangcao77** [comment]
Nope. It's not because of the Turbine ping timeout.
Actually the message `Application stopped unexpectedly` would only be sent to ui if we found the container state/pod state is unexpected during starting state. 

For che case, we checks if the pod is `running`, or if it pod is `waiting` & reason is `ContainerCreating`. Otherwise we think the pod is stopped.

**Comment by yangcao77** [comment]
Turbine use the release label `release=containerName` to look for the project pod. And if the pod status is `pending` or `running`. It will iterating through `pod.status.containerStatuses` to check the container statuses.

**Comment by makandre** [comment]
Regarding why appsody project goes to `stopped` state, here are a couple things to consider:

- when appsody project starts up, we report the app status as `starting` pretty much [right away](https://github.com/eclipse/codewind-appsody-extension/blob/master/entrypoint.sh#L124); that's because appsody projects do not need to go through a build phase to build the docker image (this behaviour has been unchanged for a number of releases)

- on Che, the appsody pod has an `initContainer` that it runs before the main application container.

- when Turbine queries for the pod and checks the container status then, is it possible that it sees the `initContainer`'s status as `terminated` and thinks the application is stopped?

**Comment by makandre** [comment]
I managed to capture this status:

```
"containerStatuses": [
                    {
                        "image": "docker.io/appsody/nodejs-loopback:0.2",
                        "imageID": "",
                        "lastState": {},
                        "name": "cw-aploopback01-f880fa40-37d7-11ea-b6c3",
                        "ready": false,
                        "restartCount": 0,
                        "state": {
                            "waiting": {
                                "reason": "PodInitializing"
                            }
                        }
                    }
                ],
```

The state is `waiting` and the reason is `PodInitializing`;  it looks like we are not taking that reason into account, hence the application is assumed to be `stopped`

https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/utils/kubeutil.ts#L297

**Comment by makandre** [comment]
PRs for 0.8.0 and master are up for review

**Comment by malincoln** [comment]
@sujeilyfonseca the fix has been merged for 0.8.0.  Can you verify?

**Comment by sujeilyfonseca** [comment]
Sure, @malincoln. I will proceed to verify the issue.

**Comment by sujeilyfonseca** [comment]
I've verified this issue with the latest Codewind 0.8.0, and I no longer see the problem:

![Screen Shot 2020-01-16 at 11 33 02 AM](https://user-images.githubusercontent.com/49531960/72543592-fb6eb900-3853-11ea-846c-15a819e9a2c2.png)

**Comment by malincoln** [comment]
@sujeilyfonseca thanks for verifying the 0.8.0 fix resolves your issue.  I'm reopening and moving back to In progress until the fix is merged into master.  Once that's done, it can be closed.

**Comment by malincoln** [comment]
closing now that PR to master has been merged.
