### ISSUE TITLE
Remove project fails if recreate the remote connection (using cwctl project remove)

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1782]
If I have a remote connection with some projects created on it and then I delete that connection and re-create it later I cannot remove the projects.  The error message is:

Connection K5H2EUL7 not found

This is the old connection id from when I first created the connection.  The new connection id is K5H2JM8P.  The cwctl project remove command does not take a connection id, only a project id.

Updating the project does not work either - if I change a file, the project does not automatically rebuild.  I can rebuild it manually but it does not pick up the change (let me know if this needs a separate issue).

Otherwise the project behaves normally.

**Comment by tobespc** [comment]
ok thanks, will pick shortly

**Comment by tobespc** [comment]
After discussion with @stalleyj and the uninstall story #1672 , when we remove a connection we will want to clean up any remote projects as well so this issue will be resolved as part of that

**Comment by tobespc** [comment]
Remote connection can be in three states - 

1) open and being using as normal in IDE (projects can exist remotely)
2) connection can be disconnected in IDE (projects can exist remotely)
3) connection is to be deleted from IDE (projects should be deleted remotely)

**Comment by james-wallis** [comment]
This was discussed in mid-sprint meeting today and we decided on two options:
1. To resolve this issue, force the update of all the `connection.json`s for every project ID retrieved from the initial `GET` on `/api/v1/projects` so that they will be updated with the new connection ID (will also have the effect of creating `connection.json`s for projects that didn't previously have one e.g. created by a different machine).

2. Enhance the way we get a connection for a project to remove the `connection.json` per project by using the `api/v1/projects/${projectID}` API to determine which connection the project belongs to (the http status will be 200 if it exists, 404 if it doesn't). 

With option 2 we will:
* Always use live data
* Make as many API requests as connections exist (most likely only a couple).
    * We should also add a `--conID` to each `cwctl` command so that if we know the connection ID for a project, we can bypass the multiple GET requests (most already have the optional `--conID` flag). 

We could implement option 2 now (bypassing the requirement for option 1) as the change should be using an API request instead of reading the `connection.json` when getting the connection ID: https://github.com/eclipse/codewind-installer/blob/master/pkg/project/projectConnection.go#L82

**Comment by eharris369** [comment]
Verified that this is working now.
