### ISSUE TITLE
ID: Move Codewind content images to dist/images

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#1883]
**Description of the enhancement:**
Move all Codewind docs content images from  the `docs/images` folder to the `dist/images` folder according to:

![image](https://user-images.githubusercontent.com/7224752/73185107-67370880-4115-11ea-9d48-f6c037d06e20.png)

Record the amount of time this takes for planning/estimating purposes etc.

**Comment by micgibso** [comment]
Discussing with Travis, he says: 
I think we need to have two folders. One is for docs and one is for landing page, so we can separate them out.  Currently we have two, one is for landing page, and the dist one was the leftover one from mc, so probably we need to rename that one.  Please open an issue and I will fix it, so fix that too under this task. @travis We can use this issue, it's all the same thing, thx!

**Comment by sishida** [comment]
@travis1111 Hi, Travis, Could you please add a comment in this issue so we can assign you? Thank you!

**Comment by sishida** [comment]
Changes/updates to images were made here with this PR: https://github.com/eclipse/codewind-docs/pull/349

I am mentioning these changes for awareness, but they shouldn't impact the move itself for this issue.

**Comment by sghung** [comment]
TODO: setup a meeting to discuss these details. Three initial folks: Michael, Sarah, and Jake.
Also need to discuss the location in the playback call.

**Comment by sghung** [comment]
@micgibso a quick summary of my proposal from today's meeting:

My proposal is to use the `images` directory and to add subfolders into there. For example, `images/docs` and the existing `images/imagesfornews`. All website related images (e.g. main page) just goes into `images`. Any user seeing this would have a good idea of where to put the images into. I wouldn't think to look at the dist folder when an images folder at the root catches my eye first.

As mentioned above, the `dist` directory was from Microclimate days. In general, `dist` directories in websites usually have post processed files (such as minified CSS from the original source). If you look at the microclimate.dev site, all images come from `dist/images` in addition to the post processed `dist/css/` and other resources in there. It is confusing to use the `dist` directory since it tends to have another meaning in web structure.

As an example, other sites like kabanero use:
https://kabanero.io/docs/img/arch-overview-main.png -> example of image for documentation
https://kabanero.io/img/favicon/apple-touch-icon.png -> example of non-documentation image

They don't use a `dist` directory but they do separate between doc and non-doc images

If you want to move all images from `dist/images` to `images`, you can do a find and replace all in vscode to do this quickly. I tested this out for Sarah in a meeting. Although there were conflicting files (duplicate files), if those are resolved, it is a safe way to move all images over. Then the images can be organized bit by bit. That is to show it is possible to move it, if you do this, please talk with me as you may want to move the files in the existing `images` folder first (ordering for moving the files to the correct directory is important).

**Comment by sishida** [comment]
@micgibso and the ID team met this morning.

@sghung Let's work together to move the images to better locations. :)

**Comment by sishida** [comment]
On Friday, Feb. 28th, Steven and I moved the images in the codewind-docs repo so that all images are located in codewind-docs/docs/images.

I might organize them further into subfolders, but at least now we no longer have a dist/images folder to get confused about.
