### ISSUE TITLE
Why is there a 20s timer with same code for updateProjectForNewChange function

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#1998]
**Question synopsis:**

Related to https://github.com/eclipse/codewind/pull/1997

1. Why do we have that 20s timer in https://github.com/eclipse/codewind/blob/b0f16f0a76be2f543d501fc718ddeaa727d75d1d/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L262
Looks like most of the code inside that timer is duplicated on the if statement https://github.com/eclipse/codewind/blob/b0f16f0a76be2f543d501fc718ddeaa727d75d1d/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L217

2. Also does why the `updateProjectForNewChange` function only takes `chunk_total` value of 1 for the function to work properly and any other value passed, it will get stuck in that 20s timer?

/area iterative-dev

**Comment by yangcao77** [comment]
There is only 1 timer. 
The `newChunkRemaining` is to track if we are still waiting for any chunks, if not, we will proceed the build directly. 
The `timer` is a 20s timeout, if within the 20s, we do not receive any chunks, we would assume the chunk is lost, and proceed the build.


The `chunk_total` value takes any int value >= 1
`ProjectEventController` waits for the all chunks before triggering a build. Once it receives a new chunk, it will reset the timer (20s).  If all chunks have been received, triggers the build immediately.
`ProjectEventController` has a 20 secs timer to wait for expected incoming chunks, if no new chunks received in the 20s period of time for this project, `ProjectEventController` triggers an update build.

**Comment by yangcao77** [comment]
For example: 
`chunk_total = 3`

1. First time receives the request, `chunkNum=1`, known `chunk_total = 3`. `chunkRemaining = 2` `ProjectEventController` knows there are more chunking coming in, set `timer` with 20s timeout. 
2. Receives `chunkNum=3`, now `chunkRemaining = 1`.  `ProjectEventController` knows there are more chunking coming in, restart `timer`.

There are 2 cases now, 
a. receives `chunkNum=2`, now `chunkRemaining = 0`.  `ProjectEventController` would trigger the build, since all expected chunks have been received. 
a. no new chunk receives in 20s, `ProjectEventController` thinks #2 chunk is lost, it would proceed the build.

**Comment by yangcao77** [comment]
In your functional test case, since you only send 1 chunk to run the update test, but you set `chunk_total` to a random number. It will wait for 20s, since Turbine is waiting for the remaining chunks. 

The functional test setting was incorrect, and the fix in PR https://github.com/eclipse/codewind/pull/1997 would resolves the 20s wait time.

**Comment by ssh24** [comment]
Thanks for the explanation, it makes sense now.

/assign @yangcao77

**Comment by rajivnathan** [comment]
Discussed with Stephanie, we can add some additional comments to the code to help others trying to understand the reasoning and behaviour.

**Comment by malincoln** [comment]
@ssh24 pls verify and close. Thanks

**Comment by ssh24** [comment]
**Verified**
