### ISSUE TITLE
Summary data on javametrics graph not appearing

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2028]
After injecting metrics into an OpenLib project, whilst I can see that data is coming through, the summary page is empty

![Screenshot 2020-02-05 at 11 07 12](https://user-images.githubusercontent.com/13151286/73836645-b103ab00-4807-11ea-9f56-fd887effabc8.png)

**Comment by tobespc** [comment]
@hhellyer please take this one

**Comment by hhellyer** [comment]
@mattcolegate helped identify that the `/metrics` endpoint on an OpenLiberty app does not include that information.
Matt suggested adding the monitor-1.0 feature to server.xml would enhance this information:
```
  <featureManager>
    <feature>microProfile-2.0</feature>
    <feature>monitor-1.0</feature>
  </featureManager>
```
It does add data on `/metrics` but I couldn't see data specific to each endpoint even then.
We will need to add the information to `/metrics`, possibly via monitor-1.0, in order to display it. At the moment it isn't failing to display it just isn't available.

**Comment by tobespc** [comment]
Can you break this down into the following please

  - Add monitor-1.0 to see what data is on /metrics
  - Can we add additional data via monitor-1.0 ?
  - Discuss next steps based on findings

**Comment by mattcolegate** [comment]
I added `monitor-1.0` to an Open Liberty instance and we do get extra metrics, but I don't think we can use them to add additional data - what I thought we could use for http data actually turns out to be statistics against the servlet that's attached to the endpoint, like:
```
# TYPE vendor:servlet_io_openliberty_sample_getting_started_io_openliberty_sample_sample_application_request_total counter
# HELP vendor:servlet_io_openliberty_sample_getting_started_io_openliberty_sample_sample_application_request_total The number of visits to this servlet since the start of the server.
vendor:servlet_io_openliberty_sample_getting_started_io_openliberty_sample_sample_application_request_total 2
```
There might be a way of programatically finding out the endpoint of a particular servlet to tie it to the URL, but it was non-obvious in the Open Liberty template and I was unable to find a solution in a reasonable period of time.
However, the issue originally said that there's no data when metrics is injected, which is indeed the case and the screenshot holds true, but there is data on /metrics/codewind that could be used to populate the tables:
```
http_request_duration_max_microseconds{handler="http://127.0.0.1:32769/health",method="GET"} 29
http_request_duration_avg_microseconds{handler="http://127.0.0.1:32769/metrics",method="GET"} 144.0
http_request_total{handler="http://172.23.0.4:9080/health",method="GET"} 3
```
So I'm going to investigate why the tables aren't being populated by injected metrics

**Comment by mattcolegate** [comment]
The code to populate the tables with injected metrics simply wasn't there for Java metrics - I don't know why it didn't get included first time round. Used the existing code in the Node metrics dashboard to reduce the development time to get all stats displayed for an injected project. https://github.com/eclipse/codewind/pull/2486 awaiting review and merge.

![image](https://user-images.githubusercontent.com/15730986/76765023-aedd2680-678d-11ea-81b9-9c384062df77.png)

/pipeline Review/QA

**Comment by mattcolegate** [comment]
PR has been merged.
/pipeline Verify
