### ISSUE TITLE
Default status for appsody projects shouldn't be [Starting][Build Succeeded]

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2052]
When Appsody projects are created, either locally or on Kube, their default app status is always: `[Starting] [Build Succeded]`, even before any build has started, and long before the app is starting. (See https://github.com/eclipse/codewind-appsody-extension/blob/master/entrypoint.sh#L118).

Now, I know that this is at least partially a limitation on the Appsody CLI in that we can't easily get build and app status notifications from it, but I still feel that our default status shouldn't be `[Starting] [Build Succeded]`, as it's misleading and confusing to the user. Could we change the default state to something more meaningful?

**Comment by makandre** [comment]
What would you suggest?  We in fact do not go through a codewind build phase for appsody projects and invoke “appsody run” immediately, hence it is “starting” in that sense.

**Comment by johnmcollier** [comment]
> What would you suggest? We in fact do not go through a codewind build phase for appsody projects and invoke “appsody run” immediately, hence it is “starting” in that sense.

Do the states necessarily need to adhere to the Codewind-style app/build statuses that we have? Maybe we need some appsody-specific states that work better for Appsody projects? I believe we did that for Odo projects.

I'm not sure on _what_ exactly we should use, but I don't think starting as the default app state, or " Build succeeded" as the build state is right here.

**Comment by makandre** [comment]
I see what ODO is doing, it defined the strings in Codewind itself:

https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/utils/locales/en/translation.json#L30

I suppose we could do the same for Appsody but I'm hesitant to put Appsody specific strings into Codewind.  But it would be ok if the strings were generic, perhaps `[Staring][Build not required]`? (I still think `starting` is still correct in the context of Appsody but I'm opened to other suggestions)

**Comment by tetchel** [comment]
I've asked this before; isn't the build status for Appsody always "succeeded", even though that isn't really true because there is no build?

We could always hide the build status for Appsody projects.

**Comment by makandre** [comment]
Ok as long as it's not `if (it's appsody) then hide it`

**Comment by tetchel** [comment]
how else would we do it :(

**Comment by johnmcollier** [comment]
Can the appsody extension just not set a build status?

E.g. https://github.com/eclipse/codewind-appsody-extension/blob/master/entrypoint.sh#L122

**Comment by tetchel** [comment]
That makes sense to me and the IDEs can hide the build status if it's unknown, the same way we do for app status.

**Comment by makandre** [comment]
I'm ok with setting build status to blank, @tetchel @johnmcollier if you guys want to tackle this in 0.10.0 let me know.

**Comment by tetchel** [comment]
I think it is a good idea

**Comment by johnmcollier** [comment]
I think we should if possible

**Comment by makandre** [comment]
If appsody extension emits the build status as `unknown`, then in VSCode it appears as `[Starting][]`. @tetchel I assume we can hide the empty square brackets?

But it would seem that alone might not be enough, because at various points during the build and run of a project, Turbine itself will pre-set the build status to `in progress`, with messages such as "Build Started", "Calculating Differences", etc.  You can see that in the gif below:

![Screen Recording 2020-02-26 at 4 43 37 PM](https://user-images.githubusercontent.com/17596240/75392635-7054fa00-58ba-11ea-8ab0-29c0c6af8117.gif)

Are we concerned with these brief in progress messages?  If so then there would need to be some changes in Turbine.  Otherwise it's just a small change in appsody extension plus whatever it takes to hide the square brackets.

**Comment by sghung** [comment]
@tetchel on Eclipse, it displays a no build status info message. Would we have something similar in vscode?

<img width="492" alt="Screen Shot 2020-03-09 at 4 37 36 PM" src="https://user-images.githubusercontent.com/7843164/76255295-56090d80-6224-11ea-83b6-ad627fd4335e.png">

Andrew, your PR looks good, but I think if we commit this before the VSCode change, it's going to look like a bug

**Comment by makandre** [comment]
Have PR https://github.com/eclipse/codewind/pull/2446 for Turbine, to hide those brief flashes of "in progress" build statuses mentioned above https://github.com/eclipse/codewind/issues/2052#issuecomment-591674420

**Comment by eharris369** [comment]
PR for Eclipse IDE to hide build status if unknown: https://github.com/eclipse/codewind-eclipse/pull/619

**Comment by sishida** [comment]
Because we plan to include this issue in 0.11.0, we have removed the update from https://github.com/eclipse/codewind-docs/pull/468 with another PR https://github.com/eclipse/codewind-docs/pull/472.

After we create a 0.10.0 release branch for `codewind-docs`, we can then add the update from https://github.com/eclipse/codewind-docs/pull/468 back into the documentation. :)

**Comment by makandre** [comment]
Had to temporarily revert https://github.com/eclipse/codewind-appsody-extension/pull/90 as a problem was discovered and need a change on Codewind side first: https://github.com/eclipse/codewind/pull/2463

**Comment by makandre** [comment]
Doc changes were just merged to master.

/pipeline verify

**Comment by johnmcollier** [comment]
Verifying, noticed this was fixed a while back. Nice work, thanks!
