### ISSUE TITLE
Docs state that we generate a Dockerfile for imported projects that don't have one

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2060]
Live docs: https://www.eclipse.org/codewind/mdt-vsc-importedprojects.html

Docs file: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/importing-existing-projects.md

**Description:**
Our docs state that if a user imports a project that does not have a Dockerfile we will generated it for them. I've tested this with an imported Node.js project and did not see one get created, not sure if Liberty, Spring etc are the same.

**Comment by james-wallis** [comment]
/priority stop-ship
/area docs

Marking as a stop ship as at the moment we're telling customers that we can automatically generate something we absolutely need to make their project work in Codewind.

**Comment by jgwest** [comment]
@james-wallis: Could not find label: priority/stop-ship

**Comment by james-wallis** [comment]
VSCode screenshot: 
![image](https://user-images.githubusercontent.com/17385115/73941602-7708d680-48e5-11ea-9def-e0d51f114951.png)

**Comment by james-wallis** [comment]
Also verified with Liberty 
![image](https://user-images.githubusercontent.com/17385115/73941744-b505fa80-48e5-11ea-8cd1-d5d2523e82c5.png)

**Comment by sishida** [comment]
@james-wallis Thank you for catching this! I have created a PR to remove the inaccurate info: https://github.com/eclipse/codewind-docs/pull/347

A couple of questions:
1️⃣ Do we also need to edit this Swift info when it says, `A `Dockerfile-tools` file is generated to build the project.` and `A `Dockerfile` file is generated. It runs the application that was built by using `Dockerfile-tools`.`?
2️⃣ Do we need to give the users more instructions about how to create their own Dockerfile because it's not automatically created?

**Comment by james-wallis** [comment]
1. Yes needs to be removed, we don't create any Dockerfiles for any project type anymore.
2. I'm not sure how much help we'll need to give them. If they've used Docker before a link to the Dockerfile docs https://docs.docker.com/engine/reference/builder/ should be enough extra information. 

We might need more information than that, it depends how experienced "Jane" is with Docker

**Comment by sishida** [comment]
@james-wallis Thank you for the info! I have added a new commit to the PR: https://github.com/eclipse/codewind-docs/pull/347/files Does it look good to merge now? :)

**Comment by sishida** [comment]
The PR is merged. Closing this issue.
