### ISSUE TITLE
Investigate offline support with codewind default project types

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2078]
Investigate what happens when there is only intranet connection.

**Comment by makandre** [comment]
My approach to testing will be as follows:

- First, create projects while still connected to the Internet
- Then I cut Internet access (imagine if I was boarding a plane) and see if I can still work on the projects in this state.

**Comment by makandre** [comment]
Go projects are fine

**Comment by makandre** [comment]
Nodejs projects:

- projects can be worked on offline if it is already running prior to connection loss
- but if we need to manually build the project while offline, there are 2 issues:

  1. build fails since docker cache is not used #2354 
  2. if you managed to workaround the above problem, the app doesn't start if auto-build is enabled #2356

**Comment by makandre** [comment]
Python projects cannot be worked on offline, even if project was running prior to connection loss.  This is due to #2357 (the fix is simple)

**Comment by makandre** [comment]
Swift projects cannot be worked on offline, even if project was running prior to connection loss.  This is due to #2358

**Comment by makandre** [comment]
Lagom projects cannot be worked on offline, even if project was running prior to connection loss. This is due to #2371

**Comment by makandre** [comment]
MicroProfile and Spring Boot projects have can be worked on while offline

**Comment by makandre** [comment]
Open Liberty projects cannot be worked on offline, even if project was running prior to connection loss. This is due to #2374

**Comment by makandre** [comment]
### Summary of findings

- 3 project types can work offline as-is: `Go`, `Microprofile`, `Spring Boot`

- 3 project types don't work offline due to non-optimized dockerfiles:
  - `Python` #2357 
  - `Lagom` #2371 
  - `Open Liberty` #2374

- 2 projects types don't work because previous images are always removed before build, so docker caching cannot be leveraged:
  - `Nodejs` #2354 
  - `Swift` #2358

- Additionally, `Nodejs` also affected by #2356

**Comment by sghung** [comment]
We will focus on getting the top 3 issues in for 0.10.0

**Comment by makandre** [comment]
I now have fixes for `Nodejs` #2354 and `Swift` #2358 as well.

@elsony or @rajivnathan, could you take a look at the issues above and review associated PRs?  Thanks.

**Comment by makandre** [comment]
As it turns out, `Go` project only works because the template is very simplistic and does not pull in any external dependencies.  When users start adding dependencies they'll have problems working offline.  I've opened #2482 for this problem

**Comment by makandre** [comment]
All associated issues are now closed

/pipeline verify

**Comment by malincoln** [comment]
@sghung pls verify and close. Thanks

**Comment by sghung** [comment]
Closing, thanks for investigating Andrew
