### ISSUE TITLE
Cwctl remove doesn't give an error if an invalid option is passed in

### ISSUE THREAD

**Issue by johnmcollier** [eclipse/codewind#2079]
**Codewind version:** latest
**OS:** macOS

**Kubernetes cluster:** Minikube

**Description:**
I was trying to remove a remote install of Codewind I had on Minikube, but I made a typo in the command:
```
johns-mbp-3:latest johncollier$ ./cwctl remove remove -n codewind -w k66un7cq
Removing Codewind docker images..
Deleting Image  cw-testmp-bc49b110-490d-11ea-98f6-b91d8c0dcf8e:latest ... 
System architecture is:  amd64
Host operating system is:  darwin
Please wait whilst images are removed...  
```

I ran `cwctl remove remove` instead of `cwctl remove remote`. Instead of giving me an error about an invalid command, it immediately proceeded to remove my running, local instance of Codewind

**Steps to reproduce:**
1. Deploy Codewind locally **and** remotely
2. Run `cwctl remove remove` (or any invalid command, like `cwctl remove asdfsd`).
3. cwctl will try to remove the local Codewind instance, rather than erroring out.

**Workaround:** 
Enter the proper command

**Comment by liamchampton** [comment]
We currently use the parent command `remove` to handle removal of the local instance and sub commands to remove remote instances. To avoid ambiguity and help with validations of commands i think we should change this to use `cwctl remove local` & `cwctl remove remote`. This will keep consistency and help avoid this issue caused by the default behavior of the cli framework.

**Comment by liamchampton** [comment]
@johnmcollier now the change above has gone into master i think this can be verified/closed

**Comment by johnmcollier** [comment]
@liamchampton Fix look good to me, thanks!
