### ISSUE TITLE
Investigate offline support for Appsody projects

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2080]
Investigate what happens when there is only intranet connection.

**Comment by makandre** [comment]
My approach to testing will be as follows:

- First, create appsody projects while still connected to the Internet
- Then I cut Internet access (imagine if I was boarding a plane) and see if I can still work on the projects in this state.

**Comment by makandre** [comment]
My findings for node type appsody projects:

- If my appsody projects were running prior to the connection lost, I can still work on the projects. Changes I make are picked up by the controller and the application is restarted
- But if I need to do a manual build (which reruns `appsody run`) while disconnected, it fails at the `npm audit` step.  I have opened https://github.com/appsody/stacks/issues/646 for this

Stacks tested which exhibit this problem:

- nodejs-express
- node-red

Stacks tested not affected by this problem:

- nodejs-loopback

**Comment by makandre** [comment]
Kitura stack can run offline without issues.

**Comment by makandre** [comment]
`python-flask` stack can run offline without issues.

**Comment by makandre** [comment]
The findings for Java type projects is very similar to node type projects.

- projects can be worked on offline if it is already running prior to connection loss
- doing a manual build fails because Maven m2 cache is not mounted - neither to local m2 cache (which we don't want to do since it's inherently unsafe), or to a named docker volume

We already had an issue opened for the named docker volume in Codewind (https://github.com/eclipse/codewind/issues/583).  But we would also need some change in `appsody` CLI, which I've opened https://github.com/appsody/appsody/issues/895 for.

**Comment by sghung** [comment]
The appsody team looked into https://github.com/appsody/appsody/issues/895 but due to some issues, can't commit to 0.10.0

**Comment by makandre** [comment]
https://github.com/appsody/stacks/issues/646 is resolved
https://github.com/appsody/appsody/issues/895 PR has been accepted. We will need some changes in the Appsody extension https://github.com/eclipse/codewind-appsody-extension/pull/89

**Comment by makandre** [comment]
Docs was just merge as well.

/pipeline verify

**Comment by sghung** [comment]
Closing as this issue has been completed
