### ISSUE TITLE
cwctl version gives confusing error message

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2109]
**Description:**
The error received when calling cwctl version when the performance pod is not running, is confusing.
/cwctl version --all       
CWCTL VERSION: x.x.dev

CONNECTION ID 	PFE VERSION	PERFORMANCE VERSION	GATEKEEPER VERSION

SOME ERRORS WHILE DETECTING CONNECTION VERSIONS
CONNECTION ID 	ERROR
local		{"error":"config_connection_notfound","error_description":"Hostname or port for PFE not found"}

Something along the lines of "Unable to detect version of Codewind server". We should not really mention PFE to the user.

**Comment by tobespc** [comment]
recreated this morning, whilst not high priority it looks terrible

**Comment by jcockbain** [comment]
This error appears to be seen whenever a command that calls local PFE is made, without the performance container running. This is because our `getLocalHostnameAndPort` logic calls the docker `checkContainerStatus` function which does a check for >= 2 Codewind containers running (https://github.com/eclipse/codewind-installer/blob/master/pkg/docker/docker.go#L390).
