### ISSUE TITLE
SVT: Feedback to Codewind docs

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2136]
**Note from @sishida:** I am editing this comment as we fix the items listed here. I am copy/pasting the completed items in the comments.

**Codewind version:** 0.9.0
 
@jagraj @sishida 

/area docs

**Comment by MelHopper** [comment]
'What is Codewind' missing topic issue has now been fixed.

**Comment by sishida** [comment]
Che content was fixed as part of Che reorganization.

**Eclipse Che**
1.	Docker Registry Guidance
o	Missing space before “buildah”: If buildah is unable to resolve the registry hostname,buildahis unable to push your projects to the registry, and deployment on Kubernetes is prevented.

o	Missing space before “and”: If you do not develop any Codewind style projects,and you use an image registry that does not require credentials, then you do not need to specify an image registry.

2.	Using the Openshift Registry
_Adding the Openshift Registry in Codewind_
o	Should use “Enter” in code style as in other sections 

3.	Support for multiple users 
o	It uses “Keycloack” with upper case “K”, but doesn’t follow that standard in the “Note”: The Eclipse Che _keycloak_ server comes with its own LDAP provider, allowing you to register/manage users through Keycloak itself.

---
</br> 

### Local to remote development
**Overview**
o	Link doesn't work: Getting started with Codewind for Eclipse: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/mdteclipsegettingstarted.html
o	Can remove “\” from: `cwctl install remote \`

**Note:** There is a difference in notation style between Overview and other pages. The Overview tends to use `~/.codewind/<version>` while other pages tend to use `~/.codewind/{version}` (Deploy all-in-one, Deploying components individually & Removing a remote deployment).

**Deploy all-in-one**
_Deploying Codewind with CWCTL_
o	kubectl get namespaces – Can also use “oc get namespaces”

_Determine your Cloud ingress domain_
o	Separate the command its output
o	Command is missing an “o” (i.e., `oc get routes -n default`)
o	Output is missing the first characters (e.g., “N” for “NAME” & “r” for “registry-console”)

**Deploying components individually**
o	Missing enters after bullets:
![image](https://user-images.githubusercontent.com/49531960/74277794-267aea00-4ce6-11ea-958d-1107ae055281.png)

o	Should be consistent and use `<Codewind-namespace>`:
a) To enable privileged containers, enter `oc adm policy add-scc-to-group privileged system:serviceaccounts:<namespace>`
b) To enable containers to run as root, enter` oc adm policy add-scc-to-group anyuid system:serviceaccounts:<namespace>`

**Note:** The mismatch between the left menu and the actual title of the page can be confusing. For example, a menu item called “Connecting VS Code to a remote deployment”, but with a page called “Connecting VS Code to Remote Codewind”. 

**Connecting VS Code to Remote Codewind**
o	In (3), we should use “Username” instead of “developer username” and “Password” instead of “developer password” to be consistent with the IDE. Also, should use “Save” in code style as in the previous bullet: 
![image](https://user-images.githubusercontent.com/49531960/74277920-56c28880-4ce6-11ea-8244-e2563481350d.png)

o	In (4), we should use “username”. Furthermore, we should use “namespace” instead of “repo name” to be consistent with other instructions: 

_Copying an existing local project to the cloud_
o	“Add Existing Project” instead of “Add existing project” 
![image](https://user-images.githubusercontent.com/49531960/74277948-62ae4a80-4ce6-11ea-8316-6d015bf7ac17.png)

o	“nodejs” instead of “NodeJS”
![image](https://user-images.githubusercontent.com/49531960/74277956-6641d180-4ce6-11ea-8d7d-e15f0bb14174.png)
 
### Connecting Eclipse to Remote Codewind
o	“username” instead of “user name” 
![image](https://user-images.githubusercontent.com/49531960/74277969-6b9f1c00-4ce6-11ea-96a8-cfc453349592.png)

_Adding a new deployment registry (The IDE uses “image registry”, so we need to be consistent)_
o	“Locate and click “Add…”
![image](https://user-images.githubusercontent.com/49531960/74277981-6fcb3980-4ce6-11ea-9812-99a3fb32ee1c.png)

_Create a new project_
o	Click “Create New Project”
![image](https://user-images.githubusercontent.com/49531960/74278023-81acdc80-4ce6-11ea-9fda-80357a05386a.png)

_Copying and existing local project to the cloud_
o	Click the `Add Existing Project` button 
![image](https://user-images.githubusercontent.com/49531960/74278034-8a051780-4ce6-11ea-9339-376b1a7c1c88.png)

o	“Node.js” instead of “NodeJS”
![image](https://user-images.githubusercontent.com/49531960/74278042-8d000800-4ce6-11ea-8628-8547125df065.png)

**Note:** Doesn’t match with the left menu - In the next step you learn how to remove an existing Codewind deployment: Remove a remote deployment of Codewind 


### Removing a remote deployment 
o	Missing a coma: 
In this procedure ---,--- you removed the Codewind and Keycloak services from your cloud platform, and you also removed the linkage to it from your IDE.

**Comment by sishida** [comment]
Asked for clarification from Sujeily in Slack:
2.	Using the Openshift Registry
_Adding the Openshift Registry in Codewind_
o	Should use “Enter” in code style as in other sections

**Comment by sishida** [comment]
PR for this change: https://github.com/eclipse/codewind-docs/pull/365
```
3.	Support for multiple users 
o	It uses “Keycloack” with upper case “K”, but doesn’t follow that standard in the “Note”: The Eclipse Che _keycloak_ server comes with its own LDAP provider, allowing you to register/manage users through Keycloak itself.
```

**Comment by sishida** [comment]
### Working with templates
1.	Manage templates
o	In VS Code, the menu item is “Template Source Manager”. In Eclipse, the menu item is “Manage Template Sources”.
![image](https://user-images.githubusercontent.com/49531960/74278072-9b4e2400-4ce6-11ea-86c1-033adbb55430.png)

o	“Add New” instead of “Add New”
![image](https://user-images.githubusercontent.com/49531960/74278081-9f7a4180-4ce6-11ea-9be7-960b21a05ca7.png)

**Comment by sishida** [comment]
- I tested the "Getting started with Codewind for Eclipse" link on both the staging server and the live site. It worked on both.
- PR for removing the `\`: https://github.com/eclipse/codewind-docs/pull/368

**Overview**
o	Link doesn't work: Getting started with Codewind for Eclipse: http://codewind-docs.rtp.raleigh.ibm.com:4321/codewind/mdteclipsegettingstarted.html
o	Can remove “\” from: `cwctl install remote \`

**Comment by sishida** [comment]
PR for this change: https://github.com/eclipse/codewind-docs/pull/369

**Deploy all-in-one**
_Deploying Codewind with CWCTL_
o	kubectl get namespaces – Can also use “oc get namespaces”

**Comment by sishida** [comment]
PR for these changes: https://github.com/eclipse/codewind-docs/pull/370

**Deploying components individually**
o	Missing enters after bullets:
![image](https://user-images.githubusercontent.com/49531960/74277794-267aea00-4ce6-11ea-958d-1107ae055281.png)

o	Should be consistent and use `<Codewind-namespace>`:
a) To enable privileged containers, enter `oc adm policy add-scc-to-group privileged system:serviceaccounts:<namespace>`
b) To enable containers to run as root, enter` oc adm policy add-scc-to-group anyuid system:serviceaccounts:<namespace>`

**Comment by sishida** [comment]
PR for last of these variable format changes: https://github.com/eclipse/codewind-docs/pull/371
Other variable format changes included in PRs along with other change(s) for those files.

**Note:** There is a difference in notation style between Overview and other pages. The Overview tends to use `~/.codewind/<version>` while other pages tend to use `~/.codewind/{version}` (Deploy all-in-one, Deploying components individually & Removing a remote deployment).

**Comment by sishida** [comment]
PR for these changes: https://github.com/eclipse/codewind-docs/pull/414

**Note:** The mismatch between the left menu and the actual title of the page can be confusing. For example, a menu item called “Connecting VS Code to a remote deployment”, but with a page called “Connecting VS Code to Remote Codewind”.

**Comment by sishida** [comment]
### Getting Started
 **VS Code**
1.	Installing Codewind for VS Code
o	Link for Docker Compose in (1): Install Docker 17.06 or later. If you use Linux, you must also install Docker Compose.

2.	Creating your first project
o	“Open Application” instead of “Open App” in (8):
<img width="297" alt="Screen Shot 2020-02-11 at 11 48 27 AM" src="https://user-images.githubusercontent.com/49531960/74276705-372a6080-4ce4-11ea-8fab-c443855edfce.png">

3.	Making a code change with VS Code
o	“Stopped” instead of “stopped” as in VS Code (3): The status of the project changes to stopped while the project is rebuilt and deployed
o	“Running” instead of “running” as in VS Code (3): After a few moments, the status changes back to running
o	“Open Application” instead of “Open App” in (4):
<img width="462" alt="Screen Shot 2020-02-11 at 11 51 21 AM" src="https://user-images.githubusercontent.com/49531960/74276757-4c06f400-4ce4-11ea-9c95-09ed5df755f6.png">

---
</br> 

**Eclipse** 
1.	Installing Codewind for Eclipse
o	Link for Docker Compose in (1): Install Docker 17.06 or later. If you use Linux, you must also install Docker Compose.
o	After (5), the numbering is reset to (1) instead of using (6). Also, it mentions the word "CODEWIND", but in Eclipse, the IDE uses "Codewind":
![image](https://user-images.githubusercontent.com/49531960/74277518-b2d8dd00-4ce5-11ea-95db-6e5ebe24b85d.png)
 
2.	Creating your first project
o	“Open Application” instead of “Open App” in (6)
![image](https://user-images.githubusercontent.com/49531960/74277494-a81e4800-4ce5-11ea-80ed-f97125f207c7.png)

3.	Making a code change with Eclipse
o	“Open Application” instead of “Open App” in (4)
![image](https://user-images.githubusercontent.com/49531960/74277503-abb1cf00-4ce5-11ea-88d5-90dcee661fc0.png)

---
</br> 

**Note:** There is a difference in style between the Eclipse and VS Code documentation. VS Code uses _italic_ to refer to general texts (i.e., Search for _Codewind_) while Eclipse uses bold (i.e., Search for **Codewind**). Furthermore, VS Code uses a standard font to refer an action or object text (i.e., CODEWIND) while Eclipse use code style text:
![image](https://user-images.githubusercontent.com/49531960/74277566-c421e980-4ce5-11ea-9388-03a97e71881d.png)

**Comment by sishida** [comment]
This instance of "user name" is correct in this context. If you have the variable `username`, then you can write it as one word. However, if it is not used as a variable name, "user name" should be two words.

o	“username” instead of “user name” 
![image](https://user-images.githubusercontent.com/49531960/74277969-6b9f1c00-4ce6-11ea-96a8-cfc453349592.png)

**Comment by sishida** [comment]
PR for this issue: 

- See previous comment about "user name." This was left as two words.
- Some of the feedback, such as about Node.js, no longer applies because of other file changes.

### Local to remote development

**Connecting VS Code to Remote Codewind**
o	In (3), we should use “Username” instead of “developer username” and “Password” instead of “developer password” to be consistent with the IDE. Also, should use “Save” in code style as in the previous bullet: 
![image](https://user-images.githubusercontent.com/49531960/74277920-56c28880-4ce6-11ea-8244-e2563481350d.png)

o	In (4), we should use “username”. Furthermore, we should use “namespace” instead of “repo name” to be consistent with other instructions: 

_Copying an existing local project to the cloud_
o	“Add Existing Project” instead of “Add existing project” 
![image](https://user-images.githubusercontent.com/49531960/74277948-62ae4a80-4ce6-11ea-8316-6d015bf7ac17.png)

o	“nodejs” instead of “NodeJS”
![image](https://user-images.githubusercontent.com/49531960/74277956-6641d180-4ce6-11ea-8d7d-e15f0bb14174.png)

**Comment by sishida** [comment]
Relevant PRs have been merged. Closing this issue.
