### ISSUE TITLE
Remove deprecated `request` module from NodeJS/Typescript code.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#2189]
The node js `request` module is deprecated as of Feb 11th 2020: https://www.npmjs.com/package/request - this means it may not receive future updates, including security fixes.

Long term we should move to something like Axios, see: https://github.com/request/request/issues/3143

There are usages of the request module in pfe and also in the VSCode plugin via `request-promise-native`.

**Comment by tetchel** [comment]
Wow, that's a surprise...

**Comment by tetchel** [comment]
Reviewing that thread, it sounds like [`got`](https://github.com/sindresorhus/got) has everything and seems to be the fastest growing / most actively maintained.

**Comment by malincoln** [comment]
are we looking to merge this into 0.10.0?

**Comment by hhellyer** [comment]
@malincoln - I don't think replacing `request` has to be in the next release but we should do it `soonish`. (i.e. before  a bug or security vulnerability forces us to do it in a hurry.) There's several possible modules we could swap to and we don't necessarily have to use the same module in the editor plugin as we do in PFE. (Though it might be nice.)

@tetchel - We've already used `axios` so it should have Eclipse approval, another Eclipse project might be using `got` already though. I don't think we're emotionally invested in either though.

**Comment by malincoln** [comment]
I agree we should actively investigate and determine which module would work best and see how we progress.

**Comment by tetchel** [comment]
The axios API looks fine too, both are upgrades from `request` :)

**Comment by tetchel** [comment]
Marilyn is seeking approval for got 10.6.0 (latest)

**Comment by malincoln** [comment]
Asked @NikCanvin to take a look.
"I checked it, only 'danger' finding, was a dual lic case, but looking it at, either lic is acceptable to Eclispe IP legal"

Gave him the specific release of 10.6.0 to review.

**Comment by malincoln** [comment]
@tetchel pls proceed.  This new pkg can be picked up when the legals are done for 0.10.0

**Comment by tetchel** [comment]
ok, this will not be done for 0.10 though.

**Comment by jgwest** [comment]
Adding iterative-dev for typescript filewatcher code
/area iterative-dev

**Comment by tetchel** [comment]
This is done in VS Code so I opened and closed #2449 for VS code specifically.

**Comment by malincoln** [comment]
Need to complete for PFE now.

**Comment by hhellyer** [comment]
I'm taking a look at this. I'll use `got` as well since we've done the license checks and it seems to function as a drop in replacement if we use `got.stream()`.
I'll need to update portal and gatekeeper.

**Comment by elsony** [comment]
@jgwest Given that there are some impact to filewatcherd, I am assigning this one to you on the iterative dev side. Please also include your work to include the related work on the rest of the turbine components as well.

**Comment by malincoln** [comment]
assigning to 0.11.0 as work is required for a few squads at this point.

**Comment by jgwest** [comment]
Work still in progress for iterative-dev.

**Comment by jgwest** [comment]
The filewatcher PR has been merged, but Turbine's use of the `request` dependency looks more difficult to remove... Request is pulled in via our use of the kubernetes-client library (https://www.npmjs.com/package/kubernetes-client) used by Turbine (not to be confused with the official client, @kubernetes/client-node)

I discussed it briefly with the iterative-dev squad, and it sounds we want to wait for the existing k8s dependency to update to another HTTP client library (if it does), rather than spending time rewriting our code in all the cases where we are interfacing with Kubernetes (switching from request to use a new k8s client librar, (likely @kubernetes/client-node)

Since the ODO2 work will likely cause all this code to be deprecated/removed anyways (as we switch to interfacing with k8s via the ODO CLI) in the short to medium term, it doesn't make sense to spend effort replacing our Kubernetes code with a different package.

BUT, as an FYI, this means that we will NOT be able to remove request from the codewind container image at this time. However, since it's a client library it's unlikely to there will be any significant vulnerabilities that we need to mitigate in it (and FWIW Codewind already has more relevant security items in this area that we are not prioritizing higher, such as our always trusting self-signed certs, and our lack of encryption on the FWd WebSocket endpoint API).

**Comment by hhellyer** [comment]
@jgwest - I don't think we can do anything about our dependencies dependencies. I raised this so we could eliminate any direct dependencies on `request` that are under our control. I'll move this to verify now.

Also @kubernetes/client-node has a dependency on request anyway:
https://www.npmjs.com/package/@kubernetes/client-node?activeTab=dependencies

**Comment by hhellyer** [comment]
@jgwest @tetchel - I think we've done what we need to for this for the moment. Are you happy for me to close? (I raised this but since it covers several components I thought I'd check first.)

**Comment by tetchel** [comment]
Yes this can be closed
