### ISSUE TITLE
Template API tests failing intermittently - implement Template.js lock

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2190]
While attempting to review https://github.com/eclipse/codewind/pull/2144, I ran the Template API test and got 2 test failures. I ran it again and they all passed, a third time, I got 1 failure but different to the first. There are clearly timing issues that may be in the APIs or the test code but we must investigate and fix this asap.

**Comment by stalleyj** [comment]
[testresult.txt](https://github.com/eclipse/codewind/files/4198979/testresult.txt)

**Comment by james-wallis** [comment]
Although I've put up that (failing) PR which was supposed to fix the intermittent errors I think that this is an implementation defect rather than a test defect, creating a race condition between `GET` requests.

When making two `GET` requests one after the other to `/api/v1/templates/repositories` they will both try to update the `repositoryList` variable.

I've worked up a solution and passed it by @hhellyer and @tobespc and the change to the implementation will see the `POST`, `GET` and `DELETE` API requests doing the following:

**POST**
* Updates the content
* `LOCK`s the data from being accessed
* If `LOCK` is already set when the a `POST` request is made then it will return `409 conflict`

**GET**
* Returns the current state of the data
* If `LOCK` is already set when this request is made it will return `409 conflict`

**DELETE**
* Updates the content
* `LOCK`s the data from being accessed
* If `LOCK` is already set when the a `DELETE` request is made then it will return `409 conflict`

This solution should:
* Remove the test flakiness as they will receive `409 conflict` when the API is being updated.
* Make the `GET` request a lot faster as it will just return the current state of the data.

**Comment by james-wallis** [comment]
The PR for this has been accepted. Closing.
