### ISSUE TITLE
Create an open doc build from codewind-docs master

### ISSUE THREAD

**Issue by micgibso** [eclipse/codewind#2230]
Create a public doc build that builds and displays the latest content from the https://github.com/eclipse/codewind-docs master branch.  

Optional:  Doc releases are branched every eGA so we have docs for 0.8.0, 0.7.0 etc. Enable users to select older releases and display these in a similar way.  

Investigate GitHub pages or other mechanism as appropriate.

**Comment by james-wallis** [comment]
Related to https://github.com/eclipse/codewind/issues/2233

**Comment by micgibso** [comment]
@sghung Still need an open doc build, see above. Are GitHub pages a viable option?

**Comment by sghung** [comment]
@micgibso we'd need to look into this some more. However, for sure Github pages won't be able to support your requirements.

It can do jekyll stuff, but not run your own custom scripts, that means our "last update" script won't work as that is a shell script. 

In addition, github pages just serves one page, not one for each version. Is having one for each version something that is needed? I think the most up-to-date one is the best way, otherwise, older versions can be run on your own machine. I don't see anyone besides the ID team needing older snap shots of the docs and I think everyone on the doc team should know how to launch our docs. However, if we need that requirement, we'd definitely need some other mechanism.

For github pages, one possibility is we generate all the .html pages on our internal server, then push those static pages to github pages. In that way, we never upload the MD files to github pages to let it run jekyll there. However, this would work well with just one branch.

**Comment by micgibso** [comment]
@sghung See https://github.com/eclipse/codewind/issues/2233 posted by James above for the requirement for users to serve up different versions of the public docs.  

So we have two things going on here:
1. We want the latest on master to be displayed on a public server.
2. We want for users to be able to be able switch between documentation versions by a drop down list at the top of the page.

Back to this issue, so if I understand correctly, we could have master served up by GitHub pages, minus the "last update" script, as static HTML from the master branch. I like the idea of your suggestion in the last paragraph running on master branch.  Would it update when we fold in our PRs as our internal build does now?  If it does, it sounds like a really good solution to build the latest docs and get them out there in the public domain. 

For 2. above, appreciate that's going to be more challenging, and that issue is already taking on a life of its own.
