### ISSUE TITLE
Make public docs release specific

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#2233]
**Codewind version:** 0.9.0

**Description of the enhancement:**

It would be good if we could publish Codewind version specific documentation

**Proposed solution:** 

Give the user an option to switch between documentation versions by a drop down list at the top of the page. 

For example by default or navigating to the page : 

https://www.eclipse.org/codewind/gettingstarted.html you would see information related to the current shipping version

where as 

https://www.eclipse.org/codewind/{version}/gettingstarted.html would provide information about the specific released version of Codewind or latest master.

**Comment by sishida** [comment]
Hi, team, If you would like to see what the docs repo looked like at a previous release, we have older release branches of `codewind-docs`: https://github.com/eclipse/codewind-docs/branches

I understand this solution isn't the easiest to navigate, but I just wanted to point out that we have it if anyone's interested. Thank you! :)

**Comment by james-wallis** [comment]
@sishida I assume the above is a workaround for this issue?

If a user is using a previous version of Codewind I think it is a valid use case for them to want to view the respective documentation, given how much we aim to change for each release and as we're currently in the middle of a complete documentation refactor.

As we're branching on each release can the current build system be changed to publish the pages as @markcor11 has described above? 

Kubernetes has different versions for their API for example (see the version drop down on the right of the image):
![image](https://user-images.githubusercontent.com/17385115/74740709-5597db00-5253-11ea-8e16-4f8347026de1.png)

**Comment by sishida** [comment]
I mentioned the release branches to a teammate who wasn't aware of them and just wanted to mention them in a comment here in case. :)

For publishing different versions of the doc, I think someone else brought up the idea to use these older release branches as the basis for creating these versioned published docs? I am not sure what it'd take to get this to work, but I will tag @travis1111 and @sghung for awareness. Thank you!

**Comment by micgibso** [comment]
This needs to be prioritised higher in our backlog due to Kabanero now running a different version of Codewind.

**Comment by sghung** [comment]
I did a quick proof of concept during the call today: https://github.com/eclipse/codewind-docs/pull/435

Instead of dynamically generating the version specific content each time, we cache a copy. This allows someone to use URLs like:

http://localhost:4321/codewind/0.7.0/
http://localhost:4321/codewind/0.8.0/open-api-tools-for-eclipse.html

These snapshots were generated from the appropriate branch with modifications to the config.yml to ensure the baseurl is "codewind/<version #">", otherwise links and images will be broken.

The biggest problem is if we want a version selection combo box for every page (including in old doc versions, since we'd need to update every page to have an updated combo box). We'd need to think about how to handle this scenario more.

**Comment by sghung** [comment]
Demoed the release specific website I quickly prototyped. Tim D didn't like having a combo with a drop down of all the versions. More discussion is required so tagging with tech topic.

Jag also brought up a good point, we don't want to show versions we don't support anymore

**Comment by sishida** [comment]
Discussion from Slack:

From @sishida:
Here's an idea about the version specific documentation: What if we linked the version URLs in each of the news pages? For example, the 0.8.0 news page could have a statement like, "Click here for the 0.8.0 version of the website." and it could open in a new tab so the user wouldn't get stuck in the older version of the website. Would something like this work, perhaps?

From @sghung:
If you say that, then you would need to generate the cached version as you are publishing. For example, if you wanted that statement for 0.10.0, I'd need to put our site's content into /codewind/0.10.0 as well as in /codewind. Otherwise you would need to update the news page after the release just to reference an older version of the site.

**Comment by jgwest** [comment]
Re: Combo drop down containing all the versions, that seems to be the common practice:
- Helm: https://helm.sh/docs/
- Kube: https://kubernetes.io/docs/home/
- Ansible: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu
- OpenShift: https://docs.openshift.com/container-platform/4.2/welcome/index.html
(etc)

**Comment by micgibso** [comment]
See https://github.com/eclipse/codewind-docs/pull/466 for the latest.

**Comment by kimholmes** [comment]
@sghung Here's what I was thinking:
![nav_Versions](https://user-images.githubusercontent.com/21316329/78269560-c29bc300-74d7-11ea-9b4e-d28ef0e84fe7.png)

**Comment by micgibso** [comment]
@kimholmes A separate version menu seems to be the norm in the examples quoted above, how about something like this for example:
![image](https://user-images.githubusercontent.com/7224752/79440171-98fd9400-7fcd-11ea-866d-2f882bb6abf2.png)

**Comment by jgwest** [comment]
@micgibso IMHO it should be a text box rather than just just a simple `Version` string, citing as design precedent all the linked examples in my comment above:
![image](https://user-images.githubusercontent.com/7594762/79518717-c6732d80-801f-11ea-905c-1cb24fd953e3.png)

**Comment by micgibso** [comment]
@jgwest Yes, this ^^^.  
I just wanted us to consider not having the doc version choice on the same menu as the function as per [the suggestion](https://github.com/eclipse/codewind/issues/2233#issuecomment-607927721).

**Comment by micgibso** [comment]
Closing as not planning on doing it.
