### ISSUE TITLE
New and Noteworthy for 0.10.0/0.11.0

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind#2323]
Need to add a news page for 0.10.0 release

**Comment by beccabau** [comment]
release engineering checklist - https://github.ibm.com/dev-ex/dev-ex-planning/issues/1017

**Comment by sishida** [comment]
Because we will no longer have a 0.10.0 release, I am updating this issue for 0.11.0 new and noteworthy content.

Existing 0.10.0 content:
- Original PR for 0.10.0 new and noteworthy file: https://github.com/eclipse/codewind-docs/pull/493
- 0.10.0 new and noteworthy file: https://github.com/eclipse/codewind-docs/blob/master/docs/_news/news10.md

To do list for 0.11.0:
[ ] Change the `news10.md` file name to `news11.md` and update the news TOC accordingly.
[ ] Add in 0.11.0 new and noteworthy content.

**Comment by beccabau** [comment]
FYI new PR for 0.11.0 https://github.com/eclipse/codewind-docs/pull/531

**Comment by sishida** [comment]
I created this PR: https://github.com/eclipse/codewind-docs/pull/535

The publication date has changed from what was originally planned. Also, because we didn't release 0.10.0, I have deleted the `news10.md` file from our `_news` folder.

Tagging @beccabau for awareness.
