### ISSUE TITLE
intellij 0.9.0 plugin / marketplace Getting Started link gives 404.

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2372]
**Codewind version:** 0.9.0 Intelij
**OS:**

**Che version:**
**IDE extension version:**.   intellij
**IDE version:**
**Kubernetes cluster:**

**Description:**

When viewing codewind plugin in the intellij marketplace the Getting Started link returns a 404 File not found.     

https://plugins.jetbrains.com/plugin/13839-codewind
 
It looks like we have the extra .md. withithing the url

https://www.eclipse.org/codewind/mdt-intellij-getting-started.md.html

similar to reported in https://github.com/eclipse/codewind/issues/2300

**Steps to reproduce:**

follow getting started link in intellij marketplace or (within intellij plugin view for codewind)
https://plugins.jetbrains.com/plugin/13839-codewind

<img width="794" alt="Screenshot 2020-03-02 at 17 30 33" src="https://user-images.githubusercontent.com/9268814/75701389-9825d280-5cab-11ea-9884-d543092b5abd.png">

**Workaround:** 

update intellij marketplace to use correct url

https://www.eclipse.org/codewind/mdt-intellij-getting-started.html

**Comment by josephca** [comment]
This was fixed by https://github.com/eclipse/codewind/issues/2300 and target **0.10.0** release as the same documentation can be obtained from https://plugins.jetbrains.com/plugin/13839-codewind
![image](https://user-images.githubusercontent.com/25185698/75704537-8a5e5600-5c87-11ea-8448-2718e651d4e2.png)

Please re-open if this should be fixed before **0.10.0** release.

**Comment by AndyRWatson** [comment]
Can we not update ahead of 0.10 ?   Thats a few weeks out and the wrong url doesnt make for a good user experience

**Comment by AndyRWatson** [comment]
can we please reopen (not sure I can) as we should look to get the url fixed before 0.10.

**Comment by josephca** [comment]
@AndyRWatson @jopit The fix is made and verified: http://download.eclipse.org/codewind/codewind-intellij/0.9.0/26/codewind-intellij-0.9.0.zip
However, in order to republish we need to bump up the version to next (i.e. 0.9.1) - republishing the same version is not allowed by the marketplace.  We need to discuss whether we (1). fix it for 0.10.0 (2). create 0.9.1 ifix.

**Comment by jopit** [comment]
I don't think we should create an entire codewind ifix just to fix the broken link.

**Comment by AndyRWatson** [comment]
ok I agree.  also spoken to @sghung and he has agreed to look at creating a temporary link to the correct page until 0.10 fixes the issue.   Would look to do the same for eclipse

**Comment by sghung** [comment]
See https://github.com/eclipse/codewind/issues/2425#issuecomment-595972527 for the file that was uploaded and an explanation of my fix.

**Comment by josephca** [comment]
Verified the fix. Closing it on behalf of @AndyRWatson
