### ISSUE TITLE
The recent doc file name changes have not been reflected fully in the corresponding Codewind codes

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2373]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The recent docs change (https://github.com/eclipse/codewind-docs/pull/421) should be reflected in the Codewind codes (not only IntelliJ)

e.g. **mdt-** has been removed from docs and the corresponding changes need to be done. 

grep intellij-getting-started.html -r *

dev/bin/main/META-INF/plugin.xml:    
To get started, see <a href="https://www.eclipse.org/codewind/**mdt-**intellij-getting-started.html"
To get started, see <a href="https://www.eclipse.org/codewind/**mdt-**intellij-getting-started.html"

dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java:            GETTING_STARTED_INFO_URL = DOC_BASE_URL + "/**mdt-**intellij-getting-started.html",

There are more file name changes that need to be handled. 

**Steps to reproduce:**

**Workaround:**

**Comment by sishida** [comment]
I have opened the following PRs to update the links:
1️⃣Since the links changed more than just removing `mdt`, I'm not sure about these updates. They need review: https://github.com/eclipse/codewind-intellij/pull/73
2️⃣I'm pretty confident this one is good to go, though: https://github.com/eclipse/codewind-intellij/pull/72
