### ISSUE TITLE
Add detailed registry information to instructions for using Codewind remotely 

### ISSUE THREAD

**Issue by MelHopper** [eclipse/codewind#2382]
Currently, Eclipse Che has a whole topic dedicated to Adding a Container Registry, che-setupregistries.html

The tutorial for Using Codewind Remotely should have this content too.

**Tasks**

1. Copy the content in che-setupregistries.html into a new topic remoteuse-setupregistries.md with title 'Adding a container registry to Codewind'. 

2. Amend content to make it valid for remote Codewind rather than Eclipse Che Codewind:
i) difference in how you open the Image Registries Manager - in Theia you right click Projects, but in remote you right click the remote connection
ii) check there are no other differences

3. Place this new topic in the Using Codewind Remotely tree as follows:

**Using Codewind Remotely**
-> Overview
-> Connecting your IDE to remote Codewind
-->Connecting VS Code to remote Codewind
--> Connecting Eclipse to remote Codewind
-> Adding a container registry in remote Codewind
-> Creating and importing projects

4. Ensure section 2. and Next Steps of 'Connecting VS Code to remote Codewind' and 'Connecting Eclipse to remote Codewind' are moved into this new topic about adding a container registry, to ensure the user journey is not broken or incorrect.

5.Ensure 'Next Steps' are added to the new topic, and ensure that orientation and next steps are correct throughout the modified user journey.

**Comment by MelHopper** [comment]
@tetchel FYI

**Comment by sishida** [comment]
Hi, @MelHopper, I think this issue is good to close. I have added the new file, remote-setupregistries.md and have received approval from both Tim E. and Erin H.

In your original comment in this issue, I was not sure about the statement, "4. Ensure section 2. and Next Steps of 'Connecting VS Code to remote Codewind' and 'Connecting Eclipse to remote Codewind' are moved into this new topic about adding a container registry, to ensure the user journey is not broken or incorrect."

Did you want to copy/paste these sections into the new file, remote-setupregistries.md? Could you please open a PR against remote-setupregistries.md to illustrate what you'd like to add? Thank you!

**Comment by sishida** [comment]
PRs to update the links in the UIs:
- Eclipse master: https://github.com/eclipse/codewind-eclipse/pull/610
- Eclipse 0.10.0: https://github.com/eclipse/codewind-eclipse/pull/611
- IntelliJ master: https://github.com/eclipse/codewind-intellij/pull/79
- IntelliJ 0.10.0: https://github.com/eclipse/codewind-intellij/pull/80
- VS Code master: https://github.com/eclipse/codewind-vscode/pull/492
- VS Code 0.10.0: https://github.com/eclipse/codewind-vscode/pull/493

**Comment by eharris369** [comment]
I think the registries information belongs in a separate file rather than included in the remote deploy info because:
- There are many places where this information is relevant including:
          creating a new connection
          creating a new project
          adding an existing project
          context menu item on connections
- If it is a separate document, links to it can be inserted directly in the step of the above documents where the user might have to deal with registries
- We are working on supporting registries for local Codewind as well so it will not be specific to remote

**Comment by sishida** [comment]
I have closed this PR: https://github.com/eclipse/codewind-docs/pull/483

To do:
1️⃣ PR 483 included some text updates, such as saying "image registry" instead of "deployment registry." I will make a new PR for those updates.
1️⃣ Make a new PR for linking section 2 in remotedeploy-eclipse.md/remotedeploy-vscode.md into remote-setupregistries.md. A link prevents duplicate content and keeps remote-setupregistries.md on its own page.

**Comment by sishida** [comment]
PRs merged. Closing this issue.
