### ISSUE TITLE
SVT: Add Existing Open Liberty project fails - missing files

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#243]
**Codewind version:** eclipse  - latest 
**OS:** Mac

**Description:**

If I create an open liberty project (openLiberty1) all is good. Remove the project from codewind but leave on disk. Now try adding it back using add existing project wizard but the project fails to build because of missing files. See this info in .projects folder:

  "validationStatus": "failed",
  "validationResults": [
    {
      "severity": "error",
      "filename": "Dockerfile-build",
      "filepath": "openLiberty1/Dockerfile-build",
      "type": "missing",
      "label": "Missing required file",
      "details": "Dockerfile-build is required but was not found.",
      "quickfix": {
        "fixID": "generateMissingFiles",
        "name": "Generate missing files",
        "description": "Generate missing required files."
      }
    },
    {
      "severity": "error",
      "filename": "pom.xml",
      "filepath": "openLiberty1/pom.xml",
      "type": "invalid",
      "label": "A maven profile named 'microclimate' was not found.",
      "details": "A microclimate build profile is recommended for Microprofile projects. See the project import documentation for details."
    }
  ],

**Steps to reproduce:**

1. Create an open liberty project
2. Remove project from codewind but leave on disk.
3. Use add existing project wizard to add project back to codewind.
 
**Workaround:** 

When binding the existing project again select "No" and then select "Other" for the project type.

**Comment by mmulholl** [comment]
Added priorty/stopship:

Think this would be a common scenario. Work on the project, remove from codewind, sometime later start work on it again.

**Comment by mmulholl** [comment]
Just noticed when adding an existing Liberty Profile project the type is set to  "Microprofile / Java EE" by default. If the default is left the problem happens. However if you set the type to "Other (Basic Container)" the project imports successfully.

**Comment by johnmcollier** [comment]
@mmulholl I believe that's expected currently. The Open Liberty template can't currently be used as a `Microprofile / Java EE` project, but rather must be used as a generic Docker / `Basic container` project.

The `Microprofile / Java EE` project type requires WebSphere Liberty at the moment I believe.

**Comment by johnmcollier** [comment]
I believe @rajivnathan was looking at getting it running as a Liberty project, but don't believe that's done yet. I'll let him confirm

**Comment by rajivnathan** [comment]
Yes, that's correct. Open Liberty should only be supported as a docker project for the moment. https://github.ibm.com/dev-ex/dev-ex-planning/issues/945 is for adding proper support. I've already done some initial investigation on it and I think I can get it working with our liberty project type with a few changes in pfe. I'll take a stab at it tomorrow.

**Comment by rajivnathan** [comment]
After doing some digging I found that the project type detection code in Turbine is not being used. The project type detection code is in the initialize container which is called by portal code so I'll move this over to the portal area.

**Investigation details**
Project detection code is here:
https://github.com/eclipse/codewind/blob/e78feedc913500f39ac3a1e1f0dde729dbc69067/src/initialize/src/controllers/typeDetectionController.ts#L39

The logic selects the `liberty` type if the pom.xml contains `<groupId>org.eclipse.microprofile</groupId>`. Both the liberty microprofile template and the open liberty template pull in that dependency except the open liberty template is created with `docker` project type instead of `liberty`. But when the project is imported again the type detection code (linked above) will detect it as `liberty` and it will fail to build. However, the user can choose to override the type and select `Other` which maps to the docker project type and things then work but this is not a great user experience because it's not obvious at all that they would need to do that.

One way we could possibly resolve it for this release is to add a specific type property to the open liberty template's pom.xml. eg. `<codewind.type>generic-docker</codewind.type>` and use that as a project type override. (thanks @jgwest for this suggestion) This would at least return `docker` as the type when imported.

If we do make this change the IDEs would currently prompt the user if `docker` is the returned type instead of directly using it. Not sure if that's intended behaviour. But it looks like the type detection code defaults to docker instead of unknown so there wouldn't be a way for the IDEs to distinguish between a type that is set to be a docker type vs the fallback case.
FYI @tetchel ^

**Comment by rajivnathan** [comment]
Added workaround instructions to the issue description. Given the simple workaround I don't believe this should be prioritized as stopship.

**Comment by eddie-95** [comment]
I'll take a look into this.

**Comment by ebuckle** [comment]
After a quick look, updating `typeDetectionController.ts` to check for `<groupId>com.ibm.websphere.appserver.api</groupId>` in pom.xml in addition to the current check will correctly identify liberty projects and assign the `docker` type to imported open liberty projects. So the project does not fail as above.

However, this hits another issue. While an imported open liberty project is correctly assigned `"projectType: "docker" "language":"java"`, the user is still prompted to choose their project type and language as if they had tried to use the workaround suggested above instead of it being resolved automatically. 

I'm going to attempt to replicate this with the Eclipse plugin and see if I get the same outcome.

**Comment by tetchel** [comment]
putting stopship label back so we can decide during a checkpoint

**Comment by ebuckle** [comment]
Have now recreated issue in both VSCode as well as Eclipse. Still currently using the identification method as in my previous comment but will find a better solution as per @rajivnathan 's suggestion.

As shown below, this now correctly identifies Open Liberty projects and has the correct project type and language selected in eclipse. The user simply needs to accept:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/33088613/63764348-8576af00-c8be-11e9-949d-db361d97a34d.png">

However, VSCode does not have these pre-selected and the user is still required to input the project type and language manually:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/33088613/63764545-fb7b1600-c8be-11e9-8fa3-c1fe60189119.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/33088613/63764574-0635ab00-c8bf-11e9-8dd0-bd9e615ab6d2.png">

Is this expected behavior? The project is being correctly assigned type and language but the VSCode plugin is not recognizing it.

**Comment by ebuckle** [comment]
@tetchel I think showing that dialog would be good. Feels intuitive to give the user the option to use Codewind's type detection or to disregard it and use their own, in the docker case.

**Comment by tetchel** [comment]
can this be closed?

**Comment by sishida** [comment]
If this issue is closed, does that mean we need to remove the Troubleshooting section in this PR https://github.com/eclipse/codewind-docs/pull/93/files because it is no longer relevant?

**Comment by tetchel** [comment]
it is possible for users to hit this issue if they import the project as the wrong type, so we should leave that in. I closed the issue because there is nothing further to fix
