### ISSUE TITLE
VS Code: Error initialing a build, Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#2435]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

When requesting a manual build, getting this popup in VS Code:

![image](https://user-images.githubusercontent.com/17596240/76239606-3b28a000-6208-11ea-8f43-b25e136baabd.png)

From what I can tell PFE always returned text (not JSON) https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/build.route.js#L46 but IDE now expects JSON?

**Steps to reproduce:**

**Workaround:**

**Comment by tetchel** [comment]
it is the same as https://github.com/eclipse/codewind/issues/2434

**Comment by jopit** [comment]
Rather than do this in a scattershot fashion, we should take a more consistent approach.  One possibility is to move all this function into cwctl.

This would involve producing a new version of the API, rather than replacing the existing one.

Julie will set up a discussion with TimE, Erin and JohnP to move this forward.

**Comment by tetchel** [comment]
I'm fixing it on my end since I originally thought the problem was isolated to the build endpoint, but there are several more.
