### ISSUE TITLE
Improve Codewind marketplace entry for IntelliJ

### ISSUE THREAD

**Issue by rtaniwa** [eclipse/codewind#2462]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

The IntelliJ marketplace entry for Codewind needs beefing up. 

https://plugins.jetbrains.com/plugin/13839-codewind

There isn't anything that really explains the plugin, or what value props it provides. We need to have it similar to what we have done on Eclipse and VS Code marketplaces ASAP. 

**Proposed solution:**

**Comment by jopit** [comment]
JetBrains gives the following 'guidance' for the description of a plugin:
```
<!-- Description of the plugin. 
       Should be short and to the point.
       Start the description with a verb in present simple form such as 
       "integrates", "synchronizes", "adds support for" or "lets you view".
       Don’t use marketing adjectives like “simple”, “lightweight”, or “professional”.
       Don’t repeat the name of the plugin.
       For plugins that add language/platform/framework support, the description MUST specify 
       the version of the corresponding language/platform/framework.
       Don't mention the IDE compatibility. E.g. don't say "Adds support to IntelliJ IDEA for..."
       Displayed in the "Plugins" settings dialog and the plugin repository Web interface. 
       Simple HTML elements can be included between <![CDATA[  ]]> tags.  -->
```
from here: https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html

**Comment by rtaniwa** [comment]
We may need to tweak our content to conform to these guidelines, but if you compare what we have to other examples (https://plugins.jetbrains.com/plugin/8079-cloud-code), we are very thin. :)

**Comment by sishida** [comment]
✍️I will write a draft of the text to appear on the marketplace and then post it here as a comment. Then, the IntelliJ team can update the plug-in XML file and add HTML for the formatting.

**Comment by sishida** [comment]
**Codewind**
Adds tools to help build cloud-native, containerized applications, regardless of which runtime or language you use. Create an application from a template project and launch, update, test, and debug in containers on the desktop. For more information, see https://www.eclipse.org/codewind/.

**Why use Codewind?**
- Get started with templates or samples to create and deploy applications that run in containers.
- Create containerized applications in languages and runtimes that you're already familiar with.
- Pull in your existing applications and use Codewind to help get them cloud ready.
- See code changes reflected in your containerized application.

**Features**
- Create new containerized projects or add existing ones.
- View your containerized projects, including the application and build status.
- Debug Microprofile/Java EE, Node.js, and Spring applications.
- Access application, build, and container logs in the Output view.
- See validation errors in the Problems view.
- Open a shell session into an application container.
- Toggle the project auto build setting and manually initiate project builds.
- Open your application or the application monitor in a browser.

**Getting started with Codewind**
For more information, see https://www.eclipse.org/codewind/mdteclipsegettingstarted.html.

**Contributing**
Submit issues and contributions:
- Submitting issues: https://github.com/eclipse/codewind/issues
- Contributing: https://github.com/eclipse/codewind-eclipse/blob/master/CONTRIBUTING.md

**Developing**
To develop and debug Codewind for Eclipse, see https://github.com/eclipse/codewind-eclipse/blob/master/README.md#developing-codewind-for-eclipse.

**Comment by sishida** [comment]
@jopit Hi, John, The draft is in the previous comment. Here are some things I thought might need editing:
- If Codewind for IntelliJ doesn't support everything mentioned yet, we'll of course want to remove that content. Please just let me know. :)
- Also, I wasn't sure if we needed to add info for the JetBrains guidance, `the description MUST specify the version of the corresponding language/platform/framework`. Do we need to provide more details about languages, etc. instead of just saying "regardless of which runtime or language you use"?
Thanks!
Thanks!

**Comment by jopit** [comment]
Hi @sishida, regarding the `the description MUST specify the version of the corresponding language/platform/framework` guidance, I think that Codewind itself counts as a 'framework', so somewhere we should mention that we support Codewind 0.10.0.  Also, since we only support Java in IntelliJ, I think we should remove the "regardless of which runtime or language you use"

Here's an updated version of what you wrong with the not-yet-supported stuff removed.  I've changed the links to point to the equivalent IntelliJ ones, but I'm not sure about the 'getting started' one -- is that going to change for 0.10.0?

Please do continue to wordsmith it if needed.

DRAFT:

**Codewind**
Adds tools to help build cloud-native, containerized Java applications. Create an application from a template project and launch, update, test, and debug in containers on the desktop. Supports Codewind version 0.10.0.  For more information, see https://www.eclipse.org/codewind/.

**Why use Codewind?**
- Get started with templates or samples to create and deploy applications that run in containers.
- Create containerized applications in languages and runtimes that you're already familiar with.
- Pull in your existing applications and use Codewind to help get them cloud ready.
- See code changes reflected in your containerized application.

**Features**
- Create new containerized projects or add existing ones.
- View your containerized projects, including the application and build status.
- Debug Microprofile/Java EE, and Spring applications.
- Access application, build, and container logs in the Output view.
- Toggle the project auto build setting and manually initiate project builds.
- Open your application in a browser.

**Getting started with Codewind**
For more information, see https://www.eclipse.org/codewind/mdt-intellij-getting-started.html

**Contributing**
Submit issues and contributions:
- Submitting issues: https://github.com/eclipse/codewind/issues
- Contributing: https://github.com/eclipse/codewind-intellij/blob/master/CONTRIBUTING.md

**Developing**
To develop and debug Codewind for IntelliJ, see https://github.com/eclipse/codewind-intellij#developing

**Comment by sishida** [comment]
@jopit Thanks for making changes! I've added small edits directly to the text in your comment, such as adding periods to the end of sentences and updating the `getting-started` link. All the link needed was to have the `mdt-` part removed. :)

**Comment by jopit** [comment]
@sishida can you review PR https://github.com/eclipse/codewind/issues/2462 to make sure I've captured all you updates?

**Comment by sishida** [comment]
Everything should be good to go for updating the marketplace page--we just need to wait for the changes to go live for the updates to appear. :)

**Comment by jopit** [comment]
The changes will go live when we publish an updated version of the plugin to the marketplace.

**Comment by sishida** [comment]
Link to updated marketplace entry: https://plugins.jetbrains.com/plugin/13839-codewind
