### ISSUE TITLE
Why can I use codewind only after upgraded codewind version

### ISSUE THREAD

**Issue by douzizuibang** [eclipse/codewind#2473]
There are two problem,
1. Why can I use it only after upgrading if there is new version?
  If I have not access to internet, what should I do?

2. if I have pull these image by other solution
`eclipse/codewind-performance-amd64` and `eclipse/codewind-pfe-amd64`.
But when I try to start codewind in vscode, it will still pull image.
How to set the config of codewind, if there are images in local, the pull will not be trigger when start it.

**Comment by tetchel** [comment]
The problem is that a given version of the VS Code extension (say 0.9.0) is only meant to work with the matching version of the Codewind images. It will check the image tags to make sure they match.

One thing you can do is disable auto-updating your vs code extensions, then it won't update and won't require a new image version.
![image](https://user-images.githubusercontent.com/8888438/76768252-1f297f00-6771-11ea-8050-b3c527910329.png)

Secondly, if you can pull the images ahead of time, this is supported so long as the images are tagged correctly. You can do this easily yourself with `~/.codewind/0.9.0/cwctl install --tag 0.9.0`.

**Comment by douzizuibang** [comment]
ok, thank you.
