### ISSUE TITLE
SVT: IntelliJ: Cancel button when creating project

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#2476]
**Codewind version:** 0.10
**OS:** Windows

**IDE extension version:** 0.10
**IDE version:** IntelliJ 3.11

**Description:**
![image](https://user-images.githubusercontent.com/19738071/76624898-8c88a600-650c-11ea-8a97-542b4acb038a.png)
We are not sure about what the ```Cancel``` button in this wizard is supposed to do. Is it supposed to not create the project whatsoever? Or is it supposed to create in the windows explorer so the user can import it later in the future?

Now we assume the project would not create whatsoever if that button is selected. However, if the user clicks the ```Cancel``` button, the Codewind project doesn't show up in the Codewind tree, but it shows up in the Windows Explorer instead. Also, the project will not show up even if the user right-clicks on ```Local [Running]``` and clicks ```Refresh```.

**Steps to reproduce:**
1. Create a new Codewind project of any type
2. When the ```Open Project``` wizard pops up, click the ```Cancel``` button.
3. The project does not show up in the Codewind tree, but if they open the windows explorer and go to the directory where the projects are located, they will see the new project that has been created
4. When the user right-clicks on ```Local [Running]``` and clicks ```Refresh```, the project will not show up, but it shows up in the windows explorer.

![image](https://user-images.githubusercontent.com/19738071/76625052-dbced680-650c-11ea-9e92-80674053d30a.png)

@jagraj

**Comment by malincoln** [comment]
@keithchong can you take a look?  I don't see @jopit online right now.  Thanks

**Comment by jagraj** [comment]
@jopit @keithchong 
I have been trying migration scenario from 0.9.0 to 0.10.0. Looks like this problem does exist in 0.9.0 release and not sure if this is "stopship" issue and this is not regression. I leave this decision to you, we are ok making this as "hot" as we are not loosing functionality here as user can delete manually if he does not want project or he can always import the project if needed after cancel button is pressed.

**Comment by keithchong** [comment]
Selecting cancel should not create the project.  The problem is that the project folder is indeed created but not all of the intended content is there.  For example, there is an empty src folder, and there is the IntelliJ project format folder `.idea`.

IMHO, I don't think this is stop-ship.  The user should relaunch the wizard and select the option to open the project in a new window.

The fix should consider cleaning up/removing the folder.  

The workaround without the fix is that the user should manually delete the folder.  (If the user wants to reuse the project name when recreating the project)

**Comment by jopit** [comment]
Agreed, this is not stop-ship

**Comment by naveenkaratekid** [comment]
Verified Keith's fix, and it works properly now and deletes the folder. WIll close this issue now.
