### ISSUE TITLE
Fix codewind.dev sidebar

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#2487]
Right now, the side bar has a few behaviours when clicking on the top level item

1. Clicking "What is codewind" brings you to a page, nothing is expanded
2. Clicking "Getting started" brings you to a page and the sidebar is expanded to show sub items
3. Clicking "Developing projects" expands the sub items but doesn't go to a page

I've seen other sites (like kubernetes) support scenario 3. 1 is doable in bootstrap, but 2 is the tricky situation that resulted in some "unnecessarily" complex code to handle that situation.

**Comment by jopit** [comment]
Option 3 seem like the right approach, but we need input from design.
Also, removing the animation from expanding an item might be less distracting, but we need design's input.

**Comment by markcor11** [comment]
I like option 3 over option 2.  I find it easier to scan down the list clicking / expanding / collapsing whilst I'm hunting for the right section to launch. That happens without the added flicker of the right hand frame changing when I didn't notice that the grey section was a link rather than an expander box.

**Comment by jcockbain** [comment]
@sghung - has this been resolved by https://github.com/eclipse/codewind-docs/pull/498?

**Comment by sghung** [comment]
Yes @jcockbain it has been, let me close it
