### ISSUE TITLE
Document keychain usage with codewind

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2563]
with #2520 and https://github.com/eclipse/codewind/issues/1306, local users will now have to use a [keychain](https://askubuntu.com/a/1719) (aka keyring) too, or use the new insecure keychain, or have cwctl crash (!) when certain commands are used.

We should document the following:
1. what systems come with a keychain by default?
2. if I don't have a keychain, how do I install one?
2. what codewind features need a keychain?
3. why do these features need a keychain?
4. what is the insecure keychain?
5. how do you enable the insecure keychain?

**Comment by tetchel** [comment]
1. Windows 10, Mac and some Linux systems (installations including the `gnome-keyring` package) come with a keyring out-of-the-box. 
2. On linux, you can install https://wiki.archlinux.org/index.php/GNOME/Keyring. You can use any keyring compatible with [go-keyring](https://github.com/zalando/go-keyring), which is what Codewind uses internally.
3. Not certain about this one. The following definitely require one:
- Accessing a remote connection. Creating a remote connection using `cwctl` does not require one, but to connect to it from an IDE you do need a keychain.
- Adding Image Registries to your local codewind connection
- (?) Right now starting local codewind also requires one, or it crashes. But as part of #2520 this requirement should be removed. I'm not sure if we will get that fix for 0.11, though.
4. These features need to store your password to your image registries, or to your Codewind instance. Keychains allow Codewind to store your passwords securely, encrypted on your disk.
5. If you absolutely cannot install a keychain, you can enable "insecure keychain" mode. If this is enabled, your credentials are instead stored in a text (JSON) file in the `.codewind` directory under your user home directory. The credentials are base64 encoded, which anyone with access to that file could decode.
6. Enable insecure keyring mode in the IDEs through the IDE preferences. If using cwctl directly, you can use the `--insecure-keyring` command-line argument, or set `INSECURE_KEYRING=true` in the environment.

**Comment by tetchel** [comment]
It looks like there is a small mention of keyrings in the documentation already added in https://github.com/eclipse/codewind-docs/pull/289

**Comment by hhellyer** [comment]
I think this is probably more information than is needed. We probably don't want to document this in the main docs just the troubleshooting guide.

I suspect it's going to be very rare that a 'real' user needs to do anything about this. A normal Mac or Windows or Linux desktop will have a keychain or be pretty broken. A "normal" desktop will come with a keychain so documenting it as a separate requirement might not make sense.

@jgwest raised the original issue: https://github.com/eclipse/codewind/issues/1735 so it might be worth checking with him what his environment was and how realistic it was and whether he thinks normal users are likely to hit this. I suspect Linux is the only environment where you could fail to have a keychain so documenting it for Mac and Windows probably doesn't make sense.

AFAIK we only implemented the insecure keychain to help with a narrow use case where someone is installing Codewind into quite an unusual environment (I think Theia was involved, inside a pod in kube) and I don't think they were following any of our other installation guides to do that work so we probably shouldn't add to the installation docs. (As a bonus it also lets us use `cwctl` inside Jenkins, which is lucky, because our Jenkins image isn't a full desktop Linux image.) 

There might be some other history I don't know about and I'm not a Linux desktop expert but assuming the above I think we should mention somewhere that the option to use an insecure keychain exists but we I'm not sure we need to have have this in our setup guides for normal users.

I think a short entry in the troubleshooting section mentioning the error, why it occurs and what you might want to do about it *if* you happen to be working in a limited desktop environment that doesn't have a keychain is probably sufficient. We can include how to force the IDE to use it if there's a way to do so, I don't know if all our IDE's would be expected to run in that kind of environment either. A normal user is unlikely to need this and if we start talking about keychains in our installation guide it's just going to get in the way and scare people of. @jgwest might have a better idea of how frequently this is going to come up though and I'm happy to defer to him if he knows better!

**Comment by tetchel** [comment]
Any user using a headless linux environment or _many_ linux distributions which don't include `gnome-keyring` will hit this problem so I think at least 2) 5) and 6) need to be documented for those users

**Comment by hhellyer** [comment]
I think the logical questions are:
- Do we document or support using a headless Linux environment? (I'm not sure we document how to use cwctl manually as an end user.)
- Do Eclipse/VSCode/IntelliJ (our supported editors) support those Linux distributions?

As an aside, starting an editor from a terminal where `INSECURE_KEYRING` is set might be sufficient. Do the editors need to have a preference for this?

(I'm being cautious because we want our docs to be clear and not filled up with work arounds for corner cases.)

**Comment by tetchel** [comment]
> Do we document or support using a headless Linux environment? (I'm not sure we document how to use cwctl manually as an end user.)
> Do Eclipse/VSCode/IntelliJ (our supported editors) support those Linux distributions?

I am much more concerned about the non-gnome-linux distros than the headless ones. The IDEs do support those.

And, whether or not we 'support' cwctl directly we see from Jonathan's issue (and bsteinfeld's participation) that people are using it - and my impression was we do plan to support it on its own one day even if it's not well supported right now

**Comment by hhellyer** [comment]
Ok, so long as we actually do have environments where the user won't have a keychain. (Although as it's insecure we might suggest installing a keychain is a better option!)

Where do you stand on including it in the main docs or the troubleshooting?
https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html
That would be enough to make it googleable which is probably the first place anyone will turn.

**Comment by tetchel** [comment]
Yes I agree installing a keychain >> using the insecure keychain, item #2

I think the troubleshooting for sure should have it, we already have some mention of keychain from I think the troubleshooting from https://github.com/eclipse/codewind-docs/pull/289/files so we could expand that section and have the troubleshooting link to it

**Comment by jgwest** [comment]
Sounds like y'all are on the same page, but since I was @-ed I thought I would put in my two cents re: prevalence.

The original issue will occur with any Linux environment that does not have their distro's desktop packages installed. This includes the Ubuntu 18.04 LTS Server Edition (and presumably RH distro equivalents), which would be the most common distribution running on servers/VMs (rather than laptops/desktops).

Most Linux Desktop users (the few and the proud) would be on the desktop edition of their OS, but you can imagine that there would also be folks administering or interacting with Codewind from a server/VM host as well (which is how I hit this).

As an example, the Ubuntu 18.04 image on Fyre is the server edition, and thus anyone using that would hit this issue. Likewise it is unfortunately not just a matter of "installing the desktop packages" into the server edition, as I have found the keyring daemon does not get properly associated with the login session (some workarounds exist, see original issue).

**Comment by tetchel** [comment]
ok, if the keychainless systems are only headless (desktop-less) systems, that changes this somewhat, because those systems won't support any graphical IDE. So the only proper use-case for insecure keychain is using cwctl on its own. 

That makes me think we don't have to support this form the IDEs.

**Comment by tetchel** [comment]
(but, to be clear, I still think we should document 5) and 6) and briefly mention 1) and 2) )

**Comment by sishida** [comment]
Talked with Michael today. He talks about keyrings in the `remotedeploy-codewind` topic. Put in Developing Projects for now. Consult with Mel later to make sure it fits with the user journey.

**Comment by sishida** [comment]
Link to updated troubleshooting section on the website: https://www.eclipse.org/codewind/troubleshooting.html#without-a-keychain-or-keyring-codewind-fails-to-run-certain-commands

Closing this issue.
