### ISSUE TITLE
Cwctl doesn't clean up keychain

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2584]
I have over 250 saved credentials in the keychain, matching `org.eclipse.codewind.<connection ID>`. Obviously I'll have way more than a real user, but when I remove a connection, it should delete the keychain entry too.

**Comment by markcor11** [comment]
That is correct - we don't delete secrets from the platform keychain (and we shouldn't expose that ability from cwctl because else badapp.sh could ping cwctl and ask us to wipe out keychain entries from our trusted process). However,  we could remove the secrets related to a connection at the time the connection is deleted.

**Comment by markcor11** [comment]
fixes merged into master 

/pipeline verify
