### ISSUE TITLE
cwctl attempts to 'docker login' in Che and fails

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2597]
![image](https://user-images.githubusercontent.com/8888438/78197552-aeae7d80-7453-11ea-8822-558b116dfbef.png)

```
==> Run cwctl --json --insecure registrysecrets add --conid local --address docker.io --username timetchells --password *********
{"error":"DOCKER_CREDENTIAL_ERROR","error_description":"exec: \"docker\": executable file not found in $PATH"}
==> End cwctl --json --insecure registrysecrets add --conid local --address docker.io --username timetchells --password *********
```

There's no need to run `docker login` in Che. This step should be skipped

**Comment by tetchel** [comment]
It should be an easy fix but this is stopship because now I can't add registry secrets which means I can't create Codewind-style projects

**Comment by hhellyer** [comment]
PR's raised for master and 0.11.0:
https://github.com/eclipse/codewind-installer/pull/423
https://github.com/eclipse/codewind-installer/pull/424

Just need review/merge.

**Comment by tetchel** [comment]
I still see the problem;

```
bash-4.4$ sha1sum ~/.codewind/latest/cwctl 
01318056d3190e931cc2cf9337d0fbab2ba134b9  /home/theia/.codewind/latest/cwctl
bash-4.4$ cwctl --json --insecure registrysecrets add --conid local --address docker.io --username timetchells --password abcdefg
bash: cwctl: command not found
bash-4.4$ ~/.codewind/latest/cwctl --json --insecure registrysecrets add --conid local --address docker.io --username timetchells --password abcdefg
{"error":"DOCKER_CREDENTIAL_ERROR","error_description":"{\"error\":\"sec_keyring\",\"error_description\":\"exec: \\\"dbus-launch\\\": executable file not found in $PATH\"}"}
```

That executable is from Jenkins build 71 which contains the fix.
```
# Build date: 2020-04-03-07:50:52
build_info.url=https://download.eclipse.org/codewind/codewind-installer/master/71
build_info.linux.SHA-1=01318056d3190e931cc2cf9337d0fbab2ba134b9
```

**Comment by hhellyer** [comment]
@tetchel - I think this is a different error message, the fix resovles:
`{"error":"DOCKER_CREDENTIAL_ERROR","error_description":"exec: \"docker\": executable file not found in $PATH"}`
The error you are seeing now: 
`{"error":"DOCKER_CREDENTIAL_ERROR","error_description":"{\"error\":\"sec_keyring\",\"error_description\":\"exec: \\\"dbus-launch\\\": executable file not found in $PATH\"}"}`
is because there is no keyring available. You need to run with the insecure keyring enabled either:
`~/.codewind/latest/cwctl --json --insecureKeyring --insecure registrysecrets add --conid local --address docker.io --username timetchells --password abcdefg`
or set `INSECURE_KEYRING=true` before running cwctl.

**Comment by tetchel** [comment]
right, ok

**Comment by hhellyer** [comment]
If it's just in Che can we add the env var to the set for the container? (Which makes sense as not having a keyring is a property of the container.)

**Comment by tetchel** [comment]
I would prefer that to adding `--insecure-keyring` to every cwctl command I run in Che, let me see

**Comment by tetchel** [comment]
Fixed 👍
