### ISSUE TITLE
codewind remote projects 'Connection Lost' after a number of hours

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind#2640]
**Codewind version:**   0.10
**OS:**      MacOS

**Che version:**
**IDE extension version:**  0.10
**IDE version:**    1.43.2
**Kubernetes cluster:**.  Openshift 43 and Kubernetes

**Description:**
After a period of time idle (multiple hours) I have been noticing my vscode remote codewind(s) reporting as "connection lost".   In my example (image) I can see two links are lost.

Clicking refresh on the connection brings connections and projects back almost instantly.   

I would not expect to have to manually re-establish the remote server connections

![Screenshot 2020-04-08 at 18 18 00](https://user-images.githubusercontent.com/9268814/78813807-7b28a180-79c5-11ea-8bab-4dc42cf73142.png)

**Steps to reproduce:**

using visualstudio code and connecting to a remote codewind instances (I am using IBM public cloud)  clusters

**Workaround:** 

manual refresh brings links back

**Comment by sujeilyfonseca** [comment]
**Codewind version:** 0.9.0
**OS:** MacOS

IDE extension version: 0.9.0
IDE version: 1.44.0

I just encountered the same issue, but not after a couple of hours. I installed Codewind 0.9.0 on VS Code because I wanted to perform a migration scenario. I created several projects, and suddenly the connection was lost: 

<img width="1669" alt="Screen Shot 2020-04-13 at 2 23 53 PM" src="https://user-images.githubusercontent.com/49531960/79148860-39687400-7d94-11ea-9377-e278f58e80c8.png">

I tried a refresh, but it didn't work:

<img width="1669" alt="Screen Shot 2020-04-13 at 2 25 42 PM" src="https://user-images.githubusercontent.com/49531960/79148867-3c636480-7d94-11ea-8578-8f5618724c08.png">

I verified the running pods, and the `codewind-pfe` was no longer running:

```
(base) Sujeilys-MBP:IBM.codewind sfonseca$ docker ps
CONTAINER ID        IMAGE                                                     COMMAND             CREATED             STATUS              PORTS                       NAMES
e9895c9fe0f4        cw-cwdefaultpython-c1732160-7db2-11ea-b3c6-e746faddb2be   "python app.py"     13 minutes ago      Up 13 minutes       127.0.0.1:32776->5000/tcp   cw-cwdefaultpython-c1732160-7db2-11ea-b3c6-e746faddb2be
f23fc0102afc        eclipse/codewind-performance-amd64:0.9.0                  "npm start"         21 minutes ago      Up 21 minutes       127.0.0.1:9095->9095/tcp    codewind-performance
```

Here are my logs:

[codewind.log](https://github.com/eclipse/codewind/files/4471159/codewind.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4471160/codewind-pfe.txt)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/4471161/filewatcherd-1.log)

**Comment by jgwest** [comment]
Looks like PFE container died with this message:
```
[13/04/20 18:23:22 /portal/modules/LoadRunner.js] [INFO] Loadrunner has disconnected
/portal/modules/LoadRunner.js:428
      this.project.loadInProgress = false; 
                                  ^

TypeError: Cannot set property 'loadInProgress' of null
    at Socket.socket.on (/portal/modules/LoadRunner.js:428:35)
    at Socket.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/portal/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onclose (/portal/node_modules/socket.io-client/lib/socket.js:214:8)
    at Manager.<anonymous> (/portal/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Manager.onclose (/portal/node_modules/socket.io-client/lib/manager.js:502:8)
    at Socket.<anonymous> (/portal/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/portal/node_modules/component-emitter/index.js:133:20)
    at Socket.onClose (/portal/node_modules/engine.io-client/lib/socket.js:725:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codewind-portal@1.0.0 prod: `node server.js`
npm ERR! Exit status 1
```

**Comment by AndyRWatson** [comment]
@sujeilyfonseca  @jgwest that maybe a different issue as I had no traffic / activity to loose the connection, and this PFE error looks to be associated with  LoadRunner

**Comment by sujeilyfonseca** [comment]
Ok. Thanks, @AndyRWatson and @jgwest! I'll proceed to open a different issue.

**Comment by tetchel** [comment]
New reconnect behaviour:

After a remote connection is lost, a timer starts which will periodically try and reconnect to the disconnected Codewind instance. 

The first reconnect will occur after 2s, then 4s, then 8s, etc, up to a maximum of 90s. 

If the maximum period is reached, a warning is shown to the user that the tools are failing to reconnect, and they should likely disable the broken connection.
