### ISSUE TITLE
SVT: Load run status stuck in "Running" state and I can not submit any load run tests for other projects

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#2659]
**Codewind version:** Codewind  0.11
**OS:**  Core OS

**Che version:**  7.9.2
**IDE extension version:**  Codewind 0.11
**IDE version:**  Theia 7.9.2
**Kubernetes cluster:**
OCP 4.3

**Description:**
I tried to run load test for Open Liberty after injecting metrics and it started fine but got it stuck at "Running" state even though it completed the test. I tried to submit another load test after 5 mins for WebSphere liberty project and the error says "500 Bad request" and after that I always get another load test is in progress for any other project. Looks like user is completely blocked at this point that he can not use load run feature from "performance metrics" dashboard.

![image](https://user-images.githubusercontent.com/713849/78935245-61956180-7a7a-11ea-82ea-afcbdd65f809.png)

![image](https://user-images.githubusercontent.com/713849/78935346-930e2d00-7a7a-11ea-81c2-55fc940778c7.png)

Logs 
[performance.txt](https://github.com/eclipse/codewind/files/4458366/performance.txt)
[pfe.txt](https://github.com/eclipse/codewind/files/4458367/pfe.txt)

**Steps to reproduce:**
1. Create WebSphere liberty project.
2. Let it build and come to running state.
3. Create another Open liberty project.
4. Let it build and come to running state.
5. Inject metrics for open liberty project.
6. Open performance dashboard for WebSphere liberty and submit load test.
7. Wait for 3 mins to complete the load run.
8. It does not come back to "Run Load Test" status and it gets stuck at "Running" state.
9. Try to submit another load test for Open liberty and then user always gets message saying "Another load test is in progress" . But at the first time we get message saying "500 Bad request" error.

**Workaround:** 

@sujeilyfonseca

**Comment by malincoln** [comment]
@tobespc pls assign. Thanks

**Comment by sujeilyfonseca** [comment]
**Codewind version:** 0.11.0
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.9.0
**Kubernetes cluster:** Fyre Cluster with OCP 4.3

I reproduced the same scenario when I was performing tests. I created some projects and waited for a "Running" status. After that, I successfully executed load tests with projects, such as MicroProfile and Swift. Then, I proceeded to start a load test with a Default Open Liberty project. The UI presented the status stuck in "Running". I waited for a while, and nothing happened. Then, I refreshed my browser, but it didn't work. 

Since then, I have not been able to execute any additional load tests. They present a 500 error or the error saying that another test is in progress.

<img width="1676" alt="Screen Shot 2020-04-09 at 2 31 31 PM" src="https://user-images.githubusercontent.com/49531960/78940451-dcaf4580-7a83-11ea-8318-290c1c678b6f.png">

<img width="1676" alt="Screen Shot 2020-04-09 at 12 26 21 PM" src="https://user-images.githubusercontent.com/49531960/78940488-ed5fbb80-7a83-11ea-9a78-469121a29fc5.png">

<img width="1674" alt="Screen Shot 2020-04-09 at 12 26 44 PM" src="https://user-images.githubusercontent.com/49531960/78940490-ee90e880-7a83-11ea-9eb6-4faf883066bd.png">

<img width="839" alt="Screen Shot 2020-04-09 at 2 29 34 PM" src="https://user-images.githubusercontent.com/49531960/78940385-bf7a7700-7a83-11ea-8a5d-95cf08322cab.png">

<img width="1664" alt="Screen Shot 2020-04-09 at 12 46 48 PM" src="https://user-images.githubusercontent.com/49531960/78940318-a4a80280-7a83-11ea-9e7e-b51d6765e25f.png">

<img width="1672" alt="Screen Shot 2020-04-09 at 12 30 36 PM" src="https://user-images.githubusercontent.com/49531960/78940345-af629780-7a83-11ea-8091-52ca4abff909.png">

<img width="1668" alt="Screen Shot 2020-04-09 at 12 46 33 PM" src="https://user-images.githubusercontent.com/49531960/78940330-a8d42000-7a83-11ea-9f5d-21f3c6aa97b2.png">

[codewind-workspacezj0ntdg6f5k5v6l2-b664b76b5-fkqqf.txt](https://github.com/eclipse/codewind/files/4458635/codewind-workspacezj0ntdg6f5k5v6l2-b664b76b5-fkqqf.txt)

**Comment by tobespc** [comment]
@markcor11 Can you pick this up please

**Comment by tobespc** [comment]
Did you see the message about "collecting" appear ?

**Comment by tobespc** [comment]
This should be now be fixed with the changes made to 0.11.0, please retest

**Comment by jagraj** [comment]
Latest fix looks good on Che, we would like to verify on remote once and close this. This is looking good on Che and it is stable. Thanks for all your help in fixing this issue.

**Comment by sujeilyfonseca** [comment]
@jagraj, I verified this issue on local, remote/hybrid, and che scenarios. Everything looked good. I couldn't reproduce the problem.

**Comment by jagraj** [comment]
Excellent, Thanks @sujeilyfonseca . I am closing this issue now. Thanks again to @tobespc and @markcor11 addressing this issue.
