### ISSUE TITLE
SVT: [VS Code] Command Palette got stuck listing projects after my remote connection refreshes automatically

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2663]
**Codewind version:** 0.11.0
**OS:** VM with Windows 10 (w. OKD/Openshift cluster)

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** Command Palette got stuck listing projects after my remote connection refreshes automatically

![vscode-command-palette](https://user-images.githubusercontent.com/49531960/78947311-fc019f00-7a92-11ea-80c8-79a24b781c4e.gif)

**Steps to reproduce:**
1. Install and start Codewind 0.11.0
2. Use the recently installed 0.11.0 cwctl to deploy Codewind remotely
3. Create a new remote connection
4. Create a new image registry
5. Create a project
6. Attempt to create another project
7. Command Palette will be stuck when listing the project types options
8. User will not be allowed to select an option

**Workaround:**
Press `ESC` and start the project creation again.

@jagraj

**Comment by tetchel** [comment]
ok, this is a weird one. the problem occurs only if that if the first project finishes creating _while_ you are creating the second project (ie, not before).

1. create first project
2. open create project wizard for second project
3. first project finishes creating
  - codewind extension automatically adds the new project's folder to the workspace
4. VS Code refreshes the workspace because of the new workspace folder 
5. The instance of the extension which owns the currently open Create Project wizard gets disposed, because the workspace is being refreshed. But surprisingly, the Create Project quickpick is **not** disposed!
6. You now have this 'marooned' quickpick which does not work properly because the extension which owns the quickpick has been disposed.

I'm not certain I can fix this, but I will try

**Comment by tetchel** [comment]
I looked into this and I am closing it as wontfix because it takes a perfect storm to have it occur, and the workaround is to just press ESC and start the create over again.
