### ISSUE TITLE
Allow configuring the Docker network that Codewind containers should join

### ISSUE THREAD

**Issue by chilanti** [eclipse/codewind#2711]
**Codewind version:** Any
**OS:** Any

**Description of the enhancement:**

We'd like to be able to configure the Docker network name that containers join - right now, this value seems to be hardcoded to `codewind_network`. 

**Proposed solution:** 

There are two approaches: 
1) Make the default Docker network - now `codewind_network` - a configurable parameter. This may require modifying code paths where this value is hardcoded. 
2) Allow the user to configure an **additional** network (or networks) the containers should join. This approach would leave the existing code paths intact, and would require Codewind to perform an additional step by calling `docker network connect` once the container is created.

**Comment by makandre** [comment]
Spoke with @chilanti to get some context.  He's working on an Appsody stack that needs to communicate with a Fabric test env running in a different docker network.

I think the 2nd approach is preferred as it can be scoped to affect individual Appsody projects (1st approach would affect all projects running in Codewind).  It is also more useful since we can make it join one or more additional networks.

I'm told that we are going to have a set of env vars (defined in `env.properties`) in order to connect to the Fabric test env.  So I think we can add a var there to specify the additional networks.

/area appsody

**Comment by sghung** [comment]
I confirmed with Michele that it is okay to have this ready for May 27 (0.13.0 DCUT). He would like a preview beforehand in May. I believe we can commit to something after the 0.12.0 April 29th DCUT

**Comment by micgibso** [comment]
@makandre I see this is pencilled in for 0.13.0, what doc changes are likely to be required? The only place we mention `codewind_network` at the moment is in the Troubleshooting.

**Comment by makandre** [comment]
@micgibso We want to document that users can set `CW_NETWORKS` env var for appsody projects. Perhaps where we talk about setting environment variables for appsody? https://www.eclipse.org/codewind/importing-existing-projects.html#defining-environment-variables-for-appsody-projects

Although that section itself is somewhat hidden.

**Comment by j-c-berger** [comment]
@micgibso, I'm happy to take this on, thanks!

**Comment by micgibso** [comment]
PR reviewed and approved, closing.
