### ISSUE TITLE
Diagnostics: Enhance must gather script to collect info for all connections

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#2767]
**Description of the enhancement:**
Must gather diagnostic command takes a connection id but this isn't something a user would necessarily have to hand. We should give an option that doesn't take an id and collects data for all connections. It could make a folder for each connection.

**Comment by mattcolegate** [comment]
I've coded in the option to supply Connection ID or Connection Label, which is the name of the remote connection the user sees in the IDE, so I need to make that clearer in the usage, but the `--all` option is a good suggestion and other commands also do that. As no remote mustgather work has currently made it to the codebase yet, this work will be blocked behind that.
/assign

**Comment by mattcolegate** [comment]
/area docs
Will add a `--all/-a` flag to the `diagnostics` command

**Comment by mattcolegate** [comment]
@stalleyj has found that the code currently in https://github.com/eclipse/codewind-installer/pull/462 does not work correctly if Docker is not running - it simply fails with an error. This is because the HandleDockerError functions I've been using require one to exit after issuing them, otherwise you end up with multiple JSON output (issue #2815 ). In order to fix this efficently, I'll need the PR for that defect https://github.com/eclipse/codewind-installer/pull/464 to merge before fixing this problem, so this issue is now Blocked.

**Comment by mattcolegate** [comment]
/pipeline In Progress
(as per @tobespc request)

**Comment by mattcolegate** [comment]
https://github.com/eclipse/codewind-installer/pull/464 has now been merged - continuing work on this issue

**Comment by mattcolegate** [comment]
Updates pushed to https://github.com/eclipse/codewind-installer/pull/462 - ready for re-review

**Comment by mattcolegate** [comment]
Awaiting PR review

**Comment by mattcolegate** [comment]
Requested changes made and pushed to PR - awaiting PR review

**Comment by mattcolegate** [comment]
PR merged
/pipeline verify
