### ISSUE TITLE
Extra space above linked section

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2771]
https://www.eclipse.org/codewind/project-settings.html#health-check-endpoint

![image](https://user-images.githubusercontent.com/8888438/80509163-04891f00-8947-11ea-8cd9-cf64c55f65fa.png)

**Comment by sishida** [comment]
Hmmm...When I look at the page, the extra space appears between "Context root" and "Health check endpoint" (instead of between "Health check endpoint" and "HTTPS application" like in Tim's screenshot).
<img width="819" alt="Screen Shot 2020-04-28 at 1 02 41 PM" src="https://user-images.githubusercontent.com/21180723/80515844-95b0c380-8950-11ea-8761-451e42ff44be.png">

Also, when I look at the Markdown file in GitHub (https://github.com/eclipse/codewind-docs/edit/master/docs/_documentations/project-settings.md), there's only one empty line between sections.

**Comment by tetchel** [comment]
it moved! 
![image](https://user-images.githubusercontent.com/8888438/80516316-48812180-8951-11ea-9d01-2a3e9ffaf0ce.png)

**Comment by tetchel** [comment]
Also, if I specifically open https://www.eclipse.org/codewind/project-settings.html (no header fragment) there's no extra space at all! so the problem is caused by the fragment

**Comment by tetchel** [comment]
Reproducible on all pages

![image](https://user-images.githubusercontent.com/8888438/80516774-fbea1600-8951-11ea-8d02-13330b399516.png)

![image](https://user-images.githubusercontent.com/8888438/80516781-fdb3d980-8951-11ea-816e-f5b9e42f9994.png)

**Comment by sghung** [comment]
The box is caused by https://github.com/eclipse/codewind-docs/commit/650695d966ff90d435542208f4bf821806edb454#diff-005d9ddd47d7e97a92c07d6e12eefe66

The 
```
:target:before {
    content: "";
    display: block;
    margin-top: -115x;
    height: 115px;
    width: 1px;
}
```

Is causing that huge spacing. If you inspect the codewind source, it is adding ::before to the header, which causes that huge block. If i remove `:target:before` the spacing is gone.

We'd have to see why that was added there (that change was made by Travis) and see what the impact is if it is removed.

**Comment by jcockbain** [comment]
Based on the description of the PR https://github.com/eclipse/codewind-docs/pull/149, seems that was the workaround to stop the navbar covering the anchor link.

Taking out that block does fix the spacing issue but for me the navbar then covers the anchor in question.

**Comment by jcockbain** [comment]
`margin-top: -115x` seems to be the culprit (x rather than px).
