### ISSUE TITLE
Provide ability to run load concurrently against multiple projects

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#2825]
Current design of load run only allows one project to be tested at a time.  We want to enable multiple projects to be tested concurrently (especially when using a remote connection and testing on a cloud)

**Comment by ebuckle** [comment]
As it currently stands, the design of LoadRunner is as follows:
- User.js creates a single LoadRunner object that it calls whenever a request for load from a project is made
- This LoadRunner can only hold a single Project object and considers itself to be 'in use' if it's project object is not null
- Once load is finished, this object is nulled and a new project can then request a load run

In the new design:
- Instead of a single LoadRunner object being held by User.js, each project object that gets created will make it's own LoadRunner object
- Instead of telling LoadRunner to perform a load, User.js now tells the project to start load on its own LoadRunner object
- This LoadRunner now has a status object and will now only reject load requests if there is already one in progress for it's parent project
- This allows multiple load requests to be made at once, from separate projects

The main issues that will need to be tested are:
- Whether we can maintain the reliability of LoadRunner when running load runs in series
- The limits of running load tests in series. How many tests we can expect a user to run at once before we hit a reasonable limit

**Comment by micgibso** [comment]
We don't mention any restrictions about running load tests concurrently so no doc updates required.
