### ISSUE TITLE
Doc does not reflect in nav bar

### ISSUE THREAD

**Issue by jasperchui** [eclipse/codewind#2883]
**Description:**
From this page (https://www.eclipse.org/codewind/remotedeploy-eclipse.html) When you select this link (use Codewind remotely to build and run projects in your cloud) the page (https://www.eclipse.org/codewind/remotedeploy-projects.html) does not reflect in the side nav bar.

<img width="800" alt="Screen Shot 2020-05-08 at 09 13 47" src="https://user-images.githubusercontent.com/11577597/81408977-3e5ae200-910c-11ea-80b2-7f1e26d355f6.png">

**Comment by sishida** [comment]
@micgibso, @melhopper, I do not see `remotedeploy-projects` in the `docstoc` file (https://github.com/eclipse/codewind-docs/blob/master/docs/_data/docstoc.yml). However, I do see the `remotedeploy-projects-vscode` file there.

Should the link in `remotedeploy-eclipse` go to `remotedeploy-projects-vscode` instead? Thanks!

**Comment by jasperchui** [comment]
Also this page shows VScode but I got to it from the eclipse page.  Should there be an eclipse version?

**Comment by MelHopper** [comment]
Hi @sishida @jasperchui this has been raised as a bug a few weeks ago https://github.com/eclipse/codewind/issues/2360 This is the Github issue I suggested Jake pick up last week - it is a high priority issue.

**Comment by jasperchui** [comment]
What about "Also this page shows VScode but I got to it from the eclipse page. Should there be an eclipse version?" is that part of the bug? @MelHopper  Thanks.

**Comment by MelHopper** [comment]
@jasperchui the issue we have is that the remotedeploy-project topic contains vs-code screenshots, so we cannot simply reinstate this whilst we await creation of an eclipse-specific topic with screenshots for the eclipse user flow via #2360.

However, we can for now change that link located in remotedeploy-eclipse so that it links to remotedeploy-projects-vscode.md, so that at least it appears in the LH nav, as proposed by @sishida 

@sishida:  ID could action #2360 now by following instructions in that defect, but just deliver eclipse-specific screenshots at a later date in order to do a quick workaround whilst awaiting the Eclipse screenshots from development...? It would be good to get this bug fixed soon.

**Comment by sishida** [comment]
It sounds like thee work for this issue is covered by issue https://github.com/eclipse/codewind/issues/2360. I'll bring this up to the docs team. I think we can close this issue.
