### ISSUE TITLE
Automatically run the ODO Extension setup script

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#3002]
**Description of the enhancement:**

As a user who had deployed Codewind and just wanted to create a project it was confusing when my ODO type project failed to build for unknown reasons.

After going through the PFE logs I asked @tobespc and he explained that when using the [ODO extension in Kubernetes](https://github.com/eclipse/codewind-odo-extension) we have to run a `setup` script to create a `cluster role` and a `role binding`. Though the error message from Codewind gave no indication that I had missed a step in setup, just that the project failed to build.

I understand that this is documented here: https://www.eclipse.org/codewind/che-odo-support.html ([is ODO extension just for Eclipse Che?](https://github.com/eclipse/codewind/issues/3003))

**Proposed solution:** 

Although ODO is technically an extension, it's installed by default so imo we should automate the running of the setup script in PFE or as part of the Operator deployment. (Perhaps the first time an ODO style project is deployed?).

**Comment by johnmcollier** [comment]
Be careful here, the script needs to be run by a user/service account that already has those roles (such as a cluster admin). You won’t be able to run it by default within PFE, as PFE doesn’t have those roles.

The roles could just be added to the PFE roles created by the operator.

**Comment by james-wallis** [comment]
To add the roles to the operator I think we need to take the values from [the odo cluster roles](https://github.com/eclipse/codewind-odo-extension/blob/master/setup/codewind-odoclusterrole.yaml) and add them to [the operator cluster roles](https://github.com/eclipse/codewind-operator/blob/master/deploy/cluster_roles.yaml)(and remove any duplicates).

**Comment by markcor11** [comment]
Not quite, as @johnmcollier said, if Codewind needs those roles we will need to add them into both the cluster roles for Codewind eg: `eclipse-codewind-0.12.0` so that the rolebinding installed the codewind namespace can link them up to the Codewind service account.  

AND, 

Since the operator is issuing those roles out, it itself needs to be granted permission to do that which is controlled by the cluster role `codewind-operator-cluster` 

I'll make the diff changes to both which quickly eyeballing seems to be project.openshift.io, image.openshift.io, apps.openshift.io and an additional verb on openshift routes.

/assign @markcor11

**Comment by markcor11** [comment]
I've had a look through the ODO docs and I think since these are cluster level roles it might be better to incorporate these changes the same way we handle the Tekton cluster roles.

**Comment by james-wallis** [comment]
Have tested, able to create an odo type project without needing to run the setup scripts.
