### ISSUE TITLE
Is the ODO extension only for Eclipse Che?

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#3003]
**Description:**

Should the ODO extension only be run on Eclipse Che?

I'm running a remote Codewind deployment (non-eclipse che and deployed through the operator) and the ODO project types are showing up. I've created an ODO Node.js application and it seems to work fine.

Not sure if I've missed a page but the docs suggest that ODO project types are only available on Che.

Either:
1. PFE should not be showing the ODO templates when not in an Eclipse Che environment.
2. The Docs should move the ODO information to the `developing projects` section, almost like [Appsody](https://www.eclipse.org/codewind/importing-existing-projects.html#appsody-projects) but I think ODO could stay as its own page. They are currently under the [Eclipse Che section](https://www.eclipse.org/codewind/che-odo-support.html).
Maybe we should move `che-odo-support` under the `developing projects` section anyway?

**Comment by tetchel** [comment]
It's not for Che only, though it was when it was introduced (Before we had remote support).

@jingfuwang @sishida

**Comment by GeekArthur** [comment]
ODO extension supports both Che and Remote now, we should update the corresponding docs.

**Comment by sishida** [comment]
I have opened a PR to move the odo file under "Developing projects."

**Comment by sishida** [comment]
@james-wallis With merging these two PRs, I think this issue is good to close, correct? Please let me know if there's anything else you'd like to include. If not, I will close the issue! Thank you!
1️⃣ Moving the odo file in the table of contents: https://github.com/eclipse/codewind-docs/pull/616
2️⃣ Adding odo compatibility info: https://github.com/eclipse/codewind-docs/pull/620

**Comment by james-wallis** [comment]
Thanks for the changes @sishida
