### ISSUE TITLE
Openshift templates not available

### ISSUE THREAD

**Issue by markcor11** [eclipse/codewind#3133]
**Codewind version:** latest 
**Kubernetes cluster:** Openshift 4.11

**Description:**

When creating a new project and searching for the Openshift templates they do not appear in the list even though the Openshift template repo is enabled. 

**Steps to reproduce:**

Create a new remote deployment
Create a connection to it from the IDE
Create a new project and search for template filtering by "openshift" 
Notice no openshift templates appear

This seems to happen more often than not on cloud clusters using remote storage so could be timing related.

Error seen in PFE log : 

```
[12/06/20 13:28:38 Templates.js] [WARN] Error accessing template repository 'file:///codewind-workspace/.extensions/codewind-odo-extension/templates/index.json'. Error: TypeError: Cannot read property 'map' of undefined
    at getTemplatesFromRepo (/portal/modules/Templates.js:488:39)
```

**Workaround:** 

No known workaround other to try a cluster with faster / local storage.

**Comment by james-wallis** [comment]
I've raised the PR for this bug. 
The issue is that the `getRepositories` function would resolve outside of the `readFile` callback meaning that there was no way of ensuring the `index.json` had been created in time for the reading.

This has been present in every Codewind release since the `codewind-odo-extension` was created. Due to the consitent rate that @markcor11 was able to recreate it, I'd bet that most users on OpenShift are not seeing the templates.

Additionally, I'll raise a PFE PR to enhance the error handling to reflect when the `index.json` does not exist versus contains invalid JSON.

**Comment by james-wallis** [comment]
Both PRs merged for this item and Mark has already verified the fix.
/close
