### ISSUE TITLE
Split the Project Lifecycle tests from PR builds

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#347]
The PR build tests have been temporarily disabled because they keep timing out (ie failing to build projects within a given timeout).  We need to resolve this issue with a very clear goal of having reliable green tests. 

There are a number of approaches/things to investigate:-
 - split the tests so we have npm run unit tests and npm run integration tests and implement these as separate steps within the build stage.
 - increase timeouts so that tests pass consistently. The downside of this is the test job may take a very long which is not suitable for PR builds. We could then run the integration tests as a nightly job and not include them in PR builds.
- restructure the way the project lifecycle tests run so that Turbine is not trying to build all of the projects at the same time. I believe the test, creates all projects up front which would mean Turbine is then asked to build them all but it can't build that many concurrently.  It may perform more consistently is we do one project at a time (or possibly up to three).

**Comment by ebuckle** [comment]
I'm looking into this

**Comment by stalleyj** [comment]
Can you also add the extra tests for project types so that all our templates are tested, you can find them here https://github.com/kabanero-io/codewind-templates/tree/master/devfiles

**Comment by ebuckle** [comment]
I believe what was causing this is the project creation loop. Creating all the projects at once means that there is a large wait time as you have no control over which containers with initialize first.

I've unrolled the project creation loop so that projects are created and tested one by one and have added in the missing templates (Go, Lagom and Open Liberty).

I am currently having two issues with Lagom and Open Liberty:
- Open Liberty projects created during testing do not take localhost as their host name and instead use the container id of their docker containers
- Lagom projects do not return 200 from their available endpoints, I am currently skipping the .applicationChecker tests to get around this

**Comment by rwalle61** [comment]
pretty sure this is complete

/close
