### ISSUE TITLE
Appsody Runtime for Node.js template not compatible with Codewind ?

### ISSUE THREAD

**Issue by stalleyj** [eclipse/codewind#378]
**Codewind version:**
Latest code on Mac

**Question synopsis:**
Projects created from the Appsody runtime for Node.js template show as stopped in Codewind. This is because it is a very simple node application that prints a message then exits. Turbine is therefore unable to ping the endpoint of the application and the IDE unable to open the application.  

Does it make sense to include this template ?

**Comment by deboer-tim** [comment]
This is 'expected', that stack and at least one other are mostly used for binding/importing existing projects, which would then provide the endpoint. A couple fixes have gone in to make sure we behave reasonably well in this scenario - after all, any other project could have a missing or incorrect endpoint.

We didn't include this stack initially, then did once the initial fixes went in. You could argue that the Appsody team shouldn't really provide this stack for new project creation since it doesn't do anything out of the box, but it's still reasonable because users could want to start with a fairly empty project/basic stack too. IMHO the stack should remain, but we should make sure the status is clear and there is a readme or other place where the purpose of the stack is clear.

**Comment by stalleyj** [comment]
Great, I'm happy that this has been considered and the decision made to include the stack.
