### ISSUE TITLE
SVT: Eclipse plugin: Appsody Python language not selected by default on import

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#398]
**Codewind version:** 0.3.1
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:** Eclispe committers Version: 2019-06 (4.12.0)
**Kubernetes cluster:**

**Description:**
When I import an appsody python flask project the language of "Python" is not selected by default as part of the import wizard.

**Steps to reproduce:**
1. Create an appsody  python flask project.
2. Remove the project from Codewind.
3. Import the project. Wizard does not select an language by default.

Note: Project still works.

**Workaround:**

**Comment by tetchel** [comment]
The detection logic only checks for Java, Node, or Swift. 

https://github.com/eclipse/codewind/blob/master/src/initialize/src/controllers/typeDetectionController.ts

If we want to detect more languages, that's an enhancement for the portal team.

**Comment by tobespc** [comment]
yes, so right now Appsody is detected as a type only, not with the additional language.  One of the main reasons for this is that due to the way Appsody stacks are put together, we may not be able to get at that info.  What we could do is enhance the data that we get from the appsody to include that which should then be a no-op for portal (yep, I'm passing the work to @makandre !)

**Comment by makandre** [comment]
Appsody doesn't really have a language per se, what they have is stack (tho from the stack you could arguably infer from it what the underlying language is)

So when we implemented the appsody extension we relied on portal to detect the language that Codewind recognizes.  If we want to language detection to be done by the appsody extension, we would need a new plug-point for extensions during that language detection stage.

**Comment by mmulholl** [comment]
It sets the correct language for other appsody types.

**Comment by makandre** [comment]
Other appsody language detection works because portal can detect those languages as @tetchel pointed out https://github.com/eclipse/codewind/issues/398#issuecomment-529540710

I noticed (in vscode at least) if I import a Codewind python project, there's a prompt for me to select the language (which makes sense since portal does not detect python).  But there's no such prompt for Appsody python project.

**Comment by makandre** [comment]
I guess the new language detection code is here in the installer now: https://github.com/eclipse/codewind-installer/blob/master/utils/project.go#L37

Perhaps a quick fix would be to make it able to detect python language (maybe by presence of files ending with `.py`?)

**Comment by tetchel** [comment]
appsody can correctly detect python now
