### ISSUE TITLE
Dynamically generated table of contents for Codewind.dev

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#443]
Create a dynamically generated table of contents for the Codewind.dev website.

**Comment by travis1111** [comment]
I will take a look :-)

**Comment by sghung** [comment]
Fix has been delivered. The TOC is generated from a defined list. The TOC can't be generated dynamically without a list, since we still need to define the order, main topics, sub topics, etc. However, it will be much easier for ID and others to add new items to the list and have it show up (without any coding).
