### ISSUE TITLE
Implement Secure connection between local editor and remote cloud deployment

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind#489]
I don't think we should create our own identity provider or add user registries for storing users/passwords in hybrid/cloud. We should support use of 3rd party providers and use security modules like OpenID Connect / OAuth 2 and JWT. That will take some work to implement but we can do this in phases.

JSON Web Tokens can be used in all scenarios, but for each one :

Portal server needs to reject all non-authorised api requests.
Portal server needs to change from using http to https in order to protect exchange of any authentication tokens.
In local only mode, starting the PFE container with username/password environment variables and adding a new "login" route would allow a user to provide matching credentials in order to retrieve an authentication token. This would be their first and required step before attempting to use any of portals APIs. IDE's would implement their own "forms" for users to type credentials into or use the IDE's own credential stores.

Once the token has been issued to the user, that token needs to be sent alongside future requests to any of the portal APIs via inclusion in the Authorization header of the request. Any requests not providing a valid token, including those providing an expired token would get rejected.

At that point we'd have secured our exposed ports, Portal APIs, and have a way for the user to "login" to PFE.

For external apps like Performance Dashboard, which is effectively running just as the IDEs are running, would require the user to provide credentials to retrieve a valid authentication token. It would then store that token in session storage and provide it on subsequent portal API requests.

Stepping up from a static username/password to one that supports end user service operations eg (password changes / multi users) this would involve using the services of an identity provider. There are several KeyCloak/ActiveDirectory/IDS Access Manager etc. OpenID identity providers could still be plugged in to portal locally (using a container based IDP) and once they've authenticated the user the process of transferring the authorisation token is the same. Thus, a token based authentication solution would work across Local, Hybrid and Cloud too.

**Comment by markcor11** [comment]
Working on above

**Comment by markcor11** [comment]
# Proposal

## Desktop : 

Interaction with KeyCloak should be handled by the Codewind CLI.  The desktop IDEs should not be required to talk directly to KeyCloak or take responsibility of managing user credentials.   IDEs may provide a UI to allow the developer to change their passwords but they should connect only to the Codewind CLI which should handle secure storage of credentials and communication with Keycloak.

Refresh tokens will be stored in the desktop keychain.  IDEs will handle the access_token (since they will need this to correspond with Codewind APIs).  IDEs will also need to handle token expiration errors and be required to request a new token via the Codewind CLI. 

Entering a username and password should not be intrusive.  As long as the user has trusted the Codewind CLI to access their Keychain they should not be constantly challenged for a password.  This is subject to the Platform APIs which at some point may ask the user for a fingerprint or to enter their OS login password again in order to unlock the keychain. 

![Screenshot 2019-09-20 at 07 38 54](https://user-images.githubusercontent.com/28102564/65304941-cee2b300-db79-11e9-959f-545f0b88b4a0.png)

## Container Install and Setup : 

As part of the container setup and installation,  defaults are required : 

* Admin username and password
* Developer username and password 
* Codewind Realm 
* Codewind client services

![Screenshot 2019-09-20 at 07 38 35](https://user-images.githubusercontent.com/28102564/65304934-cb4f2c00-db79-11e9-9493-3444f9cf8c89.png)

## Necessary CLI Commands :

To facilitate above,  the Codewind CLI will need to implement some new commands :

![Screenshot 2019-09-20 at 08 45 35](https://user-images.githubusercontent.com/28102564/65308952-099d1900-db83-11e9-80a2-d18e0f48be6d.png)

## Container Config : 

WIthin the Codewind remote container and the Keycloak container,  some configuration and endpoints will be defined : 

![Screenshot 2019-09-20 at 07 39 08](https://user-images.githubusercontent.com/28102564/65304945-d30ed080-db79-11e9-97a2-edb34502f88f.png)

## Deployments

* In a purely local configuration the addition of the keycloak container should not be required.

* In hybrid mode where the Codewind backend is hosted remotely,  a Keycloak container should be installed remotely or the deployments CLI should be used to add the service URL of an existing Keycloak container. 

* Codewind CLI commands may be used to configure an existing Keycloak installation however those actions will require and admin username and password. 

## Keycloak Theme

A Codewind custom theme will be added to the Keycloak container for the login screen initially eg: 

![Screenshot 2019-09-20 at 08 50 40](https://user-images.githubusercontent.com/28102564/65309308-c000fe00-db83-11e9-80b2-8fb53d3ac017.png)

**Comment by jopit** [comment]
Does Keycloak provide an web ui that can be used to change passwords?  If so, does it make sense to require the user to use that ui for those kind of administrative tasks rather than building that function into the IDEs, at least for a first pass?

**Comment by markcor11** [comment]
Keycloak does have a web UI that facilitates user password changes.
However, matching credentials still need to exist in the desktop keychain for the Codewind CLI to use.  If the IDEs are not going to prompt the user to enter a new password,  the user will need to manually update their desktop keychain to match any new Keycloak stored password. For a first pass that would be ok (with some support documentation)

**Comment by markcor11** [comment]
- [ ] Create Keycloak Docker image
- [ ] Add Codewind theme

- [ ] Create CLI Command:  Authenticate
- [ ] Create CLI Command:  Realm Create
- [ ] Create CLI Command:  Client Create
- [ ] Create CLI Command:  Client Get
- [ ] Create CLI Command:  User Create
- [ ] Create CLI Command:  User Get
- [ ] Create CLI Command:  User Reset Password

- [ ] Store developer credentials in Keychain (Mac) / Secret Service (Linux) / Windows Credential Manager

**Comment by markcor11** [comment]
Initial PR with first wave of CLI security commands :  https://github.com/eclipse/codewind-installer/pull/132

**Comment by markcor11** [comment]
PR with updates to Deployment command to store AUTH connection details: https://github.com/eclipse/codewind-installer/pull/135

**Comment by markcor11** [comment]
PR to store authentication credentials in platform keychains : https://github.com/eclipse/codewind-installer/pull/136

**Comment by markcor11** [comment]
Pre-select preferred keycloak theme  https://github.com/eclipse/codewind-installer/pull/149

**Comment by markcor11** [comment]
PR to make CLI Deployments command Gatekeeper aware :  https://github.com/eclipse/codewind-installer/pull/150

**Comment by micgibso** [comment]
@sishida Can you assign me please, I'll take a look at this one.

**Comment by markcor11** [comment]
PR to automate deployment of Codewind Remote + Keycloak + Gatekeeper https://github.com/eclipse/codewind-installer/pull/171

**Comment by markcor11** [comment]
PR:  Adds DispatchHTTPRequest in CLI to wrap security around PFE API requests https://github.com/eclipse/codewind-installer/pull/181

**Comment by micgibso** [comment]
@sishida Discussing with Mark, can you please move this out to release 0.7.0. thx!

**Comment by markcor11** [comment]
Introduce keycloak and gatekeeper to codewind:  https://github.com/eclipse/codewind/pull/1086

**Comment by markcor11** [comment]
Add auth to Bind and Sync :  PR https://github.com/eclipse/codewind-installer/pull/208

**Comment by micgibso** [comment]
Documented as part of https://github.com/eclipse/codewind/issues/579

**Comment by malincoln** [comment]
@tobespc pls verify and close. Thanks

**Comment by jgwest** [comment]
The websocket API used by the filewatcher is still not secured: https://github.com/eclipse/codewind/issues/1342

**Comment by tetchel** [comment]
Also the codewind ingress on Che is still not secured

**Comment by malincoln** [comment]
is this issue ready for verification or more work is needed?

**Comment by jgwest** [comment]
Shifting it back to `In Progress` as the server-side filewatcher WebSocket API should still be secured as part of this work.

**Comment by tobespc** [comment]
@elsony This will require work from your squad as to deliver this for filewatcher

**Comment by tobespc** [comment]
We discussed moving the socket type to be a socket.io rather than a websocket.   Lets re visit this as part of this work

**Comment by jgwest** [comment]
If anything we should be moving in the opposite direction (using standard websockets), given the poor socket.io support in Go and Java.

**Comment by tobespc** [comment]
I'm resolving this as done as we have implemented a secure connection as per original request.  Any enhancements to the sockets should be tracked in a separate issue if required
