### ISSUE TITLE
Documentation for creating your own template source repository

### ISSUE THREAD

**Issue by sishida** [eclipse/codewind#497]
Tagging @tetchel and @eharris369 for their awareness.

Although we merged https://github.com/eclipse/codewind-docs/pull/143, as Tim mentioned, we need documentation for how to create your own template source repository, such as how to provide your own index.json file.

**Comment by AndyRWatson** [comment]
in addition we also need to document the steps  to create your own template within your template source repo https://github.com/eclipse/codewind/issues/713

**Comment by micgibso** [comment]
@tetchel @eharris369 @sishida @AndyRWatson This is covered in the recently revamped template topics https://www.eclipse.org/codewind/mdteclipseworkingwithtemplates.html and https://www.eclipse.org/codewind/mdt-vsc-workingwithtemplates.html. If there's anything else that needs to be covered, please let me know, otherwise this can be closed.
