### ISSUE TITLE
Update appsody troubleshooting to include additional windows instructions

### ISSUE THREAD

**Issue by sghung** [eclipse/codewind#498]
The appsody troubleshooting section needs to have the following info:

https://github.com/gcharters/kabanero-dev-getting-started/blob/master/docker-windows-aad.md

This will get past a Windows issue one of our developers was experiencing. When they are using java projects on Windows, some users may hit this issue and needs to follow those instructions above.

**Comment by sishida** [comment]
@sghung Hi, Steven, Is this issue something that we intend to eventually fix in Codewind? If so, I'd prefer not to update the docs because then we'll just have to remove the info later.

However, if this is an issue that is beyond our control or something that will remain indefinitely, I will add it to Troubleshooting. 👍 Please let me know. Thank you!

**Comment by sghung** [comment]
Hey Sarah, this appears to be a limitation that won't be fixed and will rely on documentation indefinitely.

**Comment by sishida** [comment]
Thanks for the clarification! I'll plan to add it in after 0.4.0! 👍

**Comment by sishida** [comment]
@sghung Hi, Steven, Could you please review my PR for this issue? https://github.com/eclipse/codewind-docs/pull/159

**Comment by sishida** [comment]
@sghung Thank you for merging the PR. Is this issue now good to close?

**Comment by sghung** [comment]
Thanks, closing
