### ISSUE TITLE
Provide user directions for getting the codewind-workspace ingress/route

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#560]
With the current hybrid architecture, the user has to specify the codewind-workspace ingress (or route on openshift).

1. Log into the cluster
2. `kubectl get ing | grep codewind-workspace` or `oc get route | grep codewind-workspace` in the relevant namespace
3. It's the second item, eg in:
```
[ /tim/programs/codewind ] 17 $ kubectl get ing | grep codewind-workspace
codewind-workspacef46yui3s8782yntz   codewind-workspacef46yui3s8782yntz-che-che.10.102.13.205.nip.io       localhost   80      24h
```
we're looking for: `codewind-workspacef46yui3s8782yntz-che-che.10.102.13.205.nip.io`.

Alternatively, they can just copy the ingress from another user who has access to that cluster and namespace, and then they can skip running these commands.

They will then have to enter that ingress domain into the IDE 'new connection' wizard.

We should
a) provide concise directions to be shown in the IDEs
b) provide more detailed directions to be shown in our hybrid documentation

**Comment by johnmcollier** [comment]
Can we assume the installer/CLI needs an active Kube context for Hybrid to function? If so, could we just have the installer/CLI look up the ingress URL for PFE instead?

**Comment by tetchel** [comment]
@markcor11 your thoughts?

**Comment by markcor11** [comment]
Having a Kube config is only required when deploying Codewind Remote into Kube.  Once  deployed, the expected interaction with Codewind remote (from either the CLI,  IDEs, curl) will be via the new codewind-gatekeeper ingress instead of the old workspace-ingress (which will be removed).

We don't expect "developers" using Codewind to install Kubectl or oc, or have to worry about Kube namespaces or contexts.  The only information needed to hook up with Codewind Remote is the Gatekeeper Ingress URL and Keycloak credentials. Those details should be supplied by their deployment administrators.

We will provide documentation on both the authentication flow and interactions between Desktop and Remote deployment, but identifying which PFE to use would depend on more than just the results of 'kubectl get ingress'.  There may be multiple PFE's installed into a single Kube namespace and only some of those remotes may grant access depending on the Keycloak service each Codewind remote is configured to use.

**Comment by sishida** [comment]
Hi, team, I started trying to write up content for this issue today. To clarify...does the more recent comment from @markcor11 override the original Sept. 26th comment from @tetchel? Or do we need to provide Codewind users with both sets of info? Thanks!

**Comment by tetchel** [comment]
my comments above are outdated, mark is the authority on this

**Comment by sishida** [comment]
---
layout: docs
title: Deploying into Codewind remote
description: Deploying into Codewind remote
keywords: build, deploy, cloud, public cloud, Kubernetes, remote, credentials
duration: 1 minute
permalink: remote_deployment.
type: document
---

# Deploying into Codewind remote
When you deploy Codewind remote into Kubernetes, you need a Kubernetes configuration. After you deploy Codewind remote, you can interact with Codewind remote from either the CLI, IDEs, or curl through the `codewind-gatekeeper` ingress. Obtain the ingress URL and keycloak credentials from your deployment administrator.

### Authentication flow (More to come)

### Interactions between Desktop and Remote deployment (More to come)
Identifying which PFE to use would depend on more than just the results of 'kubectl get ingress'. There may be multiple PFE's installed into a single Kube namespace and only some of those remotes may grant access depending on the Keycloak service each Codewind remote is configured to use.

**Comment by micgibso** [comment]
@sishida I'll take a look at this please.

**Comment by micgibso** [comment]
Discussing with Mark, might need some info re why we need an ingress, or on OpenShift, why we need routes. @sishida Could you move this out to 0.7.0 pls, thx!
Document download the mandatory.yaml and cloudgeneric.yaml, you need both. See slack, Monday 14th October. Also see codewind-installer PR 171.

**Comment by micgibso** [comment]
@tobespc @tetchel Ingress/route instructions provided on https://github.com/eclipse/codewind/issues/579, see https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/remote-configuring.md.  Can this be closed as complete?

**Comment by micgibso** [comment]
Discussed with Mark, closing as complete.
