### ISSUE TITLE
OpenAPI: Update docs for 0.5.0

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind#650]
**Codewind version:** 0.5.0
**IDE:** Eclipse

This issue is to request documentation updates for Open API Tools

1. This applies to Eclipse. When generating a Java client or server stub into an existing Appsody or Codewind Liberty Microprofile project, there might be a validation error on the pom.xml:

- Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:aspectj-maven-plugin:1.0:compile (execution: default, phase: process-classes)

  The build will still be successful even though the validator reports this issue.  To resolve this, surround the `plugins` element under the `build` element of the pom.xml with the `pluginManagement` element.

```
  <build>
    <pluginManagement>
       <plugins>
         ...
```

2. This work-around applies to both VS Code and Eclipse. The `spring` server generator creates invalid source in the `OpenAPI2SpringBoot` class.  Simply implement the methods from the interface and save the file.  Also add the `configuration` element to the pom.xml, like this:

```
     <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                     <mainClass>org.openapitools.OpenAPI2SpringBoot</mainClass>
                </configuration>
                 ....
```

**Comment by sishida** [comment]
- Link to the general/overall issue: general/overall issue is: https://github.com/eclipse/codewind/issues/79 This issue will not be entirely covered for the 0.5.0 release.
- So Keith currently has this issue: https://github.com/eclipse/codewind-openapi-eclipse/issues/60. I have already reviewed the strings for this issue.
- The second point here https://github.com/eclipse/codewind/issues/650#issue-504840535 refers to this issue: https://github.com/eclipse/codewind-openapi-eclipse/issues/58.

**Comment by micgibso** [comment]
@sishida I can take a look at this. 
@keithchong So to confirm, is this a new issue in Troubleshooting? 
https://www.eclipse.org/codewind/mdteclipsetroubleshooting.html - seems the best place for it.

**Comment by sishida** [comment]
@keithchong @micgibso 
If this is an issue that we are working on resolving, and if we expect these OpenAPI instructions to become obsolete, let's leave this issue open so users can see it and then just close it when it's resolved instead of updating the Troubleshooting page.

If we do want to update the landing pages, we've also got two OpenAPI pages thus far:
- Eclipse: https://www.eclipse.org/codewind/open-api-tools-for-eclipse.html
- VS Code: https://www.eclipse.org/codewind/open-api-tools-for-vscode.html

**Comment by keithchong** [comment]
@micgibso , I plan to hook in a link to the landing page (at least for Eclipse) from the Eclipse wizard itself.  So maybe the user will search the help first and then think about searching for github issues?   Also, maybe you can link to a specific github issues query from the landing page?

**Comment by micgibso** [comment]
@keithchong I think users will, as you say, search the help first, so have drafted this issue in the top level Troubleshooting topic under the Open API tools section because it applies to both VS Code and Eclipse, see PR https://github.com/eclipse/codewind-docs/pull/176. 

We do have a process in place to check the issues are all still valid prior to each release so it should get picked up when it's no longer an issue. 

Will have a chat with Design about how we deal with Troubleshooting issues, see if we can come up with something better, current state isn't ideal.

**Comment by keithchong** [comment]
@micgibso , @sishida 

For the troubleshooting, please do the following:

Remove BOTH points of the following points under the workaround section:

- Manually create the output folder before you start the OpenAPI generator wizard. In the wizard, you can manually edit the Output folder text field. Ensure that the path points to a valid folder in the project.
- Or you can use the Browse… button to select the folder that you want to use. The Output folder field is updated with the path.

**Comment by keithchong** [comment]
For the last paragraph, modify it to be something like this:

For non-Java based post-client or post-server stub generation, use a separate output folder for code generation. Depending on the language and the generator type, the OpenAPI generator generates both source code files and build-related files. Some refactoring might be necessary. For example, move the generated source code to the proper source folder that already exists in the project. However, if your project is empty, the target output folder can be the root of the project, and you don’t need to do as much refactoring and merging.

**Comment by micgibso** [comment]
@keithchong All done, on PR https://github.com/eclipse/codewind-docs/pull/176

**Comment by micgibso** [comment]
@keithchong Have reworked that last sentence slightly, and split it into a new paragraph, see https://github.com/eclipse/codewind-docs/pull/176/files for the latest. Thanks.

**Comment by micgibso** [comment]
@sishida Please move to in-progress, thanks!

**Comment by micgibso** [comment]
This is complete now.

**Comment by keithchong** [comment]
Thanks @micgibso . Closing.
