### ISSUE TITLE
GET /registry always fails

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#666]
```
[11/10/19 17:06:04 User.js] [INFO] Checking PFE & workspace settings deployment registry
[11/10/19 17:06:04 User.js] [INFO] Workspace settings deployment registry status: false
[11/10/19 17:06:25 User.js] [INFO] Could not determine if watch for the workspace settings file had been established
```

Note the request took 20 seconds, too.

In the new design, we should just be checking `.config/settings.json`, not worrying about the filewatcher.

**Comment by maysunfaisal** [comment]
This happens because PFE cannot determine if filewatching on the file `codewind-workspace/.config/` has been established. Check https://github.com/eclipse/codewind/blob/master/src/pfe/portal/modules/User.js#L632

We have two options:

1. We remove filewatching completely on the workspace settings file
2. Filewatcher listens to the `codewind-workspace/.config/` dir; wherever that happens to be in hybrid case.

**Comment by maysunfaisal** [comment]
@elsony @rajivnathan any thoughts?

**Comment by tetchel** [comment]
we could have the IDE just check `~/.codewind/.config/settings.json` instead of having PFE read it at all, then it would be guaranteed to be up-to-date with no FW. but that doesn't seem ideal.

**Comment by rajivnathan** [comment]
This file contains only the deployment registry info right?

@tetchel @maysunfaisal I think what we do depends on whether this file needs to be on the local user's filesystem at all. If we provide APIs in PFE to both get and set it then presumably the state can be managed by PFE and the IDE only needs to call GET to check whether it's already set and then if not set can prompt the user to set it?

@tobespc If we put the file in the codewind-workspace in PFE will that be persisted when running in the pure hybrid model?

**Comment by tetchel** [comment]
likely this should be fixed in conjunction with https://github.com/eclipse/codewind/issues/665

**Comment by maysunfaisal** [comment]
FYI this only happens on pure Kube, where there is no Filewatcher. In Che, Filewatcher is running in the Sidecar and is not an issue

**Comment by tetchel** [comment]
well, there is a filewatcher, but it's not watching that file, because there's no more workspace

**Comment by jopit** [comment]
- IDE calls new command on cli 
- Command on cli will update registry which will POST to PFE
- PFE will save the file to the settings.json
- Keep Che with current architecture?
  - Keep it at least for 0.6.0
  - TODO: decide if we want to keep file-watcher on Che

**Comment by maysunfaisal** [comment]
Update:

- IDE already calls POST /registry for PFE writing to file, so no need to call the cwctl cli
- I think it makes sense to remove filewatching and this is done with PR https://github.com/eclipse/codewind/pull/868 since #704 can be solved as well. This also makes logic consistent between Che and Hyrbid ie; PFE Post /registry is the only way to update the `/codewind-workspace/.config/settings.json` file in the PFE container

**Comment by jopit** [comment]
I thought the ultimate goal was for the IDEs to do everything through the cwctl cli, so shouldn't we still provide this support in the cli?

**Comment by jopit** [comment]
It's more a question for @tobespc

**Comment by tetchel** [comment]
The GET works now
