### ISSUE TITLE
Version update for codewind-openapi-eclipse

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#679]
Bump up the version from 0.2.0 to 0.5.0. 

Checklist to confirm and update if necessary 

1. NOTICE.md:codewind - 0.2.0
NOTICE.md:codewind-java-profiler-client - 0.2.0
NOTICE.md:codewind-openapi-tools - 0.2.0

2. dev/org.eclipse.codewind.openapi.feature/category.xml:   `<feature url="features/org.eclipse.codewind.openapi.feature_0.2.0.qualifier.jar" id="org.eclipse.codewind.openapi.feature" version="0.2.0.qualifier">`

3. dev/ant_build/build-cw.xml:    `<property name="level_tag" value="0.2.0"/>`

4. Top feature level
dev/org.eclipse.codewind.openapi.feature/feature.xml:      version="x.x.x.qualifier"

**Comment by keithchong** [comment]
@josephca , for 1, I'm only going to change NOTICE.md:codewind-openapi-tools - 0.2.0

**Comment by keithchong** [comment]
@josephca , we have two Eclipse openapi features

**org.eclipse.codewind.openapi.base.feature**
This version is currently at 1.0.200.qualifier and was bumped up 7 days ago from 1.0.100 to 1.0.200 specifically for 0.5.0.  This one will follow Eclipse versioning guidelines.

**org.eclipse.codewind.openapi.feature**
This one is the 'top level feature' whose version has already been changed to 0.5.0.qualifier.  This feature `includes` the above base feature.

Therefore, for point 4, I believe no change is necessary.  Please let me know otherwise.

**Comment by josephca** [comment]
> @josephca , for 1, I'm only going to change NOTICE.md:codewind-openapi-tools - 0.2.0

@keithchong Update on NOTICE.md is done together with other codewind repos.

**Comment by josephca** [comment]
@keithchong I believe we can close this. Please reopen otherwise. :)
