### ISSUE TITLE
Remote: ignorePath is bypassed

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#818]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

In the new remote architecture:

- When a file is changed, it is uploaded from host filesystem to PFE
- At the end of the upload, file change events are [sent to Turbine](https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/remoteBind.route.js#L276)
- Turbine processes the file change events in [updateProjectForNewChange](https://github.com/eclipse/codewind/blob/master/src/pfe/file-watcher/server/src/controllers/projectEventsController.ts#L49) to determine if a build is required.

During this entire flow, a project type's `ignorePath` is not consulted at all.  So I believe this means files that are not meant to trigger a build, will actually trigger a build if it's changed and uploaded.

This is possibly related to #808

**Steps to reproduce:**

**Workaround:**

**Comment by jgwest** [comment]
It seems like there are 3 different places that we may need filter rules to apply:
- A) **Filewatcher change notification filter rules** (current): This is what we currently have; filewatcherd will watch a directory, and trigger on file changes, but will ignore changes that match one of the ignore rules. Example: Maven's `/target` would be filtered out by `*/target*`
- B) **Cwctl project sync upload filter rules** (new):  The cwctl command synchronizes files to various places, but since uploading is a potentially slow process, we only want to upload useful files (and exclude things like Maven's `target`). 
- C)  **Trigger build on file change filter rules** (new): After files are uploaded, we need to decide whether to trigger a build (and potentially what type to trigger). The list of changed files is received in `updateProjectForNewChange` (link above). We can filter here as well.

A significant driver of the need for these filters types is the Appsody case. Appsody is currently using an `ignorePath` filter rule of `*/*` to prevent filewatcherd from reporting file change notifications, but this filter rule can't be used with the new architecture.

To demonstrate the need for for all three filters, consider the appsody case:
1) The user makes a change to a file under an Appsody project.
2) We need the filewatcher to detect that change, and call the project sync. So filter A cannot filter out the Appsody source (but we still want it filter out any directories like `/target`)
3) Project sync will detect and upload the changed files. With filter B, we need it to upload  all newly changed files (but likewise we want to ignore binary dirs). 
4) The file change list will be received by PFE. Here, since we DON'T want PFE to build (because Appsody includes its own build logic), we want to filter out ALL files with `*/*` (filter C).

So filter A and filter B will be mostly permissive, and filter C will be entirely restrictive.

In the Appsody case, all relevant file changes should be detected, and uploaded (except those like `/target`), and thus should not be filtered out, BUT we still don't want it to trigger a build event (and thus SHOULD be filtered out at build time).

My suggestion would be:
1) I believe cwctl project sync can use the same filters as the file watcher, so treat filter type A and filter type B as the same. 
2) Implement a new filter type (based on type C), which decides which files to filter out when deciding when to do a build.  Update `updateProjectForNewChange` to apply this filter.
3) Update the Appsody filters, so that type A/B are fully permissive, and type C is fully restrictive.

**Comment by yangcao77** [comment]
Is that possible for `cwctl project sync` to only upload changed files received from filewatcher? so it won't need another filter, and we reduce the amount of files required to be uploaded.

**Comment by jgwest** [comment]
@yangcao77 Unfortunately not: the file watcher uses 3rd-party libraries that interface with the operating system (fsnotify et al) to receive file change notifications, and I have previously found these libraries to not reliably detect ALL file/directories changes in high-throughput situations. 

Thus the `cwctl project sync` does its own scan of the file system for changed files, and synchronizes based on the result. 

However, since `cwctl project sync` and the file watcher rules are closely related, I think they can be the same (eg as above, treat filters A and B as the same)

**Comment by jgwest** [comment]
Related: https://github.com/eclipse/codewind/issues/750

**Comment by james-wallis** [comment]
The work for #750 has been completed and a PR accepted. Further work for dynamic lists / using a PFE API is in a new issue: https://github.com/eclipse/codewind/issues/835

**Comment by makandre** [comment]
It sounds like #750/#835 is meant to address what files should or should not be synced to PFE.

However, this issue is for when files that are synced to PFE, they should not trigger a build if they are on the project type's `ignorePath`

**Comment by tobespc** [comment]
I've found the problem.   The change that @jgwest put into FW 7 days ago had not been pulled into the vscode IDE.  Due to the package-lock file, it was still using the previous version.   I've put a PR up against vscode to sort this out but can confirm that using the lates fw demon with the ide fies this
