### ISSUE TITLE
Unable to start Codewind containers on Windows

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#910]
**Codewind version:**
master

**OS:**
Windows 10 Enterprise

**Description:**
The pfe container fails to start on Windows with:
```
PS C:\Users\Administrator\Downloads> .\cwctl-win-2019-10-30-0829.exe start -t latest
Debug: false
==> created file codewind-docker-compose.yaml
==> environment structure written to codewind-docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait whilst containers initialize...
codewind-performance is up-to-date
Creating codewind-pfe ...
[1Bting codewind-pfe ... [31merror[0m
ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: b'Drive sharing failed for an unknown reason'

ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: b'Drive sharing failed for an unknown reason'
Encountered errors while bringing up the project.
```
This is because of the extra volume mount added here:
https://github.com/eclipse/codewind-installer/blame/master/utils/docker.go#L45

It has never been possible to get bind mounts working on the Windows 10 Enterprise boxes and this blocks us from starting codewind on those machines.
I believe this was added for Appsody support but as Appsody is not an Eclipse project, we should not fail to start because of function added for Appsody support. (Also I'm not sure if Appsody supports development on Windows.)

I will raise a PR to make the bind mount conditional so it is only added on non-Windows boxes.

**Steps to reproduce:**
Run the latest installer on Windows:
```
.\cwctl-win-2019-10-30-0829.exe install -t latest
.\cwctl-win-2019-10-30-0829.exe start -t latest
```

**Workaround:** 
None.

**Comment by jgwest** [comment]
@hhellyer 

A few points:
- Docker does work on Enterprise Windows (for example, what IBM puts on Thinkpads like mine), but you need to create a new local user account, and provide that account's credentials when Docker asks. (See [here](https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/)
- Docker does support bind mounts on Enterprise Windows (as long as the directory being shared by the user whose credentials you provided, above).
- Appsody does support Windows developers. I'm not sure we can drop support for them in Codewind, if that is what this patch does.

**Comment by makandre** [comment]
Yes it's a bind mount for retaining our Appsody support under 0.6.0's architecture.

But I'm not doing anything different from how we had the `codewind-workspace` bind mount pre-0.6.0, i.e. we had mounted `C:\codewind-workspace` -> `/codewind-workspace`, and now the mount is `C:\codewind-temp` -> `/mounted-workspace` (soon to be renamed to `codewind-data` pending https://github.com/eclipse/codewind-installer/pull/173)

Does the directory need to be pre-created on Windows?  On non-windows docker-compose creates directories used for the bind mounts if it doesn't exist.

**Comment by hhellyer** [comment]
Pre-0.60 we couldn't run on (some - I'm not sure how many) Windows machines because of the issues with giving docker access to shared drives.

Removing them allowed us to run on Windows without needing to do that. The changes to remove the bind mounts had fixed that issue. This does regress that improvement.

(There are also issues with bind mounts on Linux, it causes files to be created as root. There was a Codewind issue raised very early about this but I can't find it now.)

**Comment by malincoln** [comment]
@makandre as this is stopship, is this still in plan for 0.6.0?

**Comment by makandre** [comment]
@hhellyer This is not stopship, as discussed, is that right?

**Comment by rtaniwa** [comment]
It isn't clear to me what level of broken we are, but if the title is an accurate reflection (Codewind doesn't work on Windows) then this is a stop ship.

**Comment by hhellyer** [comment]
The title should probably be *some* Windows versions (or configurations).

(I assume Appsody isn't supported in remote/hybrid mode as there's no way to provide a bind mount there.)

**Comment by hhellyer** [comment]
Ok, I'll close this since it looks like the issues should be resolved by a future release of Appsody rather than Codewind.

**Comment by raju-valivarthi** [comment]
is this issue fixed in the latest version? I could not launch codewind 0.14.0 on windows 10 desktop. 

Full Codewind log is at "c:\Users\Test\AppData\Roaming\Code\logs\20200725T093417\exthost1\IBM.codewind\codewind.log"

C:\Users\Test\.codewind\0.14.0 exists
cwctl is available at C:\Users\Test\.codewind\0.14.0\cwctl.exe
appsody 0.6.4 is available at C:\Users\Test\.codewind\0.14.0\appsody.exe
==> Run cwctl.exe --json --insecure connections list  |  09:55:04.203
{"schemaversion":1,"connections":[{"id":"local","label":"Codewind local connection","url":"","auth":"","realm":"","clientid":"","username":""}]}
==> End cwctl.exe --json --insecure connections list  |  09:55:04.491 (Took 288ms)
==> Run cwctl.exe --json --insecure status  |  09:55:04.494
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:04.812 (Took 318ms)
==> Run cwctl.exe --json --insecure status  |  09:55:56.647
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:56.772 (Took 125ms)
==> Run cwctl.exe --json --insecure status  |  09:55:56.778
{"status":"stopped","installed-versions":["latest","0.14.0"]}
==> End cwctl.exe --json --insecure status  |  09:55:56.884 (Took 106ms)
==> Run cwctl.exe --json start -t 0.14.0  |  09:55:56.893
Debug: false
==> environment structure written to C:/Users/Test/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...  
Recreating codewind-performance ... 

[1A[2K
Recreating codewind-performance ... [32mdone[0m
[1BCreating codewind-pfe           ... 

[1A[2K
Creating codewind-pfe           ... [31merror[0m
[1B
ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute

ERROR: for codewind-pfe  Cannot create container for service codewind-pfe: invalid mount config for type "bind": invalid mount path: 'C:/dev/null' mount path must be absolute
Encountered errors while bringing up the project.
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl.exe --json start -t 0.14.0  |  09:56:00.995 (Took 4102ms)

Using all latest versions.. can someone help me how to fix this issue

**Comment by jagraj** [comment]
@raju-valivarthi 
Looks like Codewind can not mount volumes. When you navigate to Docker settings "File sharing" what you have in the list.?

Here is what I have on my Windows install.
![image](https://user-images.githubusercontent.com/713849/88541028-17f96400-cfe2-11ea-9e66-d80d264441b1.png)

**Comment by raju-valivarthi** [comment]
@jagraj , Thank you for your reply.

I have Docker Toolbox installed on my machine. 

Docker version 19.03.1, build 74b1e89e8a


![codewind error](https://user-images.githubusercontent.com/64987036/88551821-4fbbd800-cff1-11ea-9668-3cd7cd58404a.JPG)

I tried modifying shared folders options but no luck.

**Comment by jagraj** [comment]
@raju-valivarthi 

Just want to make sure you are not using virtualbox. Virtualbox and Docker Toolbox is for Windows 7. We do not support this install. We recommend users to use Windows 10 native Hyper-V and Docker install on top of it.
