### ISSUE TITLE
enable passing environment options to appsody from codewind

### ISSUE THREAD

**Issue by richard-trotter** [eclipse/codewind#934]
From command line I can do:
  appsody run --docker-options "-e MYDB_PWD=passw0rd"

I need to be able to do this from Codewind as well.

Environment variables are a very obvious omission. There may be other use cases motivating '--docker-options'. 

By analogy, consider an Eclipse launch config, or a K8s deployment spec. 

Codewind version: 0.5.0
Eclipse IDE version:   4.12.0.v20190605

**Comment by gcharters** [comment]
This gets my vote.. I also came across it needing to specify database connection information in an environment file.

**Comment by johnmcollier** [comment]
+1 we really need to support this for all project types (especially Appsody in this case), and I think this'll prevent proper multi-microservice development with Codewind until it's in place

**Comment by makandre** [comment]
I opened an issue on appsody https://github.com/appsody/appsody/issues/704

**Comment by nastacio** [comment]
appsody can receive environment variables in two different ways today, both via --docker-options:
- --docker-options="--env-file somefile.properties"
- --docker-options="-e property=value ..."

It is unclear to me whether appsody/appsody#704 is mentioned here as a related issue or as blocker. I would disagree with the latter if that is the case.

**Comment by makandre** [comment]
@nastacio It's related

**Comment by makandre** [comment]
Related sub-features for this enhancement:

- #1399 
- #1401

**Comment by sghung** [comment]
Still waiting on filewatcher and turbine fixes to get in.

**Comment by sghung** [comment]
For 0.9.0 supporting using the codewind ref file for adding external files that can be synced up. More details to come once the items get in.

**Comment by sghung** [comment]
Need to wait for vscode to pickup the new filewatcher change and we should be good to go. There will be doc impact once this done.

**Comment by malincoln** [comment]
> Need to wait for vscode to pickup the new filewatcher change and we should be good to go. There will be doc impact once this done.

@tetchel are the vscode changes in now?

**Comment by tetchel** [comment]
Yes since last Tuesday. https://github.com/eclipse/codewind-vscode/pull/426 

I would have updated this issue but I wasn't aware of it

**Comment by malincoln** [comment]
@sishida @micgibso are the doc changes complete or still in progress?

**Comment by micgibso** [comment]
@malincoln @sishida 's following up with Steven.

**Comment by sishida** [comment]
@malincoln,
@sghung informed me, "Andrew verified the doc changes in https://github.com/eclipse/codewind/issues/1399." Thanks!

**Comment by nastacio** [comment]
I am concerned about the solution outlined here:
https://www.eclipse.org/codewind/importing-existing-projects.html#defining-environment-variables-for-appsody-projects

Asking people to put what likely amounts to a file full of credentials into the project tree and then having the wherewithal to add it to .gitignore file is risky.

The workaround in https://www.eclipse.org/codewind/referencing-files.html also requires the user to remember about adding the .cw-refpaths.json file in the .gitignore file since the "from" field references local files in the developer's workstation.

Given the security exposure of the documented step for Appsody and the fact that the workaround allows the reference to the configuration as a file (more desirable in K8s environments) , I would go for the workaround, though I still think the essence of the original issue is not met with a requirement for the user to leave the UI and go edit/copy files around in the filesystem after the application has already been created in Codewind.

**Comment by makandre** [comment]
@nastacio The mechanisms for this enhancement were delivered with the consideration that they could easily be adapted to be used by all project types in Codewind and not limited to Appsody.  And we also felt this was the way we could get this capability out faster.  This lays the ground work on which we can certainly wrap some additional UI around to provide a more seamless experience for the user, and shield them from the details of the underlying metadata files.  I will open an issue for it.

**Comment by nastacio** [comment]
@makandre I only mentioned Appsody because that is in the title of the section in the codewind doc page, my comments are unrelated to Appsody itself.

**Comment by malincoln** [comment]
@makandre is this ready to be verified?

**Comment by malincoln** [comment]
@richard-trotter pls verify and close if resolved.  Thanks

**Comment by richard-trotter** [comment]
Verified fix by way of 'env.properties' in 0.9.0.
I've added +1 for #2294
