### ISSUE TITLE
Codewind not able to work with stacks images in the internal registry/non-docker hub

### ISSUE THREAD

**Issue by mtamboli** [eclipse/codewind#938]
I have a custom stack/collection for which image is pushed to the OpenShift internal registry instead of docker hub. Appsody CLI can work with internal registry if
1. If you are already looked into internal docker regisiry
docker login -u  <user> -p <password>  <docker-registry>
2. Also, if you update ~/.appsody/.appsody.yaml 
images: <docker-registry>

When using the corresponding kabanero-index.json file, codewind is not able to start the project. It is due to codewind container does not have credentials to login to internal docker registry. If I login to codewind container and do docker login then it is able to pull the image.

Is it possible for codewind container to pick the available token if the machine is already logged into the docker registry? So codewind should be able to support any other registry for storing stack images.

```
Running command: docker pull <docker-registry>
Using default tag: latest
Error response from daemon: unauthorized: authentication required
[Warning] Docker image pull failed: exit status 1
```

**Codewind version:0.5.0**
**OS:** Mac Darwin Kernel Version 18.7.0:

**Che version:**
**IDE extension version:**
**IDE version:**: Vscode
**Kubernetes cluster:** OKS3.11

**Description:**

**Steps to reproduce:**

Use a index JSON file with stack/collection which has the images (I.e. Java Microprofile) stored in a different location than docker hub. 

**Workaround:** 

Logged on to the running codewind container and did `docker login` and then it is able to pull the correct image of the stack.

**Comment by sghung** [comment]
This may happen for general codewind projects too, so removing the area/appsody label.

**Comment by sghung** [comment]
Marika said this is a stop ship issue

**Comment by sghung** [comment]
Removed the stopship to avoid confusion for our release. This is a stopship for another product.

**Comment by sghung** [comment]
I have setup a meeting with some of the leads to discuss the possible solutions on the morning of November 1st.

**Comment by rtaniwa** [comment]
Let's keep this one tagged as hot, given it is high priority for Kabanero.

**Comment by makandre** [comment]
Summary

- It sounds like we can leverage the first part of https://github.com/eclipse/codewind/issues/665 to set the docker credentials in PFE (also covered by #948 at the epic level)
- there may be some additional configuration or parameters that we'll need to set on the Appsody CLI; this part needs investigation but should be fairly straightforward.

**Comment by sghung** [comment]
- The API work has been completed from the codewind side via #665 
- Currently waiting on the IDEs to implement the UI for adding credentials
- A docker private registry test case has been created

**Comment by sghung** [comment]
I did a Webex with Monica and Jag, it looks like their setup is different than what I had. They define the private registry via the "image" property in their global appsody config file (not in the stack image). I need to try out this scenario with my test case as the setup is different.

**Comment by makandre** [comment]
The use of global `image` property is the old way of doing things I believe.  Now it is expected to have the fully qualified image name (incl. repository) in the project's `.appsody-config.yaml`

**Comment by mtamboli** [comment]
@makandre `appsody init` fails to get the image of the stack (for images that are not in docker hub). User does not have any way to update .appsody-config.yaml file before the init.

**Comment by mtamboli** [comment]
> I did a Webex with Monica and Jag, it looks like their setup is different than what I had. They define the private registry via the "image" property in their global appsody config file (not in the stack image). I need to try out this scenario with my test case as the setup is different.

Please let me know if you need my cluster for debugging.

**Comment by makandre** [comment]
This is in Che right?  Yes `appsody init` would fail to download the image, but in Che that is expected; `appsody init` purpose is to setup the env for IDE, such as Eclipse or VS Code when in local, but on Che it is not necessary for Theia.  This failure should only result in a WARNING and should not fail the entire `appsody init` command.

Also, we (Codewind) pull the project template `tar.gz` directly rather than depending on `appsody init` command to pull it down.

**Comment by mtamboli** [comment]
> This is in Che right? Yes `appsody init` would fail to download the image, but in Che that is expected; `appsody init` purpose is to setup the env for IDE, such as Eclipse or VS Code when in local, but on Che it is not necessary for Theia. This failure should only result in a WARNING and should not fail the entire `appsody init` command.
> 
> Also, we (Codewind) pull the project template `tar.gz` directly rather than depending on `appsody init` command to pull it down.

This is VScode and codewind on the local machine. Project seems to be failing during the initialization.

**Comment by makandre** [comment]
Oh if it's local, then in 0.7.0 users will need to do a local `docker login` to their private registry first.  We ran out of runway to get the private registry credentials persisted in Codewind in 0.7.0.  We will address the local case in the next release.

**Comment by sghung** [comment]
Currently stuck trying to figure out where the appsody being called inside PFE is using its appsody.yaml from. Locally, if I set the images property, I can see it pulling from there, but not the `appsody run` which uses PFE. Need to find where that file is and change it to see if that fixes the problem

**Comment by sghung** [comment]
Putting back on backlog so someone else can also investigate in the meantime

**Comment by malincoln** [comment]
@sghung as discussed, we should work to have a fix by dcut this Wednesday.  Thanks

**Comment by sghung** [comment]
Have doc impact: writeup how to connect to docker private registry in the appsody scenario for local

**Comment by sghung** [comment]
Once we verify with kabanero folks that this approach works, then we document, so hold off on documentation until then.

**Comment by sghung** [comment]
We had a meeting on Feb 3rd with the Kabanero folks + Jag. They agreed that the fully qualified stack name in their project is an appropriate solution. Previously, before that was a standard for Appsody stacks, they were more resistant to it. If this approach works, we will document it. I will followup with the contact person today.

**Comment by sghung** [comment]
Currently waiting on appody folks to help kabanero folks generate stacks with fully qualified name. Currently in discussion with appsody and kabanero folks on slack.

**Comment by sghung** [comment]
Still need to document doing the docker login. We should document the rebuild scenario too (even though it doesn't work for tWAS or katsura).

**Comment by mtamboli** [comment]
From what we tried earlier, it seems like the suggested workaround should work although we could not fully test it as discussed. 

@sghung @makandre Please document the workaround. We will try to verify the workaround in our next release testing.

Do you still want to keep the defect open for final fix and reduce the severity?

**Comment by sghung** [comment]
TODO: Need to review Andrew's doc draft and put into this issue for ID

**Comment by makandre** [comment]
I wrote some steps here https://github.com/kabanero-io/kabanero-foundation/issues/127#issuecomment-584159013

**Comment by malincoln** [comment]
@sishida just making sure this is on your radar as Kabanero team is awaiting the link for the workaround for their 0.6.0 release.  Thanks

**Comment by sghung** [comment]
@sishida and @makandre 

From Andrew's kabanero link above. I think we should document the fully qualified case only. We don't recommend people use relative paths as we know there are issues associated with failures after init (https://github.com/appsody/stacks/issues/610). So even if they did the workaround, since it failed on init, there is no way to recover.

My modification of Andrew's original comment:

Using Appsody Stacks Images from Private Docker Registries

**Local Scenario**
If the stack: property in the project's .appsody-config.yaml file is fully qualified out-of-the-box, i.e. it is of the form hostname[:port]/username/reponame[:tag], do this:
- On the local system, do a docker login to the private registry

When viewing the application log, you may see failures to pull the image during a rebuild, however it will be taking the cached Docker image from your local machine. If you ever delete that image, you will need to pull the image again. You can either create another project from the same stack or manually call a `docker pull` with the required image.

**Remote Scenario**
Follow the instructions in https://www.eclipse.org/codewind/image-registry-credentials.html (sghung: please put the relative path. I am putting the URL just so you know which URL I am referencing)

**Comment by makandre** [comment]
Since we're saying we only support fully qualified, I think we can remove the second bullet under notes and merge it into the first sentence (i.e. replace "If the stack: property..." with more concrete wording)

**Comment by sghung** [comment]
Thanks Andrew, I have removed the second bullet and integrated it into the first sentence

**Comment by sishida** [comment]
@sghung and @makandre, Just to make sure I put this content in the correct place...we want to add this new info into this section of the Troubleshooting docs, right? https://www.eclipse.org/codewind/troubleshooting.html#appsody-with-codewind

**Comment by sghung** [comment]
@sishida I am fine with putting it there for now. Originally I thought we should create a new section, but given that appsody work is slowing down, I don't think it makes sense to add a new section outside of the troubleshooting page with this info. Since all the other appsody info is in the troubleshooting, I am fine with putting it there

**Comment by sishida** [comment]
@sghung @makandre Hi, team, here is the PR: https://github.com/eclipse/codewind-docs/pull/363

Please note that because of changes to Che documentation, the https://www.eclipse.org/codewind/image-registry-credentials.html page doesn't exist anymore. Instead, we're going to add this page: https://github.com/eclipse/codewind-docs/pull/310/files.

**Comment by sishida** [comment]
With the merging of https://github.com/eclipse/codewind-docs/pull/363, docs are complete.

**Comment by malincoln** [comment]
@sghung is this read to be moved to Verify?

**Comment by mtamboli** [comment]
I could verify the workaround with private registry.

1. Make sure to do `docker login <registry URL> -u <user>`
2. Stack was created so that the .appsody-config.yaml generated file has .stack: <registry>/kabanero/svt-springboot:0.3
With this, project initialization works fine in codewind and it is able to pull the image but you still see an error as the pod is not able to login:
```
<registry>/kabanero/svt-springboot/manifests/0.3: unknown: Authentication is required
[Warning] Docker image pull failed: exit status 1
```
So the workaround works but not the clean solution.

**Comment by micgibso** [comment]
Docs complete, removing docs label, if you require further changes please add the label back in and let us know. Thanks.

**Comment by malincoln** [comment]
@mtamboli @sghung I believe this can be closed now as you are tracking the new fix with https://github.com/eclipse/codewind/issues/1306?

**Comment by mtamboli** [comment]
Thanks @malincoln I will close this defect as you have another one for more permanent fix.
