### ISSUE TITLE
Separate "sync" and "build" ignore filters for filewatcherd

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#943]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description of the enhancement:**

@jgwest can explain this better.

There is currently one set of `ignorePath` filter, which controls what files should not trigger a build, and hence should not be synced from the filesystem to PFE.

But this does not support the use case of extension projects (such as Appsody) that perform their own file monitoring to determine when to build.

In these cases, all files should be synced to PFE, but they should **not** trigger Codewind to build the project.

So there should be separate filters to control the "sync" and "build" behaviour

Related: #818 #939

**Proposed solution:**

**Comment by jgwest** [comment]
Exactly: previously we had only one filter, which controlled (only) filewatcher's file change detection.

However, if Appsody is going to use a `*/*` filter to prevent builds, we need to separate the filters as Andrew described above (likely this work would be in PFE).

For more detail and a diagram of the workflow, see my comment here:
https://github.com/eclipse/codewind/issues/818#issuecomment-545573418

**Comment by yangcao77** [comment]
I can work on this issue.

**Comment by elsony** [comment]
One thing that I have discussed on a meeting with @makandre  is that if we can stay on only one list instead of creating a new list for it.  At the end of the day, it is the Appsody extension implementation that decides that it doesn't need build.  Andrew will take a look at to see if it is possible to setup the properly list of files for the sync build do a no op when Appsody get called for a build.

**Comment by makandre** [comment]
Yes I checked the code, and for a "build" the extension already does very little; we don't take the container down.  But minimally we still had to issue some build/app status change events (this was needed to address some state display issues in IDE).  So in turn that would cause project status events etc. to be emitted by Turbine.

It's not the end of the world but it does result in some unnecessary event and state changes.  If we had a filter that allowed us to not trigger a Codewind build on file changes, that would eliminate those events altogether.

**Comment by yangcao77** [comment]
In my opinion, Turbine does not need a separate filter. Since for other project types, the filter will be exactly the same, and the filtering is already done by cwctl/filewatcherd. Appsody project is the only exception. 
In addition, the `ignoredPaths` filter is controller by user in the `.cw-settings` file; however, appsody implementation does not support that, and still decides whether to build or not by itself. 

Talked with @makandre that we think a simpler way to handler that is to have a boolean property in the projectHandler, so we know if this build should be triggerred by Turbine or the projetc extension itself.

**Comment by rajivnathan** [comment]
@makandre Can you please verify?

**Comment by makandre** [comment]
I verified it on master, thanks.
