### ISSUE TITLE
[IntelliJ] Add file-watcher to notify backend of project file changes

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind#983]

**Comment by jgwest** [comment]
## How to integrate filewatcher with intellij:

#### 1) Create a new plugin in intellij. It will have contents like this:
https://github.com/jgwest/codewind-eclipse/tree/intellij-filewatcher/dev/org.eclipse.codewind.filewatchers.intellij

This plugin will contain a single class `CodewindIntelliJFilewatcherdConnection.java` (like above), whose job it is to serve as the glue between Codewind-IntelliJ and the Filewatcher.

(I don't actually know about what a 'plugin' is in Intellij, so I'm going to use the Eclipse terminology for this stuff, and hopefully it translates)


#### 2) Next, build these two projects from the `codewind-eclipse` projects as JARs, and include them in the above plugin.

JARs:
- `org.eclipse.codewind.filewatchers.standalonenio` - Contributes an `IProjectWatcher` based on the JVM's built-in `java.nio.file.WatchService` class.
- `org.eclipse.codewind.filewatchers.core` - The "core" filewatcher code that has various functions including calling the above `IProjectWatcher`, and communicating file changes to Codewind Server/Turbine/CWCTL.


#### 3) In Codewind-IntelliJ, whenever your code creates a new Codewind connection (for example, in Codewind Eclipse, when the user opens the 'Codewind Explorer' view and then clicks on the local connection, or when they define a remote connection), you need to call this constructor in order to start the Filewatcher.

```java
var filewatcherConnection = CodewindIntelliJFilewatcherdConnection(String baseHttpUrl, File pathToCwctl,
			IAuthTokenProvider authTokenProvider /* nullable */);
```

You should only call this once per Codewind server, per workbench launch, and you need to store the reference to this object for step 3.

#### 4) When the user closes a Codewind connection (for example, they delete the connection in 'Codewind Explorer', or they stop Codewind) you need to call  `yourcodewindIntelliJFilewatcherdConnectionObj.dispose()`. 

This tells the filewatcher to shutdown (stop issuing HTTP/WebSocket requests, stop all threads, etc).

#### 5) What are the parameters that are passed to `CodewindIntelliJFilewatcherdConnection`?
- `baseHttpUrl`: The `http://` or `https://` URL of the Codewind server (including port). Codewind IntelliJ should already have this.
- `pathToCwctl`: Filewatcher requires a path to a valid `cwctl` install in order to work; Codewind IntelliJ should already have this.
- `authTokenProvider`: When connecting to a remote Codewind install, Filewatcher needs an auth token; filewatcher gets this from the IDE (which should already have this token) by calling this interface. It is up to you to implement this interface to provide filewatcher the appropriate token (see https://github.com/eclipse/codewind/issues/1309 for details.)

**Comment by jopit** [comment]
For step 1, it should just be creating a new class in our existing IntelliJ plugin -- IntelliJ doesn't have the concept like an Eclipse feature which packages multiple bundles into a singe install unit.

**Comment by keithchong** [comment]
@jgwest, one thing I didn't mention was that in step one, the class is missing an import:
import org.eclipse.codewind.filewatchers.JavaNioWatchService;
